### PR TITLE
Ethiopic script import prep

### PR DESCRIPTION
**Pull request by chrissimpkins**
Related #444 

Moves Ethiopic sources and associated import documentation into an ethiopic sub-directory of our source dir.  

The sources were moved as of downstream commit https://github.com/NeilSureshPatel/google-sans-ethiopic/commit/bc12204a2782583d6f3da3f3ccd6e40c244933b8.

Following the move, revision 98d812d5d1b295e4834b09070dc5df023fa4b4a9 was pushed based on the discussion with @NeilSureshPatel in https://github.com/NeilSureshPatel/google-sans-ethiopic/issues/20.

cc @madig. This is a temp branch that will be used to move the sources over to you and allow Neil to see the feature file edit that I made.

@NeilSureshPatel Nikolaus will open a new PR for the import and we will ping you and Mark as soon as sources/fonts are ready for your review. 

---

### TODO on import:

- [ ] Include languagesystem `ethi` prefix  in our family_uprights.fea and family_italics.fea feature files (`languagesystem ethi dflt;`)
- [ ] Include Neil's feature file fix in commit https://github.com/NeilSureshPatel/google-sans-ethiopic/commit/c56990eb6838ce2550e6155516e7c83fe7dbf4a7

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Neil fixed a minor feature file bug in https://github.com/NeilSureshPatel/google-sans-ethiopic/commit/c56990eb6838ce2550e6155516e7c83fe7dbf4a7

I need to pull this change into the upstream source in this branch.

**Comment by madig** [comment]
I can't access Neil's repo :)

**Comment by madig** [comment]
Hm, the glyphs `geez-part-(59|60|61|62)` exist in Italic but not in the Uprights, do we need separate import lists?

Edit: nevermind, I recreated them myself. Also had to fix up the feature file because it was invalid.

**Comment by chrissimpkins** [comment]
I can push the feature file change from his repo.  It sounds like you are already working on the files.  Mind opening the PR and I will push the change today?

**Comment by chrissimpkins** [comment]
> Hm, the glyphs `geez-part-(59|60|61|62)` exist in Italic but not in the Uprights, do we need separate import lists?
> 
> Edit: nevermind, I recreated them myself. Also had to fix up the feature file because it was invalid.

Will you ping @NeilSureshPatel on the commit where you made these changes so that he can have a look?

**Comment by madig** [comment]
All done in #451.

I saw the kerning groups are missing a script tag, so you have groups like `public.kern1.ddaa` without a clear indicator it's about Ethiopic.

**Pull request closed without merging**
