### PR TITLE
Remove r-ligatures (based on main branch)

### PR DESCRIPTION
**Pull request by chrissimpkins**
Cherry pick of commits https://github.com/googlefonts/googlesans/commit/2618e4cc58d66845857627377ee567b7d9db5009 and https://github.com/googlefonts/googlesans/commit/8554f1973110fdf9be9b57fc5b085146524d75c6 that are in the latin-extension-dama branch which will land after the v10 release.  This PR pulls the v10 targeted r-ligature changes into a branch based on main so that we can merge for the v10 release.

cc @mariannapaszkowska mind reviewing and merging if these are the changes that you expect?

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@madig please let us know if there are any concerns about merging the cherry picked commits here before #517 lands

**Review by MariannaPaszkowska — APPROVED** [review]

**Comment by MariannaPaszkowska** [comment]
Thank you @chrissimpkins, @belluzj, @madig!

**Comment by Hoolean** [comment]
> Please let us know if there are any concerns about merging the cherry picked commits here before #517 lands

Hello @MariannaPaszkowska @chrissimpkins,

I do see that Marc [highlighted that removing the ligatures could cause reflow](https://github.com/googlefonts/googlesans/pull/517#issuecomment-1271807675); is this an issue in v10?

Aside from this, there are no issues with changing the merge order that we're aware of : )

**Comment by chrissimpkins** [comment]
Yes, it's going to create havoc for the pixel-level screenshot diff testing. Everything will break.

But the H metric change is relatively subtle. If product teams in very tight text quarters raise issues we can revisit the decision.  IMO we are ok.

r-lig

**Pull request merged**
