### PR TITLE
Import Khmer

### LINKED ISSUE #446: Add Khmer script support

### PR DESCRIPTION
**Pull request by madig**
Closes #415.
Closes #446

---

@chrissimpkins edits below:

- test string for tall / deep glyph testing: `ប៊ិនទៅកម្មវិធីលក់នំធ្វើពីផ្លែប៊័រ   ក្នុងទឡ្ហីករណ៍ដែល​នាង​លក្ស្មី​បង្ហាញហ្វ្លូ`

---

### TODO

- [x] add Apache license to all new Python scripts in `scripts/khmer-import` dir
- [x] open issue on below base vowel sign collision in bold https://github.com/googlefonts/googlesans/issues/453
- [x] open issue on base form + vowel sign ligature separation issue in bold opsz 17 (https://github.com/googlefonts/googlesans/issues/454)

### CODE REVIEW

**Comment by madig** [comment]
Todo: investigate diffs between vendor sources and import:

```txt
In [17]: t1 = TTFont(r"\\wsl$\Ubuntu-20.04\home\nikolaus\googlesans-khmer\build\GoogleSans\variable\GoogleSans[GRAD,ops
    ...: z,wght].ttf")

In [18]: t2 = TTFont(r"c:\UsersLocal\nikolaus.waxweiler\Downloads\otf\Khmer\GoogleSansKHLooped-Regular.otf")

In [19]: gdef = t2["GDEF"].table.GlyphClassDef.classDefs

In [21]: gdef2 = t1["GDEF"].table.GlyphClassDef.classDefs

In [22]: for k, v in gdef.items():
    ...:     if k not in gdef2:
    ...:         print("not available", k)
    ...:         continue
    ...:     if v != gdef2[k]:
    ...:         print("not matching", k, v, gdef2[k])
    ...:
not available uni1794.alt
not available uni17A8
not available uni17D8
not available uni17D217A9
not available uni17D217AD
not available uni17D2178C.below2
not available uni17BE
not available uni17CF.narrow
not matching uni17D21789.full.below.narrow 3 1
not matching uni17D2178E.narrow1 3 1
not matching uni17D2178E.narrow2 3 1
not matching uni17D2178A.ro 3 1
not available uni17D2178F.ro
not matching uni17D21796.ro 3 1
not matching uni17D21797.ro 3 1
not matching uni17D21798.ro 3 1
```

**Comment by madig** [comment]
Todo: find out why some glyphs in the vendor-supplied fonts have a different production name from what Glyphs.app says 🤨 e.g.  `quu-khmer.below`: vendor font says `uni17D217A9` but Glyphs.app 2.6.5 says `uni17A9.below`.

**Comment by madig** [comment]
Hm, anchor propagation doesn't work as expected, e.g. for `ta-khmer....` marks.

**Comment by madig** [comment]
I think I know what's happening:

https://github.com/googlefonts/ufo2ft/blob/2cbc47930a88b64b8e2cac3b344290c3a6d222e1/Lib/ufo2ft/filters/propagateAnchors.py#L79

Since ta-khmer is a mark without a "base", the `_is_ligature_mark(composite)` part of the if clause stops its execution and no "base" is found, hence no copying of anchors. It's easy to run the clause by doing `and (_is_ligature_mark(composite) or len(mark_components) == 1)` but I'm not sure this is the correct fix. @anthrotype 

@chrissimpkins this potentially needs a change in ufo2ft's anchor propagation filter, which may end up being rather time consuming (also think switching GS to use the new version)... Another thing I can try is making a list of glyphs the vendor should manually propagate anchors to 🤔

**Comment by chrissimpkins** [comment]
Does the issue affect the Lao or is this Khmer only?

**Comment by madig** [comment]
I skimmed Lao and found no obvious anchor propagation problem (as in, all glyphs that have anchors in the vendor fonts also have anchors in our final font), but only a more detailed check by our font designer will reveal more.

**Comment by madig** [comment]
This branch requires https://github.com/googlefonts/ufo2ft/pull/565 to generate the needed features.

**Comment by chrissimpkins** [comment]
> This branch requires [googlefonts/ufo2ft#565](https://github.com/googlefonts/ufo2ft/pull/565) to generate the needed features.

Np.  We can begin to look into what changes with an update to v3.x fontmake.  Any idea how much effort it will be to work the ufo2ft changes into fontmake?  Please let me know what version of the compiler we should target when you know.  Ty for patching the lib!

**Comment by chrissimpkins** [comment]
@madig Possible to build fonts with your branch of ufo2ft so that the Cadson-Demak team can have a look in the meantime?  If this is a big effort, no worries.  We will do it when we can.

**Comment by madig** [comment]
I can shortly mail them built fonts directly if that's ok?

**Comment by chrissimpkins** [comment]
> I can shortly mail them built fonts directly if that's ok?

perfect! ty!

**Comment by chrissimpkins** [comment]
test string for tall / deep glyph testing: `ប៊ិនទៅកម្មវិធីលក់នំធ្វើពីផ្លែប៊័រ   ក្នុងទឡ្ហីករណ៍ដែល​នាង​លក្ស្មី​បង្ហាញហ្វ្លូ`

**Comment by belluzj** [comment]
@chrissimpkins I rebased this on top of the latest Lao

**Comment by chrissimpkins** [comment]
Thanks @belluzj! I think that the next step is to look into the diff from a fontmake compiler version bump to get the Khmer updates.

**Comment by belluzj** [comment]
Should I update fontmake in this PR?

**Comment by chrissimpkins** [comment]
We will need to understand the diff for non-Khmer things.  It might be easier to start with main or the v6.000 commit because we are expecting a diff on the Khmer data.

**Comment by belluzj** [comment]
I opened a PR here: https://github.com/googlefonts/googlesans/pull/429

There's a merge conflict because main also contains other (smaller) requirements updates, if you'd like I could also rebase the PR on top of main. Also, the fonts seem to not build with newer fontmake, because it picks up a compatibility issue in a BRACKET glyph, which is not actually used in the fonts (if I remember correctly that we have deprecated the use of bracket layers)

**Comment by chrissimpkins** [comment]
> I opened a PR here: https://github.com/googlefonts/googlesans/pull/429
> 
> 
> 
> There's a merge conflict because main also contains other (smaller) requirements updates, if you'd like I could also rebase the PR on top of main. Also, the fonts seem to not build with newer fontmake, because it picks up a compatibility issue in a BRACKET glyph, which is not actually used in the fonts (if I remember correctly that we have deprecated the use of bracket layers)

thanks Jany!

Hmm.  We shouldn't be compiling any glyphs that require bracket / rvrn support at this stage.  These should all be removed from the design space files.  I will have a look at the error you are seeing.

**Comment by chrissimpkins** [comment]
Moved the Khmer script release to GS v8.000.  We need more time to update the compiler pipeline, understand what changes in GS with the pipeline update, and review the imported designs with the pipeline updates that were required to build Khmer.

**Comment by chrissimpkins** [comment]
Lol.

https://github.com/googlefonts/googlesans/blob/3ccc3d53b0f7f285d4d8fa85359de82e6d982599/scripts/gs-glyphs2ufo.py#L71

**Comment by chrissimpkins** [comment]
Looks like we need a rebase here?  A couple of pipeline patch release differences vs. main branch.

**Comment by chrissimpkins** [comment]
I contacted Tep today to find out where we are with the Cadson-Demak review.

**Comment by chrissimpkins** [comment]
Tep approved the designs for production prior to the latest rebase.  The rebase @ https://github.com/googlefonts/googlesans/commit/175f6fdfbaace83bd7788dac659f3b5dad718543 brings in new source cleaning updates @madig?

**Comment by madig** [comment]
It only normalizes something in lib.plist and adds info to some glyphs to make normalization not change anything. Before, the glyphs were automatically marked "base" in the italics during normalization (but stayed marks in uprights because the uprights have the correct category lib key info).

**Comment by madig** [comment]
Background: for some reason, the GDEF normalization logic thinks the glyphs I added the lib info to are bases, while Glyphs.app makes them marks. The uprights carried the explicit lib info, which the GDEF logic acknowledges instead of overwriting it. So, I added the lib info from the uprights to the italics to make normalization do the right thing :) I just didn't run normalization before, which is why it showed up now.

**Comment by chrissimpkins** [comment]
Auto-rebased on main branch with the #441 changes that just landed in main.  Nothing to do here.

**Comment by chrissimpkins** [comment]
A comparison of the Google Sans Khmer character set in this branch with Noto Sans Khmer shows the following missing encoded forms in Google Sans:

- U+17A3
- U+17A4
- U+17B4
- U+17B5

OK based on the [Unicode 14.0 documentation in Chapter 16 Southeast Asia, header "Characters Whose Use is Discouraged"](https://www.unicode.org/versions/Unicode14.0.0/ch16.pdf) below:

> **U+17A3** khmer independent vowel qaq and **U+17A4** khmer independent vowel qaa are deprecated, and their use is strongly discouraged. One feature of the Khmer script is the introduction of the consonant character for a glottal stop (U+17A2 khmer letter qa).This made it unnecessary for each initial vowel sound to have its own independent vowel character, although some independent vowels exist. Neither U+17A3 nor U+17A4 actually exists in the Khmer script. Other related scripts, including the Devanagari script, have independent vowel characters corresponding to them (a and aa), but they can be transliterated by khmer letter qa and khmer letter qa + khmer vowel aa, respectively, without ambiguity because these scripts have no consonant character corresponding to the khmer qa.

> The use of **U+17B4** khmer vowel inherent aq and **U+17B5** khmer vowel inherent aa is discouraged. These newly invented characters do not exist in the Khmer script. They were intended to be used to represent a phonetic difference not expressed by the spelling, so as to assist in phonetic sorting. However, they are insufficient for that purpose and should be considered errors in the encoding. These two characters are ignored by default for collation.

**Comment by chrissimpkins** [comment]
@madig do the anchor changes in dottedC_ircle.glif across all masters affect any non-Khmer scripts?  These changes were made to support Khmer for some reason?

**Comment by chrissimpkins** [comment]
@madig will you please add our Apache license declaration to the head of all of the new Python scripts:

- scripts/khmer-import/copy_anchors.py
- scripts/khmer-import/fix_psnames.py
- scripts/khmer-import/mark_base.py
- scripts/khmer-import/move_marks.py

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/issues/453

Not a merge blocker. I'll discuss it with the C-D team.

**Comment by madig** [comment]
> @madig do the anchor changes in dottedC_ircle.glif across all masters affect any non-Khmer scripts? These changes were made to support Khmer for some reason?

Apparently some Khmer marks use the bottomright anchor (i.e. uaMark-khmer). Since it's additive, I'm not expecting it to break anything. There are a few non-Khmer glyphs however also using it before, like rakar-deva.short and dehi-hb. I don't know the significance of this, my guess is that they were not properly attaching to the dottedCircle before, if that is even relevant.

**Comment by chrissimpkins** [comment]
> There are a few non-Khmer glyphs however also using it before, like rakar-deva.short and dehi-hb. I don't know the significance of this, my guess is that they were not properly attaching to the dottedCircle before, if that is even relevant.

I can't think of any uses outside of maybe proofs of mark forms for internal users.  Are you aware of any other use cases for the dotted circle?

**Comment by madig** [comment]
Nothing other than what I found in https://github.com/googlefonts/fontbakery/issues/3600.

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/issues/454

Not a merge blocker.  I will discuss the issue with the Cadson-Demak team.

**Comment by chrissimpkins** [comment]
Thank you very much @cadsondemakoffice, @madig, & @belluzj!

**Pull request merged**
