### PR TITLE
corrections on Greek polytonic

### LINKED ISSUE #323: Polytonic upper case Greek accented spacing updates
From Irene Vlachou

Pushed in commit 1f5788c106b6e0c229b7e772547ce0ae64355b6d

### PR DESCRIPTION
**Pull request by irenevlachou**
corrections on Greek polytonic LSB and composition of marks: dasia.ca…se tonos.sc psili.sc varia.sc dasia.sc

fixing issues: #141 and #323

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@madig D/W Irene today.  All required changes for import to address #141 and #323 are available as of https://github.com/googlefonts/googlesans/commit/bc1e99398928151857eeb3cec908a85f2342cd42 in the Greek-polytonic branch (used in this PR).

The changed glyph lists are available in https://github.com/googlefonts/googlesans/issues/323#issuecomment-916105056

**Comment by madig** [comment]
Had a quick look and I see a bucket load of components changes plus some contours being turned into components, I like. I don't see any kerning changes though?

Edit: note to self, modify PR to not contain layerinfo.plist, fontinfo.plist and lib.plist changes.

**Comment by chrissimpkins** [comment]
> Had a quick look and I see a bucket load of components changes plus some contours being turned into components, I like. I don't see any kerning changes though?

My understanding is that the changes here are all that we should expect to address both IR's.

**Comment by madig** [comment]
Uhm, ok, but #323 has "kerning class updates" in the title?

**Comment by chrissimpkins** [comment]
> Uhm, ok, but #323 has "kerning class updates" in the title?

@irenevl Irene will you please confirm.  I believe that you said that you decided not to change kerns?

**Comment by irenevlachou** [comment]
yes, spacing was enough and there was no kerning updated.

**Comment by madig** [comment]
@googlebot I consent.

**Comment by chrissimpkins** [comment]
@madig what is the status of this PR?

**Comment by madig** [comment]
Ready to merge.

**Comment by chrissimpkins** [comment]
Manual static font CI run: https://github.com/googlefonts/googlesans/actions/runs/1267252000

**Comment by chrissimpkins** [comment]
> Manual static font CI run: https://github.com/googlefonts/googlesans/actions/runs/1267252000

passed

**Comment by chrissimpkins** [comment]
Gtg.  Thank you very much for these edits Irene!  And thanks for merging this Nikolaus!

**Pull request merged**
