### PR TITLE
Reimport circled numbers

### LINKED ISSUE #269: Negative circled sans-serif digit glyphs require slant and grade support
U+278A - U+2793

The DINGBAT NEGATIVE CIRCLED SANS-SERIF [numeral] glyphs have the following issues as of the GoogleSans 4.000 RC1 builds.

- GS Italic opsz 17 are not slanted forms, wght 400-700
- GS Italic opsz 18, wght 700 is not slanted, wght 400 are slanted
- GS Roman opsz 18 and 17 do not have grade support (Italic does)

### PR DESCRIPTION
**Pull request by madig**
Closes https://github.com/googlefonts/googlesans/issues/269.

Note that GRAD for these has been removed upstream.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@dberlow The design changes to support the circled numbers here also affect the `numr`, `dnom`, and `frac` forms.  Your changes removed GRAD support from these figures (except zero) so we lose GRAD in all 0-9 numerators, denominators, and figures in fraction displays.  The solidus does have GRAD support in the fractions. 

We'll need to sort out a consistent approach across these figure sets.  Possible to add GRAD across the numerator and denominator forms so that we do not lose it in areas outside of the circled number dingbats?

**Review by chrissimpkins — CHANGES_REQUESTED** [review]
Blocked on the resolution of https://github.com/googlefonts/googlesans/pull/311#issuecomment-857212084

**Comment by dberlow** [comment]
What was not solved and made consistent in #269?

**Comment by chrissimpkins** [comment]
> What was not solved and made consistent in #269?

- numr forms now include zero with grade support, 1 - 9 without
- dnom forms now include zero with grade support, 1 - 9 without
- frac figs 1 - 9 do not have grade support, the solidus does and weight changes for the solidus but not the 1 - 9 figures in fractions along GRAD axis

**Comment by chrissimpkins** [comment]
> > What was not solved and made consistent in #269?
> 
> * numr forms now include zero with grade support, 1 - 9 without
> * dnom forms now include zero with grade support, 1 - 9 without
> * frac figs 1 - 9 do not have grade support, the solidus does and weight changes for the solidus but not the 1 - 9 figures in fractions

The circled figs all look good though!

This is a new issue that was identified as we imported the changes for the circled figure dingbats.  I didn't realize that these changes were components of our numerator forms.

**Pull request closed without merging**
