### PR TITLE
Flatten components

### LINKED ISSUE #108: Remove component nesting
We have over 1000 nested components in the GS / GST designs. In the latest fontbakery release, this design approach is flagged as a fail in the new `com.google.fonts/check/glyf_nested_components` universal profile check.

Our CI: https://github.com/googlefonts/googlesans/runs/1453872062?check_suite_focus=true

fontbakery rationale: https://github.com/googlefonts/fontbakery/issues/2961

We'll need to address this new fail. Niko proposed unnesting components at compile time with the approach in https://github.com/googlefonts/fontbakery/issues/2961#issuecomment-733745539.

Let's investigate further and determine how we should address this.

cc @Colophon-Foundry @madig @belluzj 

Requires #246 

---

### TODO

- [x] confirm that there is no regression with required ufo2ft dependency bump (https://github.com/googlefonts/googlesans/issues/246)
- [x] update ufo2ft
- [x] remove nested components
- [x] eyeballs on modified glyphs (glyph lists attached in text files below)

[Regular.txt](https://github.com/googlefonts/googlesans/files/6083938/Regular.txt)
[Italic.txt](https://github.com/googlefonts/googlesans/files/6083941/Italic.txt)

### LINKED ISSUE #116: Reimplement fontbakery QA check for nested components
The nested component validation check was removed from our custom fontbakery check profile in commit https://github.com/googlefonts/googlesans/commit/a097840bee579d3198b1ad79bdefd4682953fa3d as part of the fontbakery profile fixes that were added in https://github.com/googlefonts/googlesans/pull/107.  This is being performed so that we have a functional CI during the transition to the UFO source format (PR #105) and before we address the recursive component issue in our build process.

This check is desired and will need to be added back to the QA testing in this project.  

Associated tracking issues for nested components https://github.com/googlefonts/googlesans/issues/108

### PR DESCRIPTION
**Pull request by madig**
Closes https://github.com/googlefonts/googlesans/issues/116
Closes https://github.com/googlefonts/googlesans/issues/108

---

@chrissimpkins edits below:

### TODO

- [x] calculate file size change in the production character set with these updates (https://github.com/googlefonts/googlesans/pull/124#issuecomment-761581545)
- [x] review and address inappropriate component edits initially documented in https://github.com/googlefonts/googlesans/pull/124#issuecomment-761576389 across all styles / build formats
- [x] review glyph order change after component flattening, why is this different across styles?
- [ ] further review and discuss glyph delta issue in https://github.com/googlefonts/googlesans/pull/124#issuecomment-763246768
- [ ] discuss mark delta issue in https://github.com/googlefonts/googlesans/pull/124#issuecomment-763246768 and https://github.com/googlefonts/googlesans/pull/124#issuecomment-763252993

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Hmm...

Statics fail with a new fontbakery FAIL:

```
 >> com.google.fonts/check/googlesans/glyphs/glyphset-contents
    Confirm that fonts have all expected Unicode encoded and        non-Unicoded encoded glyph definitions.This test also confirms        that the glyph order is defined as expected.
    

      Rationale:                                                                
      irms that the fonts include all expected Unicode encoded and              
      non-Unicode encoded glyph definitions. This test also confirms that       
      fonts have the expected glyph order.                                      

    * FAIL: build/GoogleSans/static/expert/GoogleSansText-Medium.ttf failed expected glyph set check
    * FAIL: build/GoogleSans/static/expert/GoogleSansText-BoldItalic.ttf failed expected glyph set check
    * FAIL: build/GoogleSans/static/expert/GoogleSansText-MediumItalic.ttf failed expected glyph set check
    * FAIL: build/GoogleSans/static/expert/GoogleSans-Regular.ttf failed expected glyph set check
    * FAIL: build/GoogleSans/static/expert/GoogleSans-Bold.ttf failed expected glyph set check
    * FAIL: build/GoogleSans/static/expert/GoogleSansText-Regular.ttf failed expected glyph set check
    * FAIL: build/GoogleSans/static/expert/GoogleSans-Medium.ttf failed expected glyph set check
    * FAIL: build/GoogleSans/static/expert/GoogleSansText-Bold.ttf failed expected glyph set check
    * FAIL: build/GoogleSans/static/expert/GoogleSans-MediumItalic.ttf failed expected glyph set check
    * FAIL: build/GoogleSans/static/expert/GoogleSans-Italic.ttf failed expected glyph set check
    * FAIL: build/GoogleSans/static/expert/GoogleSans-BoldItalic.ttf failed expected glyph set check
    * FAIL: build/GoogleSans/static/expert/GoogleSansText-Italic.ttf failed expected glyph set check


    Result: FAIL
```

**Comment by chrissimpkins** [comment]
Sorry, this is our own custom check.  This is coming from the custom FB check profile.  We'll need to redefine the expected glyph list / order lists in https://github.com/googlefonts/googlesans/tree/master/qa/definitions

**Comment by chrissimpkins** [comment]
I write these with:

```python
#!/usr/bin/env python3

import sys

from fontTools.ttLib import TTFont


def main(argv):
    for font in argv:
        tt = TTFont(font)
        write_path = font + ".glyphsetdef"
        try:
            with open(write_path, "w") as f:
                text = "\n".join(tt.getGlyphOrder())
                f.write(text)
            print(f"Successful write of {write_path}")
        except Exception as e:
            sys.stderr.write(f"[FAIL] Error during write of {font}: {e}\n")
            sys.exit(1)

if __name__ == "__main__":
    main(sys.argv[1:])
```

This is intended as a flag to know when we do something that edits names/glyph set/glyph order.  Will be an annoyance as we merge new scripts and there are frequent glyph changes but I think that it is a useful check to keep in place.

**Comment by chrissimpkins** [comment]
pushed a build-flatten-components branch to build the fonts so that we can update the glyph name/order definitions

**Comment by chrissimpkins** [comment]
it looks like brevecombcy.sc and brevecombcy.cap is going away.  Not consistent which one is eliminated across builds.  I'll push a PR so that you can see the glyph order lists.  This intentional?

**Comment by chrissimpkins** [comment]
#126

**Comment by madig** [comment]
💭 Why does the glyph name/order change when we flatten components? Makes no sense to me. Is there some subsetting going on?

**Comment by madig** [comment]
Oh right, `gs-subset.py`. It makes sense then, because some composite glyphs are probably just used while designing.

**Comment by chrissimpkins** [comment]
Thoughts about why the outlines removed might differ across styles? I will take a look at the ttx diff pre/post here.

**Comment by chrissimpkins** [comment]
New issue:

It looks like we are inappropriately re-defining some of the components with this change.

Here is an example with the Aringacute glyph in GoogleSans-Regular.ttf (static) builds with pre = master branch @ https://github.com/googlefonts/googlesans/commit/9277115d6fd870cf7ac3a66af2c26d6d1cd29da6, post = flatten-components branch @ https://github.com/googlefonts/googlesans/pull/124/commits/94b2fbf5f64237a76937986a3344705e90d0e182:


#### partial glyf table ttx diff

```diff
     <TTGlyph name="Aringacute" xMin="15" yMin="0" xMax="655" yMax="933">
-      <component glyphName="Aring" x="0" y="0" flags="0x204"/>
+      <component glyphName="A" x="0" y="0" flags="0x204"/>
       <component glyphName="acutecomb" x="130" y="197" flags="0x4"/>
     </TTGlyph>
```

#### diffenator rasterization diff

glyphs_modified

Full glyph set with visual diff in Regular static builds (diffenator std out):

```
****glyphs modified: 9****

glyph               diff                string
oslashacute.sc      0.2099              Ǿ
uni0472             0.2091              Ѳ
uni04EA             0.193               Ӫ
aringacute.sc       0.1712              Ǻ
Aringacute          0.1202              Ǻ
dcroat.sc           0.1053              Đ
uni0499.loclBSH     0.1012              ҙ
uni0499.loclBSH.... 0.0846              Ҙ
uni0498.loclBSH     0.0792              Ҙ
```

**Comment by chrissimpkins** [comment]
File size change with flattened components (bytes):

#### GoogleSans-Regular.ttf (static instance)

Pre: 295196
Post: 298364  (101%)

#### GoogleSans[opsz,wght].ttf (variable font)

Pre: 618316
Post: 624848 (101%)

#### GoogleSans-Italic[opsz,wght].ttf (variable font)

Pre: 652028
Post: 658680 (101%)

**Comment by moyogo** [comment]
> New issue:
> 
> It looks like we are inappropriately re-defining some of the components with this change.
> 
> Here is an example with the Aringacute glyph in GoogleSans-Regular.ttf (static) builds with pre = master branch @ [9277115](https://github.com/googlefonts/googlesans/commit/9277115d6fd870cf7ac3a66af2c26d6d1cd29da6), post = flatten-components branch @ [94b2fbf](https://github.com/googlefonts/googlesans/commit/94b2fbf5f64237a76937986a3344705e90d0e182):
> #### partial glyf table ttx diff
> 
> ```diff
>      <TTGlyph name="Aringacute" xMin="15" yMin="0" xMax="655" yMax="933">
> -      <component glyphName="Aring" x="0" y="0" flags="0x204"/>
> +      <component glyphName="A" x="0" y="0" flags="0x204"/>
>        <component glyphName="acutecomb" x="130" y="197" flags="0x4"/>
>      </TTGlyph>
> ```
> 

The FlattenComponentFilter doesn't currently handle this case properly.

I've opened https://github.com/googlefonts/ufo2ft/pull/448 the glyphs with contours and components, like Aring (A component, ring contour), can then be used as components without being flattened because they'll be decomposed in TTF anyway.

**Comment by madig** [comment]
The different glyphsets seem to be because `brevecombcy.sc` in the upright sources is a component of `brevecombcy` but in the italic sources is an outline. It can be removed in the upright sources after flattening but not the italic ones.

**Comment by chrissimpkins** [comment]
@googlebot I consent.

**Comment by madig** [comment]
Is this ready or do we need something? 🤔

**Comment by chrissimpkins** [comment]
I'll do a final review of the file size changes if this is wrapped up.  We know that there are no longer component related regressions across all styles of static and VF formats?  If not, I can take a look at that later today.

**Comment by madig** [comment]
We do not know. Thanks!

**Comment by chrissimpkins** [comment]
File size (bytes) `master` branch @ https://github.com/googlefonts/googlesans/commit/d459cf79173b02f7a4c39fc0435650dc0237d95e vs. `flatten-components` branch @ https://github.com/googlefonts/googlesans/commit/c1498bc0805b5b267a121fc730099684637106f7

#### GoogleSans-Regular.ttf (static instance)

Pre: 295196
Post: 298364 (101%)

#### GoogleSans[opsz,wght].ttf (variable font)

Pre: 618316
Post: 624848 (101%)

#### GoogleSans-Italic[opsz,wght].ttf (variable font)

Pre: 652028
Post: 658904 (101%)

**Comment by chrissimpkins** [comment]
diffenator run across static builds, https://github.com/googlefonts/googlesans/commit/d459cf79173b02f7a4c39fc0435650dc0237d95e vs. https://github.com/googlefonts/googlesans/commit/c1498bc0805b5b267a121fc730099684637106f7:

### GoogleSansText-MediumItalic.ttf

```
****glyphs modified: 2****

glyph               diff                string
uni1F89.ad          0.0                 ᾉ
uni1F9B.ad          0.0                 ᾛ
```

glyphs_modified

### GoogleSansText-BoldItalic.ttf

```
****marks_modified: 60****

base_glyph          mark_glyph          diff_x              diff_y
uni0453.loclMKD     uni059C             0.0                 -1.1368683772161...
uni0453.loclMKD     uni0597             0.0                 -1.1368683772161...
uni0453.loclMKD     uni05AB             0.0                 -1.1368683772161...
uni0453.loclMKD     acutecomb           0.0                 -1.1368683772161...
uni0453.loclMKD     uni030C.sc          0.0                 -1.1368683772161...
uni0453.loclMKD     uni05AC             0.0                 -1.1368683772161...
uni0453.loclMKD     tildecomb.sc        0.0                 -1.1368683772161...
uni0453.loclMKD     hookabovecomb.sc... 0.0                 -1.1368683772161...
uni0453.loclMKD     uni03060300         0.0                 -1.1368683772161...
uni0453.loclMKD     gravecomb           0.0                 -1.1368683772161...
uni0453.loclMKD     uni05AE             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03060303.sc      0.0                 -1.1368683772161...
uni0453.loclMKD     uni03020303         0.0                 -1.1368683772161...
uni0453.loclMKD     uni059E             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03020300         0.0                 -1.1368683772161...
uni0453.loclMKD     uni030A             0.0                 -1.1368683772161...
uni0453.loclMKD     uni0594             0.0                 -1.1368683772161...
uni0453.loclMKD     uni0304.sc          0.0                 -1.1368683772161...
uni0453.loclMKD     gravecomb.sc        0.0                 -1.1368683772161...
uni0453.loclMKD     hookabovecomb       0.0                 -1.1368683772161...
uni0453.loclMKD     uni05A8             0.0                 -1.1368683772161...
uni0453.loclMKD     uni0306             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03060301.sc      0.0                 -1.1368683772161...
uni0453.loclMKD     tildecomb           0.0                 -1.1368683772161...
uni0453.loclMKD     uni0307.sc          0.0                 -1.1368683772161...
uni0453.loclMKD     uni0308.sc          0.0                 -1.1368683772161...
uni0453.loclMKD     uni0593             0.0                 -1.1368683772161...
uni0453.loclMKD     uniFB1E             0.0                 -1.1368683772161...
uni0453.loclMKD     uni0308             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03060309         0.0                 -1.1368683772161...
uni0453.loclMKD     uni030A.sc          0.0                 -1.1368683772161...
uni0453.loclMKD     uni030B             0.0                 -1.1368683772161...
uni0453.loclMKD     uni0304             0.0                 -1.1368683772161...
uni0453.loclMKD     uni05BF             0.0                 -1.1368683772161...
uni0453.loclMKD     uni0302.sc          0.0                 -1.1368683772161...
uni0453.loclMKD     uni0592             0.0                 -1.1368683772161...
uni0453.loclMKD     uni030B.sc          0.0                 -1.1368683772161...
uni0453.loclMKD     uni03060303         0.0                 -1.1368683772161...
uni0453.loclMKD     uni0595             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03020309         0.0                 -1.1368683772161...
uni0453.loclMKD     uni03020301         0.0                 -1.1368683772161...
uni0453.loclMKD     uni05A1             0.0                 -1.1368683772161...
uni0453.loclMKD     uni0302             0.0                 -1.1368683772161...
uni0453.loclMKD     uni0312             0.0                 -1.1368683772161...
uni0453.loclMKD     uni05C4             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03020303.sc      0.0                 -1.1368683772161...
uni0453.loclMKD     uni03060300.sc      0.0                 -1.1368683772161...
uni0453.loclMKD     uni030C             0.0                 -1.1368683772161...
uni0453.loclMKD     uni05AF             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03020300.sc      0.0                 -1.1368683772161...
```
marks_modified

All other static instance builds across GS and GST have a clean diff.  

I am not seeing a perceptible difference in the GST-BoldItalic builds and I'm not sure that these are even marks used on the Cyrillic glyph.  We'll need to investigate the GST-MediumItalic issue further.

@madig

**Comment by chrissimpkins** [comment]
diffenator run across variable font builds, https://github.com/googlefonts/googlesans/commit/d459cf79173b02f7a4c39fc0435650dc0237d95e vs. https://github.com/googlefonts/googlesans/commit/c1498bc0805b5b267a121fc730099684637106f7

Analyzed at all named instance positions:

- Google Sans @ 
  - wght=400, opsz=17
  - wght=500, opsz=17
  - wght=700, opsz=17
  - wght=400, opsz=18
  - wght=500, opsz=18
  - wght=700, opsz=18
- Google Sans Italic @ 
  - wght=400, opsz=17
  - wght=500, opsz=17
  - wght=700, opsz=17
  - wght=400, opsz=18
  - wght=500, opsz=18
  - wght=700, opsz=18

The only diff that I see is the GoogleSansText-BoldItalic issue noted in the statics (https://github.com/googlefonts/googlesans/pull/124#issuecomment-763246768) on the GS-Italic wght=700, opsz=17 tests:

```
****marks_modified: 60****

base_glyph          mark_glyph          diff_x              diff_y
uni0453.loclMKD     uni05AF             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03020309.sc      0.0                 -1.1368683772161...
uni0453.loclMKD     uni03060301         0.0                 -1.1368683772161...
uni0453.loclMKD     uni03020300.sc      0.0                 -1.1368683772161...
uni0453.loclMKD     uni0304             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03020303.sc      0.0                 -1.1368683772161...
uni0453.loclMKD     uni030B             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03020309         0.0                 -1.1368683772161...
uni0453.loclMKD     uni03060309.sc      0.0                 -1.1368683772161...
uni0453.loclMKD     uni030A             0.0                 -1.1368683772161...
uni0453.loclMKD     uni030A.sc          0.0                 -1.1368683772161...
uni0453.loclMKD     uni03060303.sc      0.0                 -1.1368683772161...
uni0453.loclMKD     uni05A9             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03060303         0.0                 -1.1368683772161...
uni0453.loclMKD     uni030C.sc          0.0                 -1.1368683772161...
uni0453.loclMKD     tildecomb.sc        0.0                 -1.1368683772161...
uni0453.loclMKD     uni0308             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03020300         0.0                 -1.1368683772161...
uni0453.loclMKD     uni05AB             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03060300         0.0                 -1.1368683772161...
uni0453.loclMKD     uni0307             0.0                 -1.1368683772161...
uni0453.loclMKD     uni05A8             0.0                 -1.1368683772161...
uni0453.loclMKD     hookabovecomb       0.0                 -1.1368683772161...
uni0453.loclMKD     uni0593             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03060309         0.0                 -1.1368683772161...
uni0453.loclMKD     uniFB1E             0.0                 -1.1368683772161...
uni0453.loclMKD     uni030C             0.0                 -1.1368683772161...
uni0453.loclMKD     uni05AC             0.0                 -1.1368683772161...
uni0453.loclMKD     uni059E             0.0                 -1.1368683772161...
uni0453.loclMKD     acutecomb           0.0                 -1.1368683772161...
uni0453.loclMKD     uni0595             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03060300.sc      0.0                 -1.1368683772161...
uni0453.loclMKD     uni0308.sc          0.0                 -1.1368683772161...
uni0453.loclMKD     uni0594             0.0                 -1.1368683772161...
uni0453.loclMKD     uni0302             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03020301.sc      0.0                 -1.1368683772161...
uni0453.loclMKD     acutecomb.sc        0.0                 -1.1368683772161...
uni0453.loclMKD     uni05BF             0.0                 -1.1368683772161...
uni0453.loclMKD     uni0307.sc          0.0                 -1.1368683772161...
uni0453.loclMKD     uni059C             0.0                 -1.1368683772161...
uni0453.loclMKD     uni0312             0.0                 -1.1368683772161...
uni0453.loclMKD     uni05AE             0.0                 -1.1368683772161...
uni0453.loclMKD     uni03020301         0.0                 -1.1368683772161...
uni0453.loclMKD     uni03020303         0.0                 -1.1368683772161...
uni0453.loclMKD     uni0304.sc          0.0                 -1.1368683772161...
uni0453.loclMKD     uni05A1             0.0                 -1.1368683772161...
uni0453.loclMKD     uni05C4             0.0                 -1.1368683772161...
uni0453.loclMKD     uni059F             0.0                 -1.1368683772161...
uni0453.loclMKD     uni0597             0.0                 -1.1368683772161...
uni0453.loclMKD     uni0598             0.0                 -1.1368683772161...
```

marks_modified

Unclear significance as noted in the previous post.

**Comment by chrissimpkins** [comment]
@madig you can repro diffs on issues in https://github.com/googlefonts/googlesans/pull/124#issuecomment-763246768 and https://github.com/googlefonts/googlesans/pull/124#issuecomment-763252993 with:

### Static instance builds

```
diffenator A/GoogleSansText-MediumItalic.ttf B/GoogleSansText-MediumItalic.ttf -r img
diffenator A/GoogleSansText-BoldItalic.ttf B/GoogleSansText-BoldItalic.ttf -r img
```

### Variable builds

```
diffenator A/GoogleSans-Italic\[opsz,wght\].ttf B/GoogleSans-Italic\[opsz,wght\].ttf -i "wght=700, opsz=17" -r img
```

**Comment by chrissimpkins** [comment]
Merge blocked. TODO list in OP updated with outstanding issues to address before we merge.

**Comment by madig** [comment]
That's... curious. I wonder if it has something to do with https://github.com/googlefonts/ufo2ft/pull/450

**Comment by madig** [comment]
Interesting. So, updating to ufo2ft git master plus fontTools 4.18.2, I now get

```
****attribs modified: 1****

table               attrib              value_a             value_b             
head                modified            2021/01/20 14:41... 2021/01/20 14:51... 

****glyphs missing: 3****

glyph               area                string              
uni0592.final       -6846               לֹּ֒                 
uni05A9.final       -9590               לֹּ֩                 
uni05AF.final       -8054               לֹּ֯                 

****gdef_mark missing: 3****

glyph               
uni05AF.final       
uni0592.final       
uni05A9.final
```

**Comment by moyogo** [comment]
> That's... curious. I wonder if it has something to do with googlefonts/ufo2ft#450

Definitely, there's also a problem with glyphs that have components with different transformations than in the default master.

The following glyphs have transformed (scaled or flipped) components that also have different transformations in different masters:
```
dasia: psili (-1, 0, 0, -1), psili (-1, 0, 0, 1)
dasia.case: psili.case (-1, 0, 0, -1), psili.case (-1, 0, 0, 1)
finalpedagesh-hb: dagesh-hb (0.8, 0, 0, 0.8), dagesh-hb (0.9, 0, 0, 0.9)
finalpedagesh-hb.BRACKET.18: dagesh-hb (0.8, 0, 0, 0.8), dagesh-hb (0.9, 0, 0, 0.9)
lowernumeral-greek: quoteright.alt (-1, 0, 0, -1)
pedagesh-hb: dagesh-hb (0.8, 0, 0, 0.8), dagesh-hb (0.9, 0, 0, 0.9)
pedagesh-hb.BRACKET.18: dagesh-hb (0.8, 0, 0, 0.8), dagesh-hb (0.9, 0, 0, 0.9)
shindagesh-hb: dagesh-hb (0.8, 0, 0, 0.8), dagesh-hb (0.9, 0, 0, 0.9)
shindageshshindot-hb: dagesh-hb (0.8, 0, 0, 0.8), dagesh-hb (0.9, 0, 0, 0.9)
shindageshsindot-hb: dagesh-hb (0.8, 0, 0, 0.8), dagesh-hb (0.9, 0, 0, 0.9)
```

The *-hb glyphs have been decomposed in https://github.com/googlefonts/googlesans/pull/118 but that can be split into a separate PR.

The glyphs that use dasia and dasia.case like Alphadasiaprosgegrammeni.ad (uni1F89.ad) have components with the wrong transformation in some locations in the variable font.

**Comment by madig** [comment]
What a rabbit hole. But why are those `.final` glyphs gone now :(

**Comment by madig** [comment]
Cosimo says that only component offsets will variate, the other affine transformation stuff will stay as whatever the default master has.

**Comment by moyogo** [comment]
> Cosimo says that only component offsets will variate, the other affine transformation stuff will stay as whatever the default master has.

Yes, that's what I meant. I didn’t include the offsets.

**Comment by anthrotype** [comment]
Cosimo says "I trust whatever Denis says"

**Comment by madig** [comment]
@moyogo the removed `.final` glyphs aren't referenced anywhere except in the `@hb_finalCantillationDst` class definition, which does get used somewhere. Not sure what's going on there...

**Comment by madig** [comment]
@chrissimpkins maybe the merge should be kept off until the problems with Hebrew and Greek components are fixed? Otherwise sifting through the diffs will be cumbersome and error prone.

**Comment by madig** [comment]
Comparing the GlyphOrder between master and this branch's GoogleSansText-MediumItalic.ttf shows only the expected removal of brevecombcy.cap. Huh. So what does diffenator mean. Also, dumping the GDEF table shows no diff.

**Comment by madig** [comment]
The GIFs don't show anything obvious:

gdef_mark_missing
glyphs_missing

**Comment by moyogo** [comment]
Could it be that the glyph names are different? Are they also in the "new glyphs" part of the report?

**Comment by anthrotype** [comment]
different glyph names would show up in a textual diff of the two GlyphOrder ttx dumps, but Nikolaus said they are the same except for the expected removal of brevecombcy.cap

**Comment by madig** [comment]
Output is https://github.com/googlefonts/googlesans/pull/124#issuecomment-763673568, so no new glyphs... @m4rc1e halp

**Comment by madig** [comment]
Looking at the full TTX dump diff, there are indeed some diffs in GSUB, most of them about some chain substitution thing for `zero` to `nine`, but one is about how the old font had a

```
          <InputCoverage index="0" Format="1">
            <Glyph value="uni0592"/>
            <Glyph value="uni05A9"/>
            <Glyph value="uni05AF"/>
          </InputCoverage>
```

and the new one doesn't.

**Comment by chrissimpkins** [comment]
> @chrissimpkins maybe the merge should be kept off until the problems with Hebrew and Greek components are fixed? Otherwise sifting through the diffs will be cumbersome and error prone.

@madig ok with me.  Denis has PR open with the Hebrew work. My understanding is that we are still waiting on some pipeline library reviews + merges to support the changes in our build toolchain before the Hebrew cantillation fixes can be merged.

**Comment by madig** [comment]
Just as a checkpoint and reminder to myself, using ufo2ft git master fixes the delta problems, but diffenator is saying things I don't understand. We need @m4rc1e for this.

**Comment by m4rc1e** [comment]
My plan is to update diffenator this year. I want to keep the interfaces and good parts such as:
- Ability to compare fonts with different upms
- Ability to compare static fonts against VF instances
- Keep ft, hb and cairo to make diff images (may upgrade to skia)
- Update/make a new hb_input so the results are more consistent

Most of the QA tools I originally wrote happened because we'd just broken the internet. We needed something asap. Since we no longer have fires, it's definitely time to upgrade them.

**Comment by m4rc1e** [comment]
@madig, can you provide a zip of the before and after fonts please?

**Comment by m4rc1e** [comment]
Btw, diffenator by default compares glyph surface areas. Use the `-rd` arg to diff glyphs by comparing the ft bitmaps and counting the diff pixels. If I do this for d459cf7 vs. c1498bc I get the following:

glyphs_modified


cc @chrissimpkins

**Comment by madig** [comment]
Yes, I make'd those fonts with ufo2ft git master installed for that sweet component transformation fix.

Try these: [Temp.zip](https://github.com/googlefonts/googlesans/files/5858090/Temp.zip)

**Comment by m4rc1e** [comment]
Ok, I've just had an idea after our call earlier today.

@simoncozens has https://github.com/simoncozens/fontFeatures which can unparse OT Tables. It can also dump a ttf's OT features to an fea file. Here's a quick script to dump two fonts OT features to fea files.



```
import itertools
from fontFeatures.ttLib import unparse
from argparse import ArgumentParser
from fontTools.ttLib import TTFont



parser = ArgumentParser()
parser.add_argument("font_before")
parser.add_argument("font_after")
args = parser.parse_args()
font_before = TTFont(args.font_before)
font_after = TTFont(args.font_after)

font_before_unparsed = unparse(font_before).asFea()
with open("before.txt", "w") as doc_before:
    doc_before.write(font_before_unparsed)


font_after_unparsed = unparse(font_after).asFea()
with open("after.txt", "w") as doc_after:
    doc_after.write(font_after_unparsed)
```

If I diff the output for the fonts you zipped me, we get the following:

```
@markFilteringSet1 = [uni05C1 uni05C2];			      |	@markFilteringSet8 = [uni05C1 uni05C2];
@markAttachmentSet2 = [uni05BC];			      |	@markAttachmentSet9 = [uni05BC];
@markFilteringSet3 = [uni05C1 uni05B0 uni05B1 hatafsegol_silu |	@markFilteringSet10 = [uni05C1 uni05B0 uni05B1 hatafsegol_sil
@markFilteringSet4 = [dotbelowcomb uni0324 uni0326 uni0327 un |	@markFilteringSet11 = [dotbelowcomb uni0324 uni0326 uni0327 u
@markFilteringSet5 = [uni059A uni05AD];			      |	@markFilteringSet12 = [uni059A uni05AD];
@markFilteringSet6 = [uni0308 uni0307 gravecomb acutecomb uni |	@markFilteringSet13 = [uni0308 uni0307 gravecomb acutecomb un
@markFilteringSet7 = [uni030C.alt uni031B uni030C.alt.cap uni |	@markFilteringSet14 = [uni030C.alt uni031B uni030C.alt.cap un
    lookupflag UseMarkFilteringSet @markFilteringSet1;	      |	    lookupflag UseMarkFilteringSet @markFilteringSet8;
    lookupflag MarkAttachmentType @markAttachmentSet2;	      |	    lookupflag MarkAttachmentType @markAttachmentSet9;
    lookupflag UseMarkFilteringSet @markFilteringSet3;	      |	    lookupflag UseMarkFilteringSet @markFilteringSet10;
    lookupflag UseMarkFilteringSet @markFilteringSet4;	      |	    lookupflag UseMarkFilteringSet @markFilteringSet11;
    lookupflag UseMarkFilteringSet @markFilteringSet5;	      |	    lookupflag UseMarkFilteringSet @markFilteringSet12;
    lookupflag UseMarkFilteringSet @markFilteringSet6;	      |	    lookupflag UseMarkFilteringSet @markFilteringSet13;
    lookupflag UseMarkFilteringSet @markFilteringSet7;	      |	    lookupflag UseMarkFilteringSet @markFilteringSet14;
```

Obviously this can be improved greatly, but I think we should be using fontParts for the heavy lifting.

cc @belluzj

**Comment by m4rc1e** [comment]
With fontParts we can also access the shaper inputs e,g

```PYTHON
from fontFeatures.ttLib import unparse
from fontTools.ttLib import TTFont

font = TTFont(args.input)
unparsed = unparse(font) 

for tag, routines in parsed.features.items():
    for routine in routines: 
         for rule in routine.routine.rules:
            print(tag, rule.shaper_inputs())

# "dlig [["f"], ["i]]...
```

You could get all the shaper inputs for the before font and use these as strings for hb-shape. You could then see if all strings are accessible in the after font.

**Comment by madig** [comment]
So we need to do two things: 1. get a better feature diff and 2. fix component transformations. @chrissimpkins anyone working on point 2?

**Comment by simoncozens** [comment]
Is the component translate bug with flatten components the same as this one: https://github.com/originaltype/kufam/issues/16#issuecomment-769026120 ?

**Comment by chrissimpkins** [comment]
@madig This comment still apply here? https://github.com/googlefonts/ufo2ft/pull/448#issuecomment-762304811

**Comment by chrissimpkins** [comment]
Summary of outstanding blockers in this thread:

Blocker: https://github.com/googlefonts/googlesans/pull/124#issuecomment-763680928

Issue:

> Cosimo says that only component offsets will variate, the other affine transformation stuff will stay as whatever the default master has.

This affects the production Hebrew and Greek design work.  Denis is addressing the Hebrew fixes.  

> So we need to do two things: 1. get a better feature diff and 2. fix component transformations. @chrissimpkins anyone working on point 2?

I reached out to Irene Vlachou about the Greek components today.  

Issue remains blocked.

**Comment by madig** [comment]
> @madig This comment still apply here? [googlefonts/ufo2ft#448 (comment)](https://github.com/googlefonts/ufo2ft/pull/448#issuecomment-762304811)

It's stale, I implemented what I had in mind already.

**Comment by chrissimpkins** [comment]
Irene is prepping changes to address the Greek components.

**Comment by chrissimpkins** [comment]
> Irene is prepping changes to address the Greek components.

#141

**Comment by chrissimpkins** [comment]
Status:

Full glyph list that must be addressed in https://github.com/googlefonts/googlesans/pull/124#issuecomment-763680928

Hebrew fix available in https://github.com/googlefonts/googlesans/pull/118

Greek fix under review in #141

**Comment by chrissimpkins** [comment]
It would be helpful to have a list of all composite glyphs that we are modifying so that we can lay eyes on the designs before this is merged.

**Comment by madig** [comment]
Superseded by #254.

**Pull request closed without merging**
