### PR TITLE
Fix kahook-cy tail movement on GRAD axis @ opsz 17 + 18

### LINKED ISSUE #247: U+04C4 Cyrillic small letter ka with hook - grade axis curve change in Italic only
The inferior portion of the glyph has a curve change across the GRAD axis in Italic only.  Observed @ opsz = 17 & opsz=18, across full weight axis.

cyrillic

cc @dberlow 

--- 

### TODO

- [x] fix default form https://github.com/googlefonts/googlesans/pull/282
- [x] fix smcp form (https://github.com/googlefonts/GoogleSans-fb/commit/fb16902f6a51888aac830643059896c76156cd95 was cherry picked in #259)

### PR DESCRIPTION
**Pull request by chrissimpkins**
Fixes #247

--- 

### TODO

- [x] fix opsz 18 https://github.com/googlefonts/googlesans/pull/282/commits/4ea67d4585f1a5c64210b98d880a7678aed122fd
- [x] fix opsz 17

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@dberlow Your latest changes fix the issue in #247 @ opsz 18.  It looks like we need to do the same in the opsz 17 designs.

**Comment by chrissimpkins** [comment]
@dberlow Pulled from your commit https://github.com/googlefonts/GoogleSans-fb/commit/ad0c06f1d83e3e0dc173f216943778a2db5ee7eb

**Comment by dberlow** [comment]
This issue is not shown in current sources.
Screen Shot 2021-06-10 at 8 51 27 AM

**Comment by chrissimpkins** [comment]
Fixed opsz 17 with D Berlow sources in googlefonts/googlesans-fb commit https://github.com/googlefonts/GoogleSans-fb/commit/8db5f0c335af6aa721fc93b4f60d441a57d67a79 @ commit https://github.com/googlefonts/googlesans/pull/282/commits/91549f14e84449996b1a75f5c3ebab63c7260b61

**Comment by chrissimpkins** [comment]
Visually confirmed fix. LGTM.  Ready for merge.

**Pull request merged**
