### PR TITLE
diffenate: add android testing strings

### PR DESCRIPTION
**Pull request by m4rc1e**
This PR will test the Android strings in diffenator2. I got the strings by following: https://github.com/googlefonts/googlesans/tree/add-kerning-strategy-measurement-framework/scripts/measure_kerning_optimizations#extract-aosp-app-strings. This has been requested by @chrissimpkins and @MariannaPaszkowska in a meeting we had earlier today.

Happy to upload my script to transform aosp.json into the supplied text file if people want it.

### CODE REVIEW

**Comment by belluzj** [comment]
@m4rc1e There is the repository: https://github.com/googlefonts/aosp-test-texts

which I think should be the official version of the Android-extracted strings. The last extraction was two years ago though, so maybe you'll want to run the script again on the latest Android sources.

**Comment by m4rc1e** [comment]
Thanks @belluzj. I'll use that as a source instead. Do you mind if I store the strings I need in this repo? they're around 25mb.

**Comment by m4rc1e** [comment]
Ok, strings have been updated using the aosp.json in https://github.com/googlefonts/aosp-test-texts/pull/7

**Comment by m4rc1e** [comment]
@madig @belluzj Do either of you have a problem if I merge? I don't want to step on your toes.

The failing CI is due to fontbakery, not this pr.

**Comment by madig** [comment]
Go ahead :)

**Comment by belluzj** [comment]
I personally don't mind about storing the strings here and you merging, but I would say make sure with @MariannaPaszkowska and @chrissimpkins that they're happy, usually it's them who merge all of our PRs in the end.

**Pull request merged**
