### PR TITLE
Flatten components

### LINKED ISSUE #108: Remove component nesting
We have over 1000 nested components in the GS / GST designs. In the latest fontbakery release, this design approach is flagged as a fail in the new `com.google.fonts/check/glyf_nested_components` universal profile check.

Our CI: https://github.com/googlefonts/googlesans/runs/1453872062?check_suite_focus=true

fontbakery rationale: https://github.com/googlefonts/fontbakery/issues/2961

We'll need to address this new fail. Niko proposed unnesting components at compile time with the approach in https://github.com/googlefonts/fontbakery/issues/2961#issuecomment-733745539.

Let's investigate further and determine how we should address this.

cc @Colophon-Foundry @madig @belluzj 

Requires #246 

---

### TODO

- [x] confirm that there is no regression with required ufo2ft dependency bump (https://github.com/googlefonts/googlesans/issues/246)
- [x] update ufo2ft
- [x] remove nested components
- [x] eyeballs on modified glyphs (glyph lists attached in text files below)

[Regular.txt](https://github.com/googlefonts/googlesans/files/6083938/Regular.txt)
[Italic.txt](https://github.com/googlefonts/googlesans/files/6083941/Italic.txt)

### LINKED ISSUE #116: Reimplement fontbakery QA check for nested components
The nested component validation check was removed from our custom fontbakery check profile in commit https://github.com/googlefonts/googlesans/commit/a097840bee579d3198b1ad79bdefd4682953fa3d as part of the fontbakery profile fixes that were added in https://github.com/googlefonts/googlesans/pull/107.  This is being performed so that we have a functional CI during the transition to the UFO source format (PR #105) and before we address the recursive component issue in our build process.

This check is desired and will need to be added back to the QA testing in this project.  

Associated tracking issues for nested components https://github.com/googlefonts/googlesans/issues/108

### PR DESCRIPTION
**Pull request by madig**
Closes https://github.com/googlefonts/googlesans/issues/108.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@googlebot I consent.

**Comment by chrissimpkins** [comment]
diffenator shows no glyph differences across named instance locations with these changes

**Comment by chrissimpkins** [comment]
File size increase in the ~ 7 - 8 kB range / VF file with this change.

**Comment by madig** [comment]
Let's delete some glyphs to compensate 🔪

**Comment by chrissimpkins** [comment]
> Let's delete some glyphs to compensate 🔪

Which?

**Comment by madig** [comment]
Hm. All of them? Maximum saving.

**Comment by chrissimpkins** [comment]
Eyeballs suggest no significant regressions in Roman across named instances, -50 GRAD, +200 GRAD all glyphs

The tool has a cooldown time.  :) Will get to Italic in a bit.  

We should be able to merge this today.

**Comment by chrissimpkins** [comment]
> Hm. All of them? Maximum saving.

We removed quite a bit for v4.  *.alt, ss04, .BRACKET.18.  Progress

**Comment by chrissimpkins** [comment]
Italic visual review LGTM.

**Pull request merged**
