### PR TITLE
Add Noto OS/2 table Unicode range bit flag checks to custom fontbakery profile

### PR DESCRIPTION
**Pull request by chrissimpkins**
This PR adds a slightly modified version of the [Noto OS/2 table UnicodeRange bit flag check vs. code points in a font](https://github.com/googlefonts/fontbakery/blob/58b65965449a1032fa6b77a7f1807d106717eab2/Lib/fontbakery/profiles/notofonts.py#L88-L119).  The modification makes bits that are set without any code point in range a FAIL instead of a WARN.   

A new script to address this in our build workflow will follow.  We should see a number of new WARN for unset bits with this new check.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
New WARNs:

```
    * WARN: UnicodeRange bit 3 'Latin Extended-B' should be 1 because cmap has 17 of the 208 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 4 'IPA Extensions' should be 1 because cmap has 1 of the 288 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 5 'Spacing Modifier Letters' should be 1 because cmap has 9 of the 112 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 6 'Combining Diacritical Marks' should be 1 because cmap has 21 of the 176 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 24 'Thai' should be 1 because cmap has 1 of the 128 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 29 'Latin Extended Additional' should be 1 because cmap has 97 of the 512 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 30 'Greek Extended' should be 1 because cmap has 233 of the 256 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 31 'General Punctuation' should be 1 because cmap has 41 of the 240 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 32 'Superscripts And Subscripts' should be 1 because cmap has 17 of the 48 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 33 'Currency Symbols' should be 1 because cmap has 13 of the 48 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 35 'Letterlike Symbols' should be 1 because cmap has 11 of the 80 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 36 'Number Forms' should be 1 because cmap has 25 of the 64 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 37 'Arrows' should be 1 because cmap has 9 of the 512 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 38 'Mathematical Operators' should be 1 because cmap has 14 of the 688 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 45 'Geometric Shapes' should be 1 because cmap has 7 of the 96 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 47 'Dingbats' should be 1 because cmap has 24 of the 192 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 60 'Private Use Area (plane 0)' should be 1 because cmap has 8 of the 6400 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 62 'Alphabetic Presentation Forms' should be 1 because cmap has 43 of the 80 codepoints in this range. [code: bad-range-bit]
    * WARN: UnicodeRange bit 69 'Specials' should be 1 because cmap has 1 of the 16 codepoints in this range. [code: bad-range-bit]

```

cc @simoncozens

**Comment by madig** [comment]
AFAIK, these ranges are a bit, uh, vague:

>  The determination of “functional” is left up to the font designer, although character set selection should attempt to be functional by ranges if at all possible.

which can drive up the false positive/negative rate.

**Comment by chrissimpkins** [comment]
Yeah, I agree.  It isn't clear if this is the "correct" approach to consider these "functional" ranges.  But it appears to be the Noto approach.  Are you aware of any downside to setting the bits?  AFAIK the only issues that arise are when they are not set and code points are available.

**Comment by chrissimpkins** [comment]
#291 adds the "fix"

**Pull request merged**
