### PR TITLE
Latin rvrn

### PR DESCRIPTION
**Pull request by madig**
In which I try to right what is rvrn wrong.

Findings:
- There are no opsz=18 for any smallcaps variants except g.sc.BRACKET.18, g.sc.ss04.BRACKET.18 and y.sc.lc.ss04.BRACKET.18.
- Ignoring `.alt` entries in `aalt` because it's probably going away: `(Gcommaaccent|Kcommaaccent|Rcommaaccent|kcommaaccent|rcommaaccent|tcommaaccent).alt`  I deleted their Designspace rules because they are unreachable. The (bracket) glyphs could be deleted as well then. The quotes `(questiongreek|quotedblbase|quotedblleft|quotedblright|quoteleft|quoteright|quotesinglbase)` have `aalt` entries as well but their `.alt` are not put into Designspace rules.
- We need Scedilla.rvrn, scedilla.rvrn, Tcedilla.rvrn, tcedilla.rvrn copies to replace them with the commabelow bracket glyphs for ROM and MOL.
- Italic is missing samekhdagesh-hb.BRACKET.18 and perafe-hb.BRACKET.18.
- There is no semicolon.tf.BRACKET.18
- Should there be a u-cy.BRACKET.18?

### CODE REVIEW

**Comment by madig** [comment]
The `aalt` stuff is funny in InDesign. I can select various alternates and alts may present me with a different set of alternatives. Selecting e.g. `G.logo` actually inserts the ligature text instead of just the glyph! Which messes with selecting other alternates. I am tempted to ignore `aalt` rvrn stuff if its future is in doubt? @chrissimpkins

**Comment by madig** [comment]
@chrissimpkins have a look. I think this solves most Latin `rvrn` things. I am not entirely sure about the Hebrew stuff.

**Comment by chrissimpkins** [comment]
I believe that this can be closed?

**Comment by madig** [comment]
Yes, only this points stands IIRC:

- Italic is missing samekhdagesh-hb.BRACKET.18 and perafe-hb.BRACKET.18.

**Comment by chrissimpkins** [comment]
> Yes, only this points stands IIRC:
> 
> 
> 
> - Italic is missing samekhdagesh-hb.BRACKET.18 and perafe-hb.BRACKET.18.

Ty!

https://github.com/googlefonts/googlesans/issues/233

**Pull request closed without merging**
