### PR TITLE
Hebrew script merge (merge 1, this merge was not used)

### LINKED ISSUE #47: Merge Hebrew script sources
Merge the Hebrew script design work by @fontef and @danielgrumer into the upstream source files.

TODO:

- [x] update bracket layer definitions for opsz axis changes in #60 (see https://github.com/googlefonts/googlesans/pull/56#issuecomment-647749754 for the definitions that need to be updated)
- [x] merge outlines for min opsz upright masters
- [x] merge outlines for min opsz italics masters
- [x] merge outlines for max opsz upright masters
- [x] merge outlines for max opsz italics masters
- [x] merge fea code for upright source
  - [x] languagesystem (hebr dflt + hebr IWR)
  - [x] global class definitions (renamed with hb_* prefix)
  - [x] aalt
  - [x] ccmp (must be first fea implemented)
  - [x] dlig (Yiddish rules)
  - [x] jalt
  - [x] kern
- [x] merge fea code for italics source
  - [x] languagesystem (hebr dflt + hebr IWR)
  - [x] global class definitions (renamed with hb_* prefix)
  - [x] aalt
  - [x] ccmp (must be first fea implemented)
  - [x] dlig (Yiddish rules)
  - [x] jalt
  - [x] kern
- [x] add Hebrew Unicode range setting in Font > Info tab
- [ ] update expected fea tags with new features that are merged with Hebrew glyph set
- [ ] update fontbakery char set QA tests with new Hebrew glyphs
- [ ] designer review of sources (review in progress)
- [ ] designer review of build artifacts (review in progress)

The review identified the following issues:

- [ ] H spacing is slightly off for some glyphs, more detailed review in progress to understand this problem
- [x] we support tab and caps variants of currency symbols, these new outlines and feature code support will be added to the sources

### PR DESCRIPTION
**Pull request by chrissimpkins**
Merges the Hebrew script into the upright and italics source files.

Work is being tracked in #47 

Closes #47

cc @danielgrumer 
cc @Colophon-Foundry 

--- 

### TODO

- [x] address H spacing issues following the Hebrew merge
- [x] add sheqel tabular and caps forms + associated fea code (d/w Daniel, in progress)

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@danielgrumer Your feature code with updated class names (`hb_*` prefix added) is available in this branch (`Hebrew`).  Mind having a look to confirm that you are OK with the feature code in the upright and italics source files as of the https://github.com/googlefonts/googlesans/pull/56/commits/eeedf9b9e5c6f4be228673ea0fef28571bac2480 commit?

There are no outlines merged yet.  I will begin that work tomorrow.

**Comment by danielgrumer** [comment]
@chrissimpkins the code look ok to me 👍

**Comment by chrissimpkins** [comment]
Bracket layers that need to be redefined as part of the #62 opsz axis revisions

#### Upright source file

```
samekh-hb
[16]
finalpe-hb
[16]
finalpedagesh-hb
[16]
pe-hb
[16]
pedagesh-hb
[16]
```

#### Italics source file

```
samekh-hb
[16]
finalpe-hb
[16]
finalpedagesh-hb
[16]
pe-hb
[16]
pedagesh-hb
[16]
```

The following will remain at the values defined in the Latin source files:

```
comma
[16]
quoteright
[16]
```

**Comment by chrissimpkins** [comment]
@danielgrumer Daniel, we are closing in on the final updates for the opsz axis transition in #62.  I edited your Hebrew sources to move the min masters / instances to an opsz value of 17 and moved all bracket layers to 18.  This follows the approach that we are using in the Latin designs.  Any concerns about these changes for the Hebrew script designs?  

I took a look at the Hebrew sources vs. the changes in #62 today using the Merge Glyphs tool.  I hope to get your designs merged prior to our meeting on Wednesday so that we can review the sources during the meeting.

**Comment by danielgrumer** [comment]
> Any concerns about these changes for the Hebrew script designs?

I don't think so. Conceptually, the Hebrew alternations follow the same design principles as the Latin. So every decision that is taken on the Latin side - can be applied to the Hebrew.

**Comment by chrissimpkins** [comment]
Thanks Daniel!

**Comment by chrissimpkins** [comment]
rebased on opsz axis changes as of https://github.com/googlefonts/googlesans/pull/65/commits/7da7cd4717a69bbf298282df1e85afee2f0e2157 @ commit https://github.com/googlefonts/googlesans/pull/56/commits/801652e25411e620510818bbb928ee986ee5b20b

**Comment by chrissimpkins** [comment]
Upright source merge of sheqel and all *-hb outlines + kerning + features are in place as of https://github.com/googlefonts/googlesans/pull/56/commits/377b0e030577fd40bfc337bed76d582339ac13e0

Italics source merge of sheqel and all *-hb outlines + kerning + features are in place as of https://github.com/googlefonts/googlesans/pull/56/commits/3234868c49fd18338679306acafda687d9914cfe

**Comment by chrissimpkins** [comment]
CI test fails at this stage are due to:

- missing expected glyphs from the new Hebrew glyphs that were merged
- missing expected fea tags that were added in the Hebrew merge (jalt, kern)

These edits are being tracked in #47 and will be added before this PR is merged

**Comment by chrissimpkins** [comment]
@danielgrumer Yanek and I discussed the possibility that the new feature class names might not be valid with the changes that made (e.g., too long) and that could be the reason why some of the feature code is not properly functioning.  I reviewed all of the class names and they appear to be valid based on length, char set included in names.  Will continue to investigate.

**Comment by chrissimpkins** [comment]
@danielgrumer Thoughts about removing the Hebrew script registration in the new `kern` feature code that you are adding?

```
script hebr;
	lookupflag 0;
	lookupflag RightToLeft;	

...
```

Yanek felt that at least part of the H spacing issue that you are seeing go away when the locale is properly set in the environment where you are reviewing the files.  This seems to be pointing to a script / locale registration issue given that we are not seeing metrics changes with the merge.

**Comment by chrissimpkins** [comment]
Notable from the [Adobe OT fea spec](https://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#4bii-script-and-language):

> Rules that are specified after the start of a feature and before the first script and/or language statement will be included in all the language systems specified by the languagesystem statements. **If you do not want any of the rules in the feature to be registered under the language systems specified by the languagesystem statements, then a script and/or language statement for a script must be present before the first rule in the feature.**

If I understand this correctly, that means that your `kern` fea code is not registered under anything other than the Hebrew script so the kern metrics are not applied when this script/locale is either not set or not validly set in a rendering environment.

**Comment by chrissimpkins** [comment]
Daniel is working on changes to address the H spacing issues in https://github.com/googlefonts/googlesans/tree/build-Hebrew

**Comment by chrissimpkins** [comment]
We support tabular and caps forms of the currency symbols.  D/W @danielgrumer and Yanek.  Daniel will draw tabular and caps variants of the sheqel currency symbol that is added with these changes + add associated feature code, and push to this branch

**Comment by danielgrumer** [comment]
@chrissimpkins 
I've added the tab +  cap sheqel signs

**Comment by chrissimpkins** [comment]
@Colophon-Foundry 

Edd, there were a few issues that arose with composed glyphs in our Hebrew merged sources and in order to work around the issue we needed to remove the `script latn;` registration on `lookup ccmp_latn_1` in the `ccmp` feature.  There is additional `ccmp` feature code being added with the Hebrew designs that is not working properly with this definition.  Is there any reason that this lookup needs to be registered to the Latin script only?

```
lookup ccmp_latn_1 {
	lookupflag 0;
	sub brevecomb acutecomb by brevecomb_acutecomb;
	sub brevecomb.cap acutecomb.cap by brevecomb_acutecomb.cap;
	sub brevecomb.sc acutecomb.sc by brevecomb_acutecomb.sc;
	sub brevecomb gravecomb by brevecomb_gravecomb;
	sub brevecomb.cap gravecomb.cap by brevecomb_gravecomb.cap;
	sub brevecomb.sc gravecomb.sc by brevecomb_gravecomb.sc;
	sub brevecomb hookabovecomb by brevecomb_hookabovecomb;
	sub brevecomb.cap hookabovecomb.cap by brevecomb_hookabovecomb.cap;
	sub brevecomb.sc hookabovecomb.sc by brevecomb_hookabovecomb.sc;
	sub brevecomb tildecomb by brevecomb_tildecomb;
	sub brevecomb.cap tildecomb.cap by brevecomb_tildecomb.cap;
	sub brevecomb.sc tildecomb.sc by brevecomb_tildecomb.sc;
	sub circumflexcomb acutecomb by circumflexcomb_acutecomb;
	sub circumflexcomb.cap acutecomb.cap by circumflexcomb_acutecomb.cap;
	sub circumflexcomb.sc acutecomb.sc by circumflexcomb_acutecomb.sc;
	sub circumflexcomb gravecomb by circumflexcomb_gravecomb;
	sub circumflexcomb.cap gravecomb.cap by circumflexcomb_gravecomb.cap;
	sub circumflexcomb.sc gravecomb.sc by circumflexcomb_gravecomb.sc;
	sub circumflexcomb hookabovecomb by circumflexcomb_hookabovecomb;
	sub circumflexcomb.cap hookabovecomb.cap by circumflexcomb_hookabovecomb.cap;
	sub circumflexcomb.sc hookabovecomb.sc by circumflexcomb_hookabovecomb.sc;
	sub circumflexcomb tildecomb by circumflexcomb_tildecomb;
	sub circumflexcomb.cap tildecomb.cap by circumflexcomb_tildecomb.cap;
	sub circumflexcomb.sc tildecomb.sc by circumflexcomb_tildecomb.sc;
} ccmp_latn_1;
# 
# script latn;
# lookup ccmp_latn_1;
```

**Comment by Colophon-Foundry** [comment]
I can't see specifically why it would have to be only in the `latn` tag, unless it interferes with other scripts. @gorjious may be able to weigh in more on this issue?

**Comment by chrissimpkins** [comment]
I'm not sure that I understand your response Edd.  You are saying that the removal of the `script latn;` registration on the `lookup ccmp_latn_1` seems ok to you?

**Comment by Colophon-Foundry** [comment]
Sorry @chrissimpkins — Yeah I think so. The addition of it means it restricts it to that script (if I remember correctly?) So removing it should have no adverse effects, other than the code being duplicated into all of the other scripts.

**Comment by gorjious** [comment]
As far as I can tell, it doesn't seem like it should interfere with other scripts. I also have a script tag in the ccmp which I can remove.

**Comment by chrissimpkins** [comment]
Thanks Edd and Gor!

**Comment by chrissimpkins** [comment]
I repeated the merge based on our current master branch commit with all recent bug fixes/opsz axis changes.  This was easier that cherry picking the changes into this branch.  Will close this PR and open a new one for the Hebrew merge work.

**Pull request closed without merging**
