### PR TITLE
Fix tt ligatures

### LINKED ISSUE #624: Fix tt ligature crossbar to be pixel perfect on Android
Per https://github.com/googlefonts/googlesans-flex/issues/901 I propose that in the next release of GS that the tt ligature fix in GSF be backported to GS :)

### PR DESCRIPTION
**Pull request by belluzj**
Hello Marianna, these are changes to the italic only. Eduardo lists below all the changes he had to make. If you approve of the approach he'll do the same to the uprights.

## Changed glyphs

- /i: added #entry anchor
- /j: top was made more similar to /i top + #entry anchor
- /b: added #entry anchor
- /k: added #entry anchor
- /h: added #entry anchor
- /l: added #entry anchor
- /t-bar /t-caron /t-cedilla now using anchors to support auto-align
- /t-bar component now renamed to t-bar_three
- /ij: fixed adv. width

## Ligature parts

- flig1: longs part of f
- flig2: ascender ligature
- flig3: slightly shorter f part to open up Bold display fi, fj, ft, ffi, ffj, fft
- tlig: t stem
- f-bar_one: short left part of f
- f-bar_two: short right part of f
- f-bar_three: long right part of f ligatures
- t-bar_one: short left part of t
- t-bar_two: short right part of t
- t-bar_two: crossbar that is centred in tbar (glyph not the bar)

Fixes #624

### CODE REVIEW

**Comment by schriftgestalt** [comment]
I had a look at the sources. I would make the bar glyphs slightly longer to overlap with the vertical stems to avoid white lines or other artifacts.

**Comment by MariannaPaszkowska** [comment]
This is great; many thanks! Please proceed with the uprights. 
Yes, thanks for your suggestion @schriftgestalt ! indeed, we discussed this with @belluzj and Eduardo. I see some overlap (in the reworked italics), but the masters may need a slightly bigger overlap to ensure proper interpolation in all design spaces.

**Comment by MariannaPaszkowska** [comment]
@belluzj I noticed few changes in uprights. I saw this when running diffenetor2 on this build vs previous merge.  Could you and Eduardo please look into that and fix it or confirm this is intentional? 
Here is a list:
opsz 18, GRAD 0, Regular: 
- [ ] ligatures and "t" changed their spacing. 

opsz 18, GRAD 0, Bold:
- [ ] the distance between the components in "tt" has changed 
- [ ] the length of the terminal in "f" in "fft ffk, ffh" 
- [ ] the bar in "fh fk fb"

opsz 17, GRAD 0, Regular:
- [ ] the length of the terminal in "f" changed in "ffh ff"

opsz 17, GRAD 0, Bold:
- [ ] "t" - spacing changed

opsz18 GRAD 200 Regular
- [ ] stem moved in "t"
- [ ] spacing and distances between components changed in: "ffh tt ffj fft tf fl ffk ff fj fi ffi ffb fh ffl"

opsz18 GRAD 200 Bold:
- [ ] crossbar got longer in "fb fh" 
- [ ] terminals got longer in "ffh fl ffk"
- [ ] spacing or distances between components changed in "tt"

opsz17 GRAD 200 Regular
- [ ] "ť ţ" -  the position of the accent changed slightly

opsz17 GRAD 200 Bold
- [ ] "t" - spacing changed

opsz18, GRAD -50 Regular:
- [ ]  spacing changed: "t" and in ligatures "ffh ffj tf fft tt fl ffk ff ffb fi ffi fj fh"

opsz18, GRAD -50 Bold: 
- [ ]  spacing changed: "tt"
- [ ] terminals got longer in "ffh fl ffk"

 opsz17 GRAD -50 Regular:
- [ ] terminals changed in "ffh fft"
- [ ] "t" - spacing changed

 opsz17 GRAD -50 Bold:

- [ ] spacing changed: "t" and in ligatures "ffh ffj tf fft tt fl ffk ff ffb fi ffi fj fh"

**Comment by belluzj** [comment]
@MariannaPaszkowska I've given your list to Eduardo and he's having a look.

**Comment by belluzj** [comment]
@MariannaPaszkowska Reply from Eduardo:

All the changes are intentional, since we used a modular approach some proportions had to be changed slightly to make the system work, for example the middle bar of /t_t and /f_f is now the same.

I tried to make sure that none of the changes were too big or noticeable, but to make everything match the previous version would have meant adding more components.

It took a while to make the grads work too, so I had to take one point here and there to make sure the grads would still match with the automatic alignment.

Among the changes in particular:
* the length of the terminal in "f" changed in "ffh ff"

    => this is as per our discussion about the f hook changes. We decided that it didn't make sense to make it longer than /f, so I only shortened in 2 masters: Display Bold and opsz18-400-200 to accommodate the i dot in /f_i, /f_t and /f_j glyphs, and kept the same behaviour as /f in the other masters

* "ť ţ" - the position of the accent changed slightly

    => the t was built using components, I had to add anchors and rebuild the accents to ensure they were in the right position, due to the slight changes in spacing in advance width of t, they might be off by a couple of units. Please let us know if you want us to ensure that they have the previous offset.



Please let us know if you are happy with the changes, and if anything should be kept the same as the previous version for technical reasons.

**Comment by MariannaPaszkowska** [comment]
Thanks for the additional explanation, @belluzj !
In this case, we're improving the consistency, so those are good changes. Thanks for confirming that those are intentional.

**Pull request merged**
