### PR TITLE
Support colon.ss03 in calt, Roman builds

### LINKED ISSUE #178: ss03 colon substitution conflict with calt substitution
`ss03`:

```
sub colon by colon.ss03;
```

is trumped by the `calt`:

```
sub [zero one two three four five six seven eight nine] colon' [zero one two three four five six seven eight nine] by colon.time;
```

so we do not get the expected `colon.ss03` when stylistic set 03 is activated

### PR DESCRIPTION
**Pull request by chrissimpkins**
Fixes #178

with calt off, colon -> colon.ss03 is already implemented in ss03 feature

with calt on, this PR adds a new colon.time -> colon.ss03 sub **in Roman only** to address the issue in #178

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@madig does 32312434b45053f272628d9720eb10fbf03b3a09 appear to be related to the changes in #391?  I'm not sure why the CI did not flag the issue in that PR?

**Comment by madig** [comment]
Seems that way (can repro on main) and I don't know why CI didn't pick it up 🤔

**Comment by chrissimpkins** [comment]
Updated expected ss03 shaping output in https://github.com/googlefonts/googlesans/pull/398/commits/4b25ae069bba820d9c980cfed004890e56414e7f.

When ss03 is toggled on, Roman should have ss03 fig and ss03 colon forms.  This style is not supported in Italic. In Italic, the colon.time outline continues to be used when a colon is positioned between adjacent figs.  The shaping output file was updated on local builds at https://github.com/googlefonts/googlesans/pull/398/commits/32312434b45053f272628d9720eb10fbf03b3a09.

**Comment by chrissimpkins** [comment]
Manual trigger of the static font CI run on https://github.com/googlefonts/googlesans/pull/398/commits/4b25ae069bba820d9c980cfed004890e56414e7f: https://github.com/googlefonts/googlesans/actions/runs/1283008742

**Comment by chrissimpkins** [comment]
CI passed.  LGTM.  Ready for merge.

**Pull request merged**
