### PR TITLE
Document the merge process

### PR DESCRIPTION
**Pull request by belluzj**
The goal is to document our proposed merge process, to let vendors know how we're going to handle the files they deliver to be merged.

As the first step I'm uploading our project plan presentation and Nikolaus will expand with some that focuses on the merge process and includes the relevant diagrams from the presentation, in the other PR: #105.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thanks Jany! Please let me know when you are ready to merge this. It looks like it is a draft right now.

**Comment by madig** [comment]
I also wrote some MAINTAINER.md docs over in https://github.com/googlefonts/googlesans/pull/105.

**Comment by belluzj** [comment]
Since Nikolaus is writing documentation as part of his other PR, I'm marking this one as ready for review, and its point is only to add the presentation.

**Comment by chrissimpkins** [comment]
Thanks Jany. I won't remove your PR branches unless I hear otherwise from you.  Will you please periodically scan for leftovers any that aren't required and delete them?

**Comment by belluzj** [comment]
Sure, will do!

**Pull request merged**
