### PR TITLE
Merge and format feature files

### PR DESCRIPTION
**Pull request by madig**
🚀

### CODE REVIEW

**Comment by madig** [comment]
~~Ready to go!~~

Wait, what's going on.

**Comment by madig** [comment]
Argh I think I forgot to update some files after all...

**Comment by madig** [comment]
Scratch that. I made a mistake transferring features over.

**Comment by madig** [comment]
@chrissimpkins I think we're good now.

**Comment by chrissimpkins** [comment]
You ok with the GSUB diff here Niko?

**Comment by chrissimpkins** [comment]
I pushed a `build-merge-features-fea` branch if you want to have a look at the fonts.  https://github.com/googlefonts/googlesans/actions/runs/552695417

**Comment by chrissimpkins** [comment]
Rebased on master to test against the new ss05 and ss06 hb shaping regression tests based on the GSUB diff.  Will merge this.  @madig, please let me know if you have any concerns about the binary diffs. I *think* that we have checks covering everything that was in the diff.

**Comment by madig** [comment]
I'm comparing those fonts to the ones pre-merge (commit 4448a913) and see a bit of shuffling around of the ss03 code and the others because we move lookups around 🤷‍♀️

**Comment by chrissimpkins** [comment]
That's what I saw too.  It looked like it affected ss05 and 06 as well so I added new regression tests last night before the merge.  Looks like we are ok.

**Pull request merged**
