### PR TITLE
Adds smart colon height adjustment

### LINKED ISSUE #63: Smart colon height adjustment OT feature
Request from @davelab6 / internal design team (contact ryankiley@)

> SF has some 'liga' code which uses GSUB classes to only apply between {0-9}{0-9}:{0-9}{0-9} (excuse the pseudo regex ;) and maybe it is worthwhile to do something similar here to automatically raise the colon to look centered for clock times.
>
>Possibly this should also go in the case feature for {A-Z}:{\ } etc

Support is currently available with `colon.time` design via SS02.  This request is to broaden the feature support.

### PR DESCRIPTION
**Pull request by chrissimpkins**
Closes #63

This PR includes changes from Edd Harrington to support contextual figure centered colon positioning when the colon is displayed between numerals (e.g., in time displays `12:32pm`.  This will be supported in the `calt` feature and merged as part of the v3.001 release.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@Colophon-Foundry Do you mind adding the statement `@googlebot I consent` to this PR thread?  It looks like you need to explicitly verify the contribution since I opened the PR on your work.  Thanks.

**Comment by chrissimpkins** [comment]
Will merge once Edd signs this thread.  I reviewed the feature changes and confirmed that the OT feature is functioning properly locally.  Ready for release as part of v3.001

**Comment by Colophon-Foundry** [comment]
@googlebot I consent

**Comment by chrissimpkins** [comment]
Thanks Edd!

**Comment by chrissimpkins** [comment]
Merging

**Pull request merged**
