### PR TITLE
Add KaiSymbol GRAD 1-200 support @ opsz 17 and 18

### LINKED ISSUE #261: Greek capital Kai symbol (U+03CF) does not appear to have grade 1 - 200 support, Roman only

### PR DESCRIPTION
**Pull request by chrissimpkins**
Fixes #261

Test string:

```
Ϗ
```

---

### TODO

- [x] fix opsz 18 https://github.com/googlefonts/googlesans/pull/283/commits/f76d01a7521e9ec8581eb07ed336308a464c3a47
- [x] fix opsz 17

### CODE REVIEW

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/pull/283/commits/f76d01a7521e9ec8581eb07ed336308a464c3a47 fixes the issue described in #261 for opsz 18

@dberlow it looks like we need this in the opsz 17 masters too.  I pulled your changes in https://github.com/googlefonts/GoogleSans-fb/commit/7be3d2c0720107e8c08ff0f7e4a283bf18b4542c

**Comment by dberlow** [comment]
This has been repaired and committed

Screen Shot 2021-06-10 at 8 46 37 AM

**Comment by chrissimpkins** [comment]
in googlefonts/GoogleSans-fb repository

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/GoogleSans-fb/commit/b955a4c5714d571c886b3ae3189f3b122f837f13

**Comment by chrissimpkins** [comment]
Imported Berlow commit https://github.com/googlefonts/GoogleSans-fb/commit/b955a4c5714d571c886b3ae3189f3b122f837f13 @ googlefonts/googlesans commit https://github.com/googlefonts/googlesans/pull/283/commits/3073f02a7c12f7994d570fac9d37f4769c1b5889

**Comment by chrissimpkins** [comment]
Confirmed fix as of https://github.com/googlefonts/googlesans/commit/3073f02a7c12f7994d570fac9d37f4769c1b5889

LGTM. Ready for merge.

**Pull request merged**
