### PR TITLE
Delete Greek ccmp entries

### LINKED ISSUE #195: Remove Greek part of ccmp
https://github.com/googlefonts/googlesans/issues/161#issuecomment-777796745

### PR DESCRIPTION
**Pull request by madig**
Implements https://github.com/googlefonts/googlesans/issues/161#issuecomment-777796745.

This removes the `.case` variants of various Greek marks (without removing them from the source). I am not sure this is as it should be? @moyogo @irenevl

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thoughts about this @irenevl and @moyogo?  OK to merge as part of the v6.000 release scheduled next week?

**Comment by irenevlachou** [comment]
> Thoughts about this @irenevl and @moyogo? OK to merge as part of the v6.000 release scheduled next week?

I think that's ok, we just need them for composing the accented uc, not as standalone glyphs

**Comment by madig** [comment]
Ok, then we can leave them in. We flatten components, so the source glyphs can use the `.case` variants and they get removed by the subsetter because the production glyphs use the transformed outlines directly.

**Comment by chrissimpkins** [comment]
Thanks Irene! Thanks Nikolaus!

**Pull request merged**
