### PR TITLE
Import Bangla

### LINKED ISSUE #445: Add Bangla script support

### LINKED ISSUE #475: Bengali letter sha stroke length, opsz 17 Roman, regular -> bold weight transition (U+09B6 U+09C1)
The new Bengali set includes a U+09B6 + U+09C1 form with an arm length discrepancy.  The length does not change across weights in the optical size 18 masters (Roman and Italic).  The arm length does not change across weights in the opsz 17 italic masters.  The arm length shortens from regular ==> bold in the opsz 17 Roman masters.

bengali

Maybe an intentional design feature at smaller optical sizes? If so, should this happen in the italic too?  Maybe not intentional and needs to be addressed in the opsz 17 regular master?

Test string: `শু`

### LINKED ISSUE #477: Bengali Nga Virama Gha junction alignment in Roman, opsz 17
Misalignment in the junction of the forms as shown in the animation below:

bengali-junction

Test string: `ঙ্ঘ`

### PR DESCRIPTION
**Pull request by madig**
Closes #445
Closes #475 
Closes #477

Some existing glyphs like space and nbspace gain lib keys describing their categories, which helps with GDEF generation.

Todo:

- [x] Check PostScript names
- [x] Internal review
- [x] Finalize regression test files
- [x] update Win Ascent values (only! no hhea or typo metrics changes) for max tall glyph metrics

---

@chrissimpkins TODO's

- [x] review tall/deep glyphs from https://github.com/googlefonts/googlesans/issues/445#issuecomment-1047581417 (`র্টিঁ র্ক্টিঁ র্ট্বিঁ র্ট্রিঁ র্ট্মিঁ র্ট্ট্রিঁ র্ণ্টিঁ র্ণ্ট্রিঁ র্ন্টিঁ র্ন্ট্রিঁ র্প্টিঁ র্ফ্টিঁ র্ল্টিঁ র্ল্ট্রিঁ র্ষ্টিঁ র্ষ্ট্রিঁ র্স্টিঁ র্স্ট্রিঁ`) 
- [x] wait for Kalapi response on https://github.com/googlefonts/googlesans/pull/455#issuecomment-1075544621
- [x] fix #475 
- [x] discuss #476
- [x] fix #477

### CODE REVIEW

**Comment by chrissimpkins** [comment]
It looks like we are adding some tall glyphs here.  That is what FB is failing on in the CI. We'll need to update the Win Ascent values in the fonts.

**Comment by madig** [comment]
Oh yes, I meant to ask about this. Weren't the vertical metrics fixed? This may blow up some regression test images 😬

**Comment by chrissimpkins** [comment]
"fixed" as in the Win metrics (only!) should now be set to the max height and depth of glyphs as they are added to the set.  The line spacing defined in hhea and typo metrics will never change.  FB will flag with a fail when new max tall or deep glyphs are added to the set and the WinAscent and / or WinDescent will need to be updated.  I can address it after I finish with the Ethiopic unless this is blocking what you need to do to wrap up here.

**Comment by madig** [comment]
Alright, good to know. I can do it myself when finalizing regression test files after Kalapi gives us green light.

**Comment by chrissimpkins** [comment]
@kalapi 

- `U+0980 ঀ BENGALI ANJI` is only used in religious texts and therefore excluded from the glyph set here?
- `09FA ৺ BENGALI ISSHAR` needed?  Unicode 14 standard says that it is used before the name of a deceased person. I don't understand how this is used.

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/issues/475

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/issues/476

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/issues/477

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/issues/476 is a blocker.  I need to discuss this with Kalapi and come up with a plan to address it before we consider release of these designs.

**Comment by chrissimpkins** [comment]
Unblocked on the #476 issue.

Will incorporate design fixes to address #475 and #477 before we merge this.  Kalapi is working on the edits.  This will involve a very small set of glif file updates.

**Comment by chrissimpkins** [comment]
Will rebase on main after https://github.com/googlefonts/googlesans/pull/474 is merged.

**Comment by madig** [comment]
Hm, I do have to rerun the GDEF script...

**Comment by chrissimpkins** [comment]
> Hm, I do have to rerun the GDEF script...

#474 was merged.  This branch is ready for rebase.

**Comment by madig** [comment]
Ok, this took me a bit more than 2h...

Compared to the previous state, Italic aaMatra-beng now has no GDEF category. @kalapi is that ok? The upright one already has no base, so I assume it's correct.

**Comment by kalapi** [comment]
@chrissimpkins Attaching the updated package with a fix for #475 and #477 

[2022-04-05_GoogleSansBangla_V1.000_BETA11.zip](https://github.com/googlefonts/googlesans/files/8429554/2022-04-05_GoogleSansBangla_V1.000_BETA11.zip)

**Comment by chrissimpkins** [comment]
> @chrissimpkins Attaching the updated package with a fix for #475 and #477 
> 
> 
> 
> [2022-04-05_GoogleSansBangla_V1.000_BETA11.zip](https://github.com/googlefonts/googlesans/files/8429554/2022-04-05_GoogleSansBangla_V1.000_BETA11.zip)
> 
> 

Thank you very much Kalapi.  What glyph (names) do we need to import?  Will you also respond to Nikolaus' question in the post above?

**Comment by kalapi** [comment]
> Ok, this took me a bit more than 2h...
> 
> Compared to the previous state, Italic aaMatra-beng now has no GDEF category. @kalapi is that ok? The upright one already has no base, so I assume it's correct.

All good!

**Comment by kalapi** [comment]
Hi @chrissimpkins 

Here is an updated package with the glyph-lists updated. The Italic list is empty since nothing needs to be copied over, in the uprights there are 2 glyphs. 

[2022-04-05_GoogleSansBangla_V1.000_BETA12.zip](https://github.com/googlefonts/googlesans/files/8429928/2022-04-05_GoogleSansBangla_V1.000_BETA12.zip)

**Comment by chrissimpkins** [comment]
Thanks Kalapi!

@madig it sounds like this was a painful rebase.  Are you confident that the state of the design sources has not changed since our pre-rebase review with the exception of the issue that you raised in https://github.com/googlefonts/googlesans/pull/455#issuecomment-1087917267?  Or do we need to put eyeballs on the Bangla designs again?

**Comment by chrissimpkins** [comment]
Imported Kalapi's changes to address #475 and #477 in cd0d8cbb76b8e5192c1f46ab41baed797ca268d7

Note: confirmed that there were no changes to previous glif lib key defined GDEF category definitions with these edits.

**Comment by chrissimpkins** [comment]
Visually confirmed fixes for #475 and #477 following https://github.com/googlefonts/googlesans/commit/cd0d8cbb76b8e5192c1f46ab41baed797ca268d7

Will wait for on Nikolaus' response to https://github.com/googlefonts/googlesans/pull/455#issuecomment-1090685697 so that we can decide if a new review is required before merge.  Otherwise, gtg from my standpoint.

**Comment by madig** [comment]
I had a bad time untangling the conflicts in lib.plist but confirmed that the information matches what we had pre-rebase. There was no problem with the glif rebase. I have not checked the feature regressions but could do that tomorrow (I don't remember them having conflicts).

**Comment by madig** [comment]
Weird, I pulled the latest commit and rebuilt, and I'm seeing the following diff between the fonts in https://github.com/googlefonts/googlesans/pull/455#issuecomment-1090676136 and our build (left: Beta 12 fonts, right: our build):

bangla

The regression test suite doesn't pick this up, so... are we right or wrong?

**Comment by madig** [comment]
I compared the entire test text of the Beta 12 QA HTML page against our builds (up/it) and those two glyphs seem to be the only ones being different.

**Comment by chrissimpkins** [comment]
Thank you very much Nikolaus.  I'm sorry that we are taking steps backwards here.  Noted for future cases where we might want to re-org sequential branch work.  We won't do it again with big change lists unless we have a different approach in place to work with these massive type source diffs.

@kalapi Will you please have a look at the builds linked below in your test documents and confirm that there are no other regressions?  Please also comment on the above regression that Nikolaus identified in https://github.com/googlefonts/googlesans/pull/455#issuecomment-1093015112.  How should it be resolved?

https://github.com/googlefonts/googlesans/suites/5961153362/artifacts/204781634

**Comment by kalapi** [comment]
Hi @madig @chrissimpkins,

I've checked and compared both–the sources and the builds (mine as well as the artefacts you've generated) and found a few issues:

1. There are 20 glyphs missing between the Glyphs source and the compiled TTFs. I'm guessing one of the reasons this is happening is because during the build process the tool is identifying one or more of the following unencoded glyphs missing from the feature code and discarding them. Here is a list:

```
# Production names

uni09C8.init
uni09A809CD09B0
uni09B709CD09AC
uni09AA09CD09A409C1
uni09A409CD09B009C2
uni09B909C3
uni09C8.init.short
uni09C8.init.short2
uni099E09CD.half1
uni09CD09A409CD09B0.blwf
uni09CD09A709CD09AC.blwf
uni09CD09AD.blwf1
headlinebeng
headlinebeng.140
headlinebeng.160
headlinebeng.180
headlinebeng.200
headlinebeng.260
headlinebeng.40
headlinebeng.80

# Nice names

aiMatra-beng.init
n_ra-beng
ss_ba-beng
p_ta_uMatra-beng
t_ra_uuMatra-beng
ha_rVocalicMatra-beng
aiMatra-beng.init.short
aiMatra-beng.init.short2
ny-beng.half1
t_ra-beng.blwf
dh_ba-beng.blwf
bha-beng.blwf1
headline-beng
headline-beng.140
headline-beng.160
headline-beng.180
headline-beng.200
headline-beng.260
headline-beng.40
headline-beng.80
```

2. While some of the above glyphs should be dropped from the final build because they're only building blocks for included, outlined glyphs and not used in glyph composition (e.g. `headline-beng.XXX`) other glyphs such as `p_ta_uMatra-beng` (প্তু) which are included in the Glyphs source's feature code have this code missing in the final `bangla.fea`. Similarly the line of code responsible for the second regression (ম্তু) is also missing from `bangla.fea`. I don't know why only these two lines are being dropped. 

Code responsible for `p_ta_uMatra-beng` (প্তু):

- `	sub p_ta-beng @BNG_uMatra by p_ta_uMatra-beng;`  line # 1290 in the `feature.fea` of `GoogleSansBangla-Regular.ufo` or line # 28 in feature `blws` in the Glyphs source

Code responsible for ম্তু:

-`	sub m-beng.half4 ta-beng.blwf1' @BNG_uMatra' by ta_uMatra-beng.blwf;` line # 1351 in the `feature.fea` of `GoogleSansBangla-Regular.ufo` or line # 89 in feature `blws` in the Glyphs source

3. I also notice now that there are a few additional glyphs being dropped from the set because of the code being commented out. I'll fix the feature code for those glyphs and send BETA13 on Monday 

I hope this makes sense. Please let me know if you need further explanation.

**Comment by madig** [comment]
Our build process drops glyphs if they aren't reachable via a codepoint or substitution feature, or used as a component by a glyph that is. Additionally, we flatten components, so intermediate composites get dropped, too. You can approximately test this with `pyftsubset font.ttf --unicodes="*" --no-ignore-missing-glyphs --notdef-outline --layout-features="*" --drop-tables=MVAR --name-IDs="*" --name-languages="*" --glyph-names --no-prune-unicode-ranges --output-file=font-subset.ttf` (will preserve nested composites).

**Comment by chrissimpkins** [comment]
IIUC, it sounds like Kalapi feels that we should be able to fix all of the identified issues with the correction of the shaping definitions in `feature.fea` and `bangla.fea`?  There must have been a few minor issues that arose with the rebase of the feature code? Or we missed these issues on the first pass through the feature merge process?

@kalapi we are prepared to merge and re-test your fea updates when you push them.  Thank you very much for the detailed investigation of the problems here.

**Comment by kalapi** [comment]
Hello @madig and @chrissimpkins 

I'm adding an updated package herewith. The changes are as follows:

- Removes some un-reachable glyphs as reported (regression test performed to check shaping changes; test-passed)
- Modifies OTL code to access some previously unreachable glyphs
- Item # 2 in https://github.com/googlefonts/googlesans/pull/455#issuecomment-1100308948 is unchanged. The code remains the same.

Please let me know if you have any questions.

[2022-04-19_GoogleSansBangla_V1.000_BETA13.zip](https://github.com/googlefonts/googlesans/files/8511982/2022-04-19_GoogleSansBangla_V1.000_BETA13.zip)

**Comment by kalapi** [comment]
Also attaching the old and new feature files for your reference to inspect the diff.

[Bangla_feature_files.zip](https://github.com/googlefonts/googlesans/files/8514322/Bangla_feature_files.zip)

**Comment by madig** [comment]
I have imported the new bangla.fea and glif files. I needed to update the regression tests actually, specifically for this line:

> ক্ন খ্ব গ্ন ঘ্ন ঙ্ব চ্ন জ্ব ঝ্ব ট্ব থ্ব দ্র ঢ্ব ণ্ণ থ্র ধ্ন ন্ন ন্থ ন্ত ন্র প্প ফ্ল ভ্ল হ্ল ম্থ ম্ত ম্ল ল্গ শ্ন স্ন স্থ স্ত স্ল ষ্র ষ্ব হ্ব য্ব

Can you please check that the newly built fonts match your expectations? Get the files from https://github.com/googlefonts/googlesans/actions/runs/2195255189.

**Comment by chrissimpkins** [comment]
@kalapi F/U to our discussion earlier this week.  

It looks like all of the feature rule updates landed in the bangla.fea file (https://github.com/googlefonts/googlesans/pull/455/commits/c5aef45c417de971c7b987d64264483f2cf6ba2b)

**Comment by kalapi** [comment]
This is good to go!

**Comment by chrissimpkins** [comment]
D/W Kalapi today.  This has been re-reviewed in full on his side following the rebase and fix push, and has been cleared for production release.

**Comment by chrissimpkins** [comment]
Final file sizes after the Bangla import:

## Roman

Previous total size: 2328232 B

```
build/GoogleSans/variable/GoogleSans[GRAD,opsz,wght].ttf

             Summary Statistics              
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃                    Statistic ┃   Size (B) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│                        Total │ 2618576.00 │
│ Avg per encoded glyph (2690) │     973.45 │
│   Avg per total glyph (5035) │     520.07 │
└──────────────────────────────┴────────────┘
```

## Italic

Previous total size: 2477588 B

```
build/GoogleSans/variable/GoogleSans-Italic[GRAD,opsz,wght].ttf
              Summary Statistics              
 ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
 ┃                    Statistic ┃   Size (B) ┃
 ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
 │                        Total │ 2793680.00 │
 │ Avg per encoded glyph (2690) │    1038.54 │
 │   Avg per total glyph (5031) │     555.29 │
 └──────────────────────────────┴────────────┘
```

**Comment by chrissimpkins** [comment]
Also of note, our Win Ascent values changed from 1116 to 1320 with the Bangla release (included in GS v8.000).  We continue to set the Use Typo Metrics bit flag and did not adjust typo or hhea line spacing metrics.

**Pull request merged**
