### PR TITLE
merging Cyrillic utraight-cy kerning

### PR DESCRIPTION
**Pull request by alexeiva**
- Fixed ustrait->ustraight-cy in Italic source too 
- Merged in all ustraight-cy kerning to Roman and Italic. Screenshots from GlyphsMerge
Screenshot 2020-09-10 at 13 35 31
Screenshot 2020-09-10 at 13 35 37
Screenshot 2020-09-10 at 13 49 37
Screenshot 2020-09-10 at 13 49 46

Screenshot 2020-09-10 at 13 29 01

### CODE REVIEW

**Comment by alexeiva** [comment]
@googlebot I consent.

**Comment by alexeiva** [comment]
@chrissimpkins MergeGlyphs creates a lot of clutter in the diffs because of the `userdata` field that was useful for development. I suggest removing it from production sources via 

`del font.userData[RMXScaler]` https://docu.glyphsapp.com/#GSFont.userData

Screenshot 2020-09-10 at 14 20 40

**Comment by chrissimpkins** [comment]
Thanks Alexei.  I really appreciate this work.  Unfortunately 0ae3164e78b121b7489fd913145aaf16768590e1 has a massive diff that seems to change much more than the title suggests "renamed ustrait->ustraight-cy in Italic source".  It looks like ~ 3/4 of the entire source file changed.  What did you do in that step?  I don't know that I can accept this as is.  The name changes should be fairly clean.  If this is a MergeGlyphs issue, then perhaps we step back to before that commit and do this by hand in Glyphs?

**Comment by chrissimpkins** [comment]
> @chrissimpkins MergeGlyphs creates a lot of clutter in the diffs because of the `userdata` field that was useful for development. I suggest removing it from production sources via
> 
> `del font.userData[RMXScaler]` https://docu.glyphsapp.com/#GSFont.userData
> 
> Screenshot 2020-09-10 at 14 20 40

Ty!  Opened https://github.com/googlefonts/googlesans/issues/86 to track this.  I'll look into it

**Comment by alexeiva** [comment]
> Thanks Alexei. I really appreciate this work. Unfortunately [0ae3164](https://github.com/googlefonts/googlesans/commit/0ae3164e78b121b7489fd913145aaf16768590e1) has a massive diff that seems to change much more than the title suggests "renamed ustrait->ustraight-cy in Italic source". It looks like ~ 3/4 of the entire source file changed. What did you do in that step? 

I simply opened Glyphs app and renamed the glyphs manually. Seems to be a Glyphs issue. I also had a massive diff issue in https://github.com/googlefonts/googlesans/pull/85/commits/8f1df46e0f697fe3a4c89bd4ef35200318ca1af2 which I resolved by cherry-picking via diffmerge, but didn't notice this one. I will revert this.

**Comment by chrissimpkins** [comment]
> > Thanks Alexei. I really appreciate this work. Unfortunately [0ae3164](https://github.com/googlefonts/googlesans/commit/0ae3164e78b121b7489fd913145aaf16768590e1) has a massive diff that seems to change much more than the title suggests "renamed ustrait->ustraight-cy in Italic source". It looks like ~ 3/4 of the entire source file changed. What did you do in that step?
> 
> I simply opened Glyphs app and renamed the glyphs manually. Seems to be a Glyphs issue. I also had a massive diff issue in [8f1df46](https://github.com/googlefonts/googlesans/commit/8f1df46e0f697fe3a4c89bd4ef35200318ca1af2) which I resolved by cherry-picking via diffmerge, but didn't notice this one. I will revert this.

See our main PR branch thread.  I went through this again and confirmed that you used Glyphs.  I am seeing the same thing.  On review of the updated fontbakery glyph name/order files, it looks like Glyphs is reordering many of the glyphs in the italics sources.  Much of this appears to be our Hebrew additions.  Have a look and let me know if you see anything that is not desirable.  I will test the changes with fontdiffenator to confirm that we are not touching anything else.

**Comment by chrissimpkins** [comment]
Merged into #82

**Pull request closed without merging**
