### PR TITLE
Consolidated Cyrillic update v3.001

### PR DESCRIPTION
**Pull request by alexeiva**
Duplicates https://github.com/Colophon-Foundry/google-sans/pull/240

Consolidates all updates from https://github.com/Colophon-Foundry/google-sans/pull/228:

- Added new glyphs (fixes https://github.com/Colophon-Foundry/google-sans/issues/222 and https://github.com/Colophon-Foundry/google-sans/issues/212):

Roman
```
apostrophemod
tsetse-cy.sc
```
Italic
```
apostrophemod
tsetse-cy.sc
ge-cy.loclSRB
gje-cy.loclMKD
```

Adds final refinements:

- `Ustrait-cy` renamed to `Ustraight-cy` (misspelled name in Glyphs App lists), updated features
- Updated kerning for Cyrillic small caps. (Previously they relied on UC classes)
- in Italics added new glyph `gje-cy.loclMKD` and updated `language MKD` definition:

```
script cyrl;
language SRB;
sub be-cy by be-cy.loclSRB;
sub de-cy by de-cy.loclSRB;
sub pe-cy by pe-cy.loclSRB;
sub te-cy by te-cy.loclSRB;
sub sha-cy by sha-cy.loclSRB;
language MKD;
sub ge-cy by ge-cy.loclMKD;
sub gje-cy by gje-cy.loclMKD;
sub be-cy by be-cy.loclSRB;
sub de-cy by de-cy.loclSRB;
sub pe-cy by pe-cy.loclSRB;
sub te-cy by te-cy.loclSRB;
sub sha-cy by sha-cy.loclSRB;
```

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thanks Alexei!

**Comment by chrissimpkins** [comment]
Alexei, thoughts about this error on your builds (from CI log)?

```
fontmake: Error: In 'GoogleSans/GoogleSans.glyphs' -> '../build/GoogleSans/master_ufo/GoogleSans.designspace': Generating fonts from Designspace failed: /home/runner/work/googlesans/googlesans/build/GoogleSans/master_ufo/GoogleSans-TextRegular.ufo:20:2554: "Ustraight-cy" is not a glyph in the font, and it can not be split into a range of known glyphs
```

**Comment by chrissimpkins** [comment]
OK to work in the `Cyrillic` branch by the way.  That is a development branch intended for your edits Alexei.

**Comment by alexeiva** [comment]
> Alexei, thoughts about this error on your builds (from CI log)?
> 
> ```
> fontmake: Error: In 'GoogleSans/GoogleSans.glyphs' -> '../build/GoogleSans/master_ufo/GoogleSans.designspace': Generating fonts from Designspace failed: /home/runner/work/googlesans/googlesans/build/GoogleSans/master_ufo/GoogleSans-TextRegular.ufo:20:2554: "Ustraight-cy" is not a glyph in the font, and it can not be split into a range of known glyphs
> ```

I updated the Uppercase class and c2sp feature with correct name `Ustraight-cy` (was Ustrait-cy), this fixed the error.

> OK to work in the `Cyrillic` branch by the way. That is a development branch intended for your edits Alexei.

Okay, I moved this PR to https://github.com/googlefonts/googlesans/pull/51 and will delete the cyr-3001-patch branch

**Comment by chrissimpkins** [comment]
> > Alexei, thoughts about this error on your builds (from CI log)?
> > ```
> > fontmake: Error: In 'GoogleSans/GoogleSans.glyphs' -> '../build/GoogleSans/master_ufo/GoogleSans.designspace': Generating fonts from Designspace failed: /home/runner/work/googlesans/googlesans/build/GoogleSans/master_ufo/GoogleSans-TextRegular.ufo:20:2554: "Ustraight-cy" is not a glyph in the font, and it can not be split into a range of known glyphs
> > ```
> 
> I updated the Uppercase class and c2sp feature with correct name `Ustraight-cy` (was Ustrait-cy), this fixed the error.
> 
> > OK to work in the `Cyrillic` branch by the way. That is a development branch intended for your edits Alexei.
> 
> Okay, I moved this PR to #51 and will delete the cyr-3001-patch branch

Tyvm!

**Pull request merged**
