### PR TITLE
Add ldot (U+0140) smcp feature support

### PR DESCRIPTION
**Pull request by chrissimpkins**
Addresses https://github.com/googlefonts/googlesans/issues/159#issuecomment-795846041

Unclear if it completely closes the issue in #159.  Await response to https://github.com/googlefonts/googlesans/issues/159#issuecomment-796142458

---

### TODO

- [x] update `smcp_c2sc.json` shaping regression definition file with the toml file that is pushed here (will merge #275 first) [e47740fedfc6eb37457aa123a1ad5e5ba57029b5]

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@madig OK to merge before the Armenian?  Let me know if this causes you any problems.  Minor fea file edit.

**Comment by chrissimpkins** [comment]
hb shaping regression test definition updated with bug fix output @ e47740fedfc6eb37457aa123a1ad5e5ba57029b5

**Comment by madig** [comment]
Yes, please merge. I already rebased Armenian on top of this.

**Comment by chrissimpkins** [comment]
Changelog updated @ 2dfe77402a4b2e074178894a97212ffe32844c6b

**Pull request merged**
