### PR TITLE
Stop compacting GPOS for interpolatable masters

### PR DESCRIPTION
**Pull request by madig**
Try tackling https://github.com/googlefonts/googlesans/issues/503

### CODE REVIEW

**Comment by madig** [comment]
@chrissimpkins Can you please try releasing something again with this?

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/actions/runs/2398359104

**Comment by chrissimpkins** [comment]
Worked! https://github.com/googlefonts/googlesans/releases/tag/v8.001-rc.2

**Comment by chrissimpkins** [comment]
time

!!!

**Comment by chrissimpkins** [comment]
> time
> 
> !!!

cc @rsheeter This is where we are without redlining memory in the GHA runner.

related https://github.com/googlefonts/googlesans/issues/503

**Comment by madig** [comment]
:smiley: :gun:

**Comment by chrissimpkins** [comment]
Merging this and will prep a new v8.001 release that includes the ttf-interpolatable builds to support downstream Latin glyph set merges.

**Comment by chrissimpkins** [comment]
@madig v8.001 release will be gen'd by this GHA run: https://github.com/googlefonts/googlesans/actions/runs/2409968329

**Pull request merged**
