### PR TITLE
Import Tamil and Gurmukhi fixes to address GDEF miscategorization, dotted circle anchor fix, and different min/max opsz localized punctuation forms

### LINKED ISSUE #458: Dotted circle attachment
We now fail on the new fontbakery check:

```
 >> Check:   com.google.fonts/check/dotted_circle
    Desc:    Ensure dotted circle glyph is present and can attach marks.
    Files:   GoogleSansText-Regular.ttf

     FAIL The following glyphs could not be attached to the dotted circle
          glyph: - uni0A75 - uni0A51 - And uni0A4D [code:
          unattached-dotted-circle-marks]
    Result: FAIL
```

Gurmukhi in this case.

### LINKED ISSUE #466: Potential GDEF miscategorization of some glyphs
Fontbakery complains about the following glyphs:

Non-mark glyphs should not be a GDEF mark (`com.google.fonts/check/gdef_non_mark_chars`):

* U+0A03 GURMUKHI SIGN VISARGA
* U+0BBF TAMIL VOWEL SIGN I
* U+0BC1 TAMIL VOWEL SIGN U
* U+0BC2 TAMIL VOWEL SIGN UU

And, probably redundantly, these spacing glyphs should not be a GDEF mark (`com.google.fonts/check/gdef_spacing_marks`):

* uni0A03 (U+0A03)
* uni0BBF (U+0BBF)
* uni0BBF.alt (unencoded)
* uni0BC1 (U+0BC1)
* uni0BC2 (U+0BC2)

These warnings are annoying because they fill multiple screens. @kalapi can we recategorize these glyphs somehow to satisfy fontbakery? Or are the warnings wrong?

### PR DESCRIPTION
**Pull request by madig**
Closes #466 
Closes #458
Addresses https://github.com/googlefonts/googlesans/issues/388 in Gurmukhi and Tamil scripts

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Why do we have over 4100 files changing?  Was this a more extensive issue than described in #458 & #466?

**Comment by chrissimpkins** [comment]
Kalapi indicated that this should fix #458 too.  Will activate the dotted circle FB check following the deactivation in https://github.com/googlefonts/googlesans/pull/461

**Comment by madig** [comment]
I asked Kalapi to embed all glyph metadata into the glyphs, which leads to thousands of changes. This should prevent glyphsLib misinterpretation bugs though...

**Comment by chrissimpkins** [comment]
Looking into https://github.com/googlefonts/googlesans/tree/build-khmer-fixes rebase on main branch as we work through some issues in #455 revisions included in this branch.  Let me discuss the issues in #455 with Kalapi and then we can decide where to base the work here.

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/tree/build-khmer-fixes branch was rebased on main and merged into main.

**Comment by madig** [comment]
The warnings came back 🥴

**Comment by madig** [comment]
This is why I don't like rebasing. Had to repeat my clear-taml-and-gurm-categories-and-normalize dance.

**Comment by chrissimpkins** [comment]
> This is why I don't like rebasing. Had to repeat my clear-taml-and-gurm-categories-and-normalize dance.

Yeah, it is a PIA.  I apologize.  I thought that this was going to be a straightforward set of issues to address and it turned into a massive set of revisions.

**Comment by madig** [comment]
No worries. I think centralized CSVs are going to save us a ton of diff traffic, some day 🤞

**Comment by chrissimpkins** [comment]
> No worries. I think centralized CSVs are going to save us a ton of diff traffic, some day 🤞

Let's get the green light on your concept and then we can look into implementation in GS and GS Flex.

**Comment by chrissimpkins** [comment]
It appears that Kalapi addressed ~~https://github.com/googlefonts/googlesans/issues/390~~ #388 in the revisions here.  @kalapi is this in Gurmukhi and Tamil only or does it apply to the Devanagari too?

**Comment by chrissimpkins** [comment]
@madig @kalapi Any chance that these glyph name changes will conflict with requirements in other scripts?  Why did we move from a name that includes Gurmukhi context to a name without?

**Comment by chrissimpkins** [comment]
LGTM.  Let's address the questions in https://github.com/googlefonts/googlesans/pull/474#issuecomment-1086226572 and https://github.com/googlefonts/googlesans/pull/474#issuecomment-1086257591 above, then this is ready to be merged.

**Comment by kalapi** [comment]
Hi @chrissimpkins 

I don't think the headline glyph names will cause conflict with other scripts, this should be fine. 

I haven't fixed the Devanagari WRT #390 This will be done along with the other fixes pending on the Devanagari.

**Comment by chrissimpkins** [comment]
> Hi @chrissimpkins 
> 
> 
> 
> I don't think the headline glyph names will cause conflict with other scripts, this should be fine. 
> 
> 
> 
> I haven't fixed the Devanagari WRT #390 This will be done along with the other fixes pending on the Devanagari. 

ty!

**Pull request merged**
