### PR TITLE
Cut down Armn and Geor punctuation down-shifting

### LINKED ISSUE #324: Review Armenian calt punctuation centering feature code
Related: https://github.com/googlefonts/googlesans/pull/310#issuecomment-867914010

We may need to edit the contextual punctuation position change due to the issue identified in https://github.com/googlefonts/googlesans/pull/319#issuecomment-866192552

### LINKED ISSUE #328: Review Georgian calt positioning feature code
Designer intent:

```fea

@punctuation_centered = [periodcentered bullet hyphenbullet hyphen softhyphen endash emdash horizontalbar plus minus multiply equal notequal greater less approxequal asciitilde logicalnot infinity];

@punctuation_all = [asterisk asterisk.num asterism backslash braceleft braceleft.cap braceright braceright.cap bracketleft bracketleft.cap bracketright bracketright.cap bullet bullet.cap colon colon.tf colon.time comma comma.tf doublequestion ellipsis emdash emdash.cap endash endash.cap exclam exclamationquestion exclamdouble exclamdown exclamdown.cap flowerpunctuationmark guillemetleft guillemetleft.cap guillemetright guillemetright.cap guilsinglleft guilsinglleft.cap guilsinglright guilsinglright.cap horizontalbar hyphen hyphen.cap hyphenbullet lowasterisk numbersign numbersign.cap numbersign.tf parenleft parenleft.cap parenright parenright.cap period period.tf periodcentered question questiondown questiondown.cap questionexclamation quotedbl quotedblbase quotedblleft quotedblright quoteleft quoteright quotesinglbase quotesingle semicolon semicolon.tf slash softhyphen twoasterisksvertical underscore paragraph-georgian paragraph-georgian.case colon.loclGEO semicolon.loclGEO];

@spaces_all = [emquad emspace enquad enspace figurespace fourperemspace hairspace punctuationspace sixperemspace space nbspace thinspace threeperemspace zerowidthspace space.tf];

    pos @geor_lowercase @punctuation_centered' <0 -25 0 0>;
    pos @geor_lowercase @spaces_all @punctuation_centered' <0 -25 0 0>;
    pos @geor_lowercase @spaces_all @punctuation_centered @punctuation_centered' <0 -25 0 0>;

    pos @geor_lowercase @punctuation_centered @spaces_all @punctuation_centered' <0 -25 0 0>;
    pos @geor_lowercase @punctuation_centered @punctuation_centered' <0 -25 0 0>;

    pos @punctuation_centered' @geor_lowercase <0 -25 0 0>;
    pos @punctuation_centered' @spaces_all @geor_lowercase <0 -25 0 0>;
    pos @punctuation_centered' @spaces_all @punctuation_centered @geor_lowercase <0 -25 0 0>;


    pos @geor_lowercase @punctuation_all @spaces_all @punctuation_centered' <0 -25 0 0>;
    pos @punctuation_centered' @spaces_all @punctuation_all @geor_lowercase <0 -25 0 0>;

    pos @geor_lowercase @punctuation_all @punctuation_centered' <0 -25 0 0>;
    pos @punctuation_centered' @punctuation_all @geor_lowercase <0 -25 0 0>;

    pos @geor_lowercase @punctuation_all @punctuation_all @punctuation_centered' <0 -25 0 0>;
    pos @geor_lowercase @punctuation_all @punctuation_all @spaces_all @punctuation_centered' <0 -25 0 0>;

    pos @punctuation_centered' @punctuation_all @punctuation_all @geor_lowercase <0 -25 0 0>;
    pos @punctuation_centered' @spaces_all @punctuation_all @punctuation_all @geor_lowercase <0 -25 0 0>;
```

Related thread where the conversation began #310

### PR DESCRIPTION
**Pull request by madig**
Closes #324.
Closes #328.

This limits `calt` for both languages to only consider punctuation next to lowercase letters without going past spaces. For Georgian, `calt` won't switch out (semi)colon for the localized variant, instead relying on `locl`.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
LGTM.

@gorjious @razmadzekoko Nikolaus was able to support the punctuation shifts without side effects for all of your Armenian and Georgian sequence requirements *except* those that include an intervening space character.  Mind having a look at the files in this archive to confirm that this strikes a reasonable balance and you feel that we are good to go to production with these changes?  

https://github.com/googlefonts/googlesans/suites/3182369448/artifacts/73395593

Thanks!

**Comment by chrissimpkins** [comment]
@googlebot I consent.

**Comment by razmadzekoko** [comment]
@chrissimpkins is it the last version of the files?
I just tested it in FontGoggles and what I see is that punctuation shifts does not work.
Even the changing colon and semicolon to localised forms does not working here:
Screenshot 2021-07-08 at 13 03 13

**Comment by madig** [comment]
Have you set the language for the text span? The code relies on `locl`.

**Comment by razmadzekoko** [comment]
yes, the colon change can be worked while choosing KAT
Screenshot 2021-07-08 at 13 39 55
But I thought it should be worked with default too (achieved with calt feature) because localised forms work almost nowhere in terms of Georgian scripts, as far as I know. That's why I had both locl and calt features.
There are examples of adobe Illustrator and InDesign:
Screenshot 2021-07-08 at 13 44 02
Screenshot 2021-07-08 at 13 45 55
 
After the choosing KAT at the language tab, the punctuation shifts still does not work, what I see but maybe I still miss something.

**Comment by madig** [comment]
Hm, alright, then I'll do it in calt, too. The punctuation shifting works in Firefox, though.

**Comment by madig** [comment]
So, this now works with "abo: აბო:" in Firefox and InDesign 2021, without setting the language, within the bounds of what the feature code defines. Armenian is a bit more extreme and swaps out (semi)colon also next to uppercase and smallcaps glyphs.

**Comment by madig** [comment]
@razmadzekoko Here's some fresh VFs: https://github.com/googlefonts/googlesans/suites/3190091163/artifacts/73632450

**Comment by razmadzekoko** [comment]
> @razmadzekoko Here's some fresh VFs: https://github.com/googlefonts/googlesans/suites/3190091163/artifacts/73632450

Now everything works great as I see 👍

**Comment by gorjious** [comment]
Yeah, I think everything seems to be working fine 👍

**Comment by chrissimpkins** [comment]
> Now everything works great as I see 👍

> Yeah, I think everything seems to be working fine 👍

👍 

Great job Nikolaus!

**Review by chrissimpkins — APPROVED** [review]

**Pull request merged**
