### PR TITLE
Update mark weights & add /colon.time.tf

### LINKED ISSUE #177: calt feature substitutions for numeral, colon, numeral sequences (colon.time)
Our `calt` feature code includes the following substitution:

```fea
sub [zero.tf one.tf two.tf three.tf four.tf five.tf six.tf seven.tf eight.tf nine.tf] colon.tf' [zero.tf one.tf two.tf three.tf four.tf five.tf six.tf seven.tf eight.tf nine.tf] by colon.time;
```

The colon.tf has an adv width of 300 and the colon.time has an adv width of 238.  colon.time is a figure aligned colon design intended for hh:mm time displays.

Do we want a new colon glyph that has the same tabular width as the rest of the `*.tf` punctuation and the figure centered vertical alignment of the colon.time glyph?

cc @Colophon-Foundry @dberlow

### LINKED ISSUE #383: Review GRAD -50 / GRAD +200 mark weights
Irene mentioned to me today that she identified some incorrect GRAD -50 / GRAD +200 mark weights while she was working on component updates in the Greek glyph set.  This included:

- dieresistonos
- semi-circle mark forms
- circumflex
- acute

We will need to review the mark designs to identify the full set of glyphs and masters involved.

### PR DESCRIPTION
**Pull request by RickyDaMa**
Will close #177 and #383 

Updated shaping tests as feature code has changed

### CODE REVIEW

**Comment by RickyDaMa** [comment]
Pipeline fail related to https://github.com/fonttools/fontbakery/issues/4479

**Comment by RickyDaMa** [comment]
@MariannaPaszkowska do you have a preference as to where /colon.time.tf comes in the glyph order?

The Fontbakery fail is related to it not being in the glyphset definition files, so I guess we need to nail this down 😃

**Comment by MariannaPaszkowska** [comment]
No preference, it can be added at the end of the .tf group.

**Comment by RickyDaMa** [comment]
Added!

image

**Comment by MariannaPaszkowska** [comment]
@RickyDaMa @Hoolean 
Generally, this is great progress. Many thanks! The colon is working great, and the accents are more readable. and also included in the GRAD masters. 
However, in Italic, in some glyphs, for example: `ῢ` `ῒ` (polytonic Greek), I noticed that we have issues with the accents mispositioned on the GRAD axis. Can we make sure we also fix this?
Screenshot 2024-02-08 at 4 16 25 PM
Screenshot 2024-02-08 at 4 16 32 PM
Screenshot 2024-02-08 at 4 17 03 PM

**Comment by RickyDaMa** [comment]
@MariannaPaszkowska Eduardo has fixed those for you now, let us know what you think!

**Comment by MariannaPaszkowska** [comment]
Many thanks, everyone!

**Pull request merged**
