### PR TITLE
Import Sinhala

### LINKED ISSUE #469: Add Sinhala script support
Sources will be available on the repository: Aug 18

### PR DESCRIPTION
**Pull request by madig**
Closes https://github.com/googlefonts/googlesans/issues/469

### CODE REVIEW

**Comment by Hoolean** [comment]
@chrissimpkins @MariannaPaszkowska

Our [variable CI builds for this branch](https://github.com/googlefonts/googlesans/actions?query=branch%3Aimport-sinhala++) have been consistently failing with [an out-of-memory exit code](https://github.com/googlefonts/googlesans/runs/8160433096?check_suite_focus=true#step:4:162), after taking a lengthy amount of time.

This is particularly odd for a few reasons:
1. Nikolaus and I have have been able to build this branch locally, and have not observed longer build times;
2. Other branches have enjoyed [a build speedup](https://github.com/googlefonts/googlesans/runs/8098484675?check_suite_focus=true); and
3. #522 should mean that resources are plentiful.

Do you have any ideas what may be causing this, especially on the CI side?

My next lead is to try and reproduce locally by explicitly building with `FONTTOOLS_GPOS_COMPACT_MODE`, as Nikolaus and I frequently remove the flag to cut down on local build times when testing.

**Comment by Hoolean** [comment]
(Just checking in case it can be explained quickly by the CI configuration; we will be continuing to try and reproduce :) )

**Comment by chrissimpkins** [comment]
This shouldn't be happening.  I wonder if you need to rebase on the new gha runner configs in main?

**Comment by Hoolean** [comment]
Terrific! Thanks for the pointer @chrissimpkins, that was exactly it; now, the build completes in [a sprightly 13 minutes](https://github.com/googlefonts/googlesans/runs/8303009780). Next, we may revisit the PyPy branch, to complement the beefier CI environment.

More immediately, we will look at updating the QA tests, and merging Kalapi's latest changes.

**Comment by belluzj** [comment]
I rebased this branch on top of import-odia, itself rebased on top of main, so it's a straight line now.

**Comment by Hoolean** [comment]
Hi @MariannaPaszkowska, @chrissimpkins!

After regenerating the shaping tests and rebasing on main, I am happy to tell you that this branch is now ready for review and merge :tada:

I have built the variables and the statics on [a `build-` branch here](https://github.com/googlefonts/googlesans/actions/runs/3098524436). The GDEF warnings we see are the same as those from Odia; other than that, no new FontBakery warnings or errors are shown.

**Comment by belluzj** [comment]
I merged the latest shaping test files from Kalapi, from https://github.com/googlefonts/googlesans/issues/531#issuecomment-1261376414

**Comment by MariannaPaszkowska** [comment]
Thank you, everyone! :tada:

**Pull request merged**
