### PR TITLE
Import Thai

### LINKED ISSUE #352: Import Thai Looped designs
The Google Sans Thai Looped styles will be imported as our default Google Sans Thai style (Loopless designs will be compiled in a separate Google Sans Thai Loopless typeface)

I d/w Anuthin / Cadson-Demak team and this is scheduled for import in Q3 2021, release in v6.000.

### PR DESCRIPTION
**Pull request by madig**
Closes https://github.com/googlefonts/googlesans/pull/361.

- [x] [Confirm feature diffs between upright and italic](https://github.com/googlefonts/googlesans/pull/361#issuecomment-898440883)
- [x] [Confirm regression test strings](https://github.com/googlefonts/googlesans/pull/361#issuecomment-898452668) -- Source text from the test documents instead.
- [x] [Add production names to "additional glyphs"](https://github.com/googlefonts/googlesans/pull/361#issuecomment-898459396)
- [x] Have built fonts checked by us
- [x] Finalize commit IDs in regression test JSON files

---

CS TODO's

- [x] Nikolaus to revert new baht outlines, GRAD support was removed with changes here (https://github.com/googlefonts/googlesans/pull/365#issuecomment-904920911)
- [x] check / fix centering on baht.tf components after we revert to previous defaults (CS)
- [x] add baht.tf and tnum feature support (CS) #370 
- [x] design space visual review (CS)
- [x] check vs. Noto Sans Thai char set (CS)
- [x] review hb regression test output (CS)
- [x] remove `ญ_ น_ ม_ ง_` strings from Pali and Sanskrit locl fea HB shaping regression checks (adbf376a7e23cbe9dafc942192948713208dcbce)
- [x] remove `ญ ฐ ญฐ` text run from Malay and Pattani Malay locl fea HB shaping regression checks (adbf376a7e23cbe9dafc942192948713208dcbce)

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Merged https://github.com/googlefonts/googlesans/pull/367 with a significant refactor of all fea source.  This branch will need to be rebased on main

Edit: Done.

**Comment by chrissimpkins** [comment]
@madig Faster builds during this import? :)

**Comment by chrissimpkins** [comment]
Is there any benefit to defining a lookup for the duplicate subs in the `locl` block?:

```fea
    language PAL;
    sub [yoYing-thai thoThan-thai] by [yoYing-thai.less thoThan-thai.less];
    language SAN;
    sub [yoYing-thai thoThan-thai] by [yoYing-thai.less thoThan-thai.less];
```

Table packed differently/better or does this just get decomposed into the same set of GSUB data in the binary?

**Comment by chrissimpkins** [comment]
@kanorider Kano, it looks like you modified the baht symbol that was in Google Sans.  Will you please have a look at the case form (baht.cap) and confirm that similar edits are not required there?

**Comment by kanorider** [comment]
> @kanorider Kano, it looks like you modified the baht symbol that was in Google Sans. Will you please have a look at the case form (baht.cap) and confirm that similar edits are not required there?

baht glyphs from us are not required. We can use the glyphs from Google Sans.

**Comment by kanorider** [comment]
> Is there any benefit to defining a lookup for the duplicate subs in the `locl` block?:
> 
> ```opentype
>     language PAL;
>     sub [yoYing-thai thoThan-thai] by [yoYing-thai.less thoThan-thai.less];
>     language SAN;
>     sub [yoYing-thai thoThan-thai] by [yoYing-thai.less thoThan-thai.less];
> ```
> 
> Table packed differently/better or does this just get decomposed into the same set of GSUB data in the binary?

As far as I know, It would work when subs use under 'language XXX;'. So, we have to duplicate subs for using for both 'language'

**Comment by chrissimpkins** [comment]
> > @kanorider Kano, it looks like you modified the baht symbol that was in Google Sans. Will you please have a look at the case form (baht.cap) and confirm that similar edits are not required there?
> 
> baht glyphs from us are not required. We can use the glyphs from Google Sans.

I had a look at your designs.  ~~I don't see any immediately apparent differences in the outlines c/w the case forms and these glyphs are already imported.  We will use them as the new defaults.~~ (Edit: see thread below)

I am going to push tabular baht glyphs in an update shortly.  Currency symbols have tab forms in the set.  ~~They will use your baht design as a component.~~

**Comment by chrissimpkins** [comment]
Check that last comment.  It looks like the previous baht form has grade support.  

@madig, will you please revert the new baht outlines to the previous defaults?  The changes remove the -50 / +200 grade support from these outlines.  

(I recognize that this is likely not desirable to have grade in the currency symbol but not in the script, but let's not lose previous grade work that has been performed on the set. We will provide guidance against use of GRAD in non-LGC scripts for now)

**Comment by kanorider** [comment]
> > > @kanorider Kano, it looks like you modified the baht symbol that was in Google Sans. Will you please have a look at the case form (baht.cap) and confirm that similar edits are not required there?
> > 
> > 
> > baht glyphs from us are not required. We can use the glyphs from Google Sans.
> 
> I had a look at your designs. I don't see any immediately apparent differences in the outlines c/w the case forms and these glyphs are already imported. We will use them as the new defaults.
> 
> I am going to push tabular baht glyphs in an update shortly. Currency symbols have tab forms in the set. They will use your baht design as a component.

Just for your information. I did double check on the source file that we working on. I seem that we use the Baht glyphs from Google Sans which might not an up to date. But in term of visual it should work fine.

**Comment by chrissimpkins** [comment]
@madig I added new baht.tf glyphs using baht components in Robofont.  I am seeing a massive glyph order diff in the lib.plist files (that includes the new baht.tf) that isn't normalized with a R/W pass through ufoLib2 or the gs-normalize-designspace.py script.  Is there a way to reduce this diff to the single glyph addition short of creating separate UFO source files and importing the new outlines with ufoLib2 or manually editing the lib.plist files with the new glyph?

Will wait on your response before I push the updates

**Comment by chrissimpkins** [comment]
@kanorider There appears to be minimal kerning added in your changes.  I see kerning pairs defined for figs and the `thai-saraE` group.  Just confirming that this is all that is intended and we did not miss kerning definitions?

**Comment by kanorider** [comment]
Yes

**Comment by chrissimpkins** [comment]
I will assume that this means ‘yes we did not miss kerns and all is well’ :) 

Let me know if that is a misinterpretation.

**Comment by kanorider** [comment]
Yes, We did not miss kern. Sorry for unclear answer.

**Comment by madig** [comment]
> Faster builds during this import? :)

I haven't checked the CI but locally, yes :)

> Is there any benefit to defining a lookup for the duplicate subs in the locl block?:

Hum, I suppose the difference is going to be in the bytes...

>  Is there a way to reduce this diff to the single glyph addition 

What exactly is the diff? @chrissimpkins

**Comment by chrissimpkins** [comment]
> > Is there any benefit to defining a lookup for the duplicate subs in the locl block?:

> Hum, I suppose the difference is going to be in the bytes...

I recognize that the change is minimal in this case.  This was a general question about what the optimal approach is for my knowledge.  It is better to group duplicate feature code under a lookup when you can in some/most/all cases?

**Comment by chrissimpkins** [comment]
> What exactly is the diff? @chrissimpkins

Will post in #369

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/pull/370 adds a tabular baht with a baht component.  Needs additional centering via component transforms when the baht outlines are reverted to previous defaults that include GRAD support.  Added to OP todo list and I'll take this on as soon as the outlines are reverted.

**Comment by chrissimpkins** [comment]
@madig does https://github.com/googlefonts/googlesans/issues/366 apply to the new rlig ligs here?  Anything that we should address at this stage while the design team is involved?

**Comment by chrissimpkins** [comment]
@googlebot I consent.

**Comment by chrissimpkins** [comment]
Removed unnecessary HB shaping test locl text runs in adbf376a7e23cbe9dafc942192948713208dcbce

Completed the review.  Things look great here.  

Ready to merge after the baht default is reverted, followed by #370 wrap up with centering based on the baht outlines that have GRAD support.

**Comment by madig** [comment]
Baht revert done!

**Comment by chrissimpkins** [comment]
> Baht revert done!

Ty!  Will merge #370 into this branch, update new tabular baht as necessary, and merge.

**Comment by chrissimpkins** [comment]
Tabular baht added to this branch as of https://github.com/googlefonts/googlesans/commit/13a1f72802417ebe644d003aa457645622a00e5c

**Comment by chrissimpkins** [comment]
Thai addition file size assessment:

### Before Thai expansion

#### Roman

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┓
┃                    Statistic ┃  Size (B) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━┩
│                        Total │ 986644.00 │
│ Avg per encoded glyph (1719) │    573.96 │
│   Avg per total glyph (3242) │    304.33 │
└──────────────────────────────┴───────────┘
```

#### Italic

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃                    Statistic ┃   Size (B) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│                        Total │ 1035092.00 │
│ Avg per encoded glyph (1719) │     602.15 │
│   Avg per total glyph (3238) │     319.67 │
└──────────────────────────────┴────────────┘
```


### After Thai expansion

#### Roman

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃                    Statistic ┃   Size (B) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│                        Total │ 1043316.00 │
│ Avg per encoded glyph (1805) │     578.01 │
│   Avg per total glyph (3374) │     309.22 │
└──────────────────────────────┴────────────┘
```

#### Italic

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃                    Statistic ┃   Size (B) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│                        Total │ 1098168.00 │
│ Avg per encoded glyph (1805) │     608.40 │
│   Avg per total glyph (3370) │     325.87 │
└──────────────────────────────┴────────────┘
```

**Pull request merged**
