### PR TITLE
Add various glyphs

### PR DESCRIPTION
**Pull request by madig**
Delivers a new Eng(.alt), eng(.alt)(.sc) and acaron(.alt).

### CODE REVIEW

**Comment by madig** [comment]
@chrissimpkins you can see here why I made https://github.com/f-actions/font-bakery/pull/210

**Comment by MariannaPaszkowska** [comment]
@madig fonts are not building, could you please look into that?

**Comment by madig** [comment]
They aren't building because we need https://github.com/f-actions/font-bakery/pull/210 to make fontbakery test actually run.

**Comment by chrissimpkins** [comment]
> They aren't building because we need [f-actions/font-bakery#210](https://github.com/f-actions/font-bakery/pull/210) to make fontbakery test actually run.

See https://github.com/f-actions/font-bakery/pull/210#issuecomment-1727743891 

I requested @felipesanches feedback on that PR to understand if/how we happen to break anyone who has fb pinned at a version earlier than 0.9 using the custom GH Action.  If no one breaks, all is well and we'll merge to main so that you can switch back to a main branch based approach.  If they do, then let's add some logic so that they can maintain a functional state with the Action.

**Comment by MariannaPaszkowska** [comment]
@belluzj @madig I thought we would be keeping the previous Eng form and making it accessible via contextual features to be used in Sámi languages. Where is this localisation available, via which feature?

Languages that use this alternate Eng form and their tags:
```
Northern Sami	'NSM '	sme
Inari Sami	'ISM '	smn
Skolt Sami	'SKS '	sms
Lule Sami	'LSM '	smj
```

**Comment by MariannaPaszkowska** [comment]
That's how the localised feature for it could look like. We need to keep the original Eng character in (maybe name it Eng.locl? ) the font, and I cannot locate it in the font. 
```
feature locl {
    script latn;
    language NSM;
    sub Eng by Eng.locl;
    language ISM;
    sub Eng by Eng.locl;
    language SKS;
    sub Eng by Eng.locl;
    language LSM;
    sub Eng by Eng.locl;
} locl;
```

**Comment by chrissimpkins** [comment]
> @belluzj @madig I thought we would be keeping the previous Eng form and making it accessible via contextual features to be used in Sámi languages. Where is this localisation available, via which feature?
> 
> Languages that use this alternate Eng form and their tags:
> 
> ```
> Northern Sami	'NSM '	sme
> Inari Sami	'ISM '	smn
> Skolt Sami	'SKS '	sms
> Lule Sami	'LSM '	smj
> ```

Yes, this was only an expansion of the glyph set and broadened localization to additional Latin-based African languages.  There was no intent to replace the previous form if that is what happened.

**Comment by belluzj** [comment]
I'm sorry for the confusion, I will forward your concerns to Nikolaus and the designers, and we'll come back to you shortly.

**Comment by chrissimpkins** [comment]
It was a feature code coverage issue and the subsetter became overzealous. Fix in progress.

**Comment by NeilSureshPatel** [comment]
> @belluzj @madig I thought we would be keeping the previous Eng form and making it accessible via contextual features to be used in Sámi languages. Where is this localisation available, via which feature?
> 
> Languages that use this alternate Eng form and their tags:
> 
> ```
> Northern Sami	'NSM '	sme
> Inari Sami	'ISM '	smn
> Skolt Sami	'SKS '	sms
> Lule Sami	'LSM '	smj
> ```

There are two others:

>```
>Southern Sámi    'SSM'   sma
>Kildin Sámi     'KSM'    sjd
>```

**Comment by MariannaPaszkowska** [comment]
From an email thread with @NeilSureshPatel "We haven't found any languages in Africa that utilize the second form of the uppercase Eng. I have also scoured ScriptSource to see if there were any notes about African languages that use the second form, and I did not find any.  As a result, we have found it easier to make the 1st form the default and then use locl features for the European languages you have listed for the second form. "

**Comment by NeilSureshPatel** [comment]
> > @belluzj @madig I thought we would be keeping the previous Eng form and making it accessible via contextual features to be used in Sámi languages. Where is this localisation available, via which feature?
> > Languages that use this alternate Eng form and their tags:
> > ```
> > Northern Sami	'NSM '	sme
> > Inari Sami	'ISM '	smn
> > Skolt Sami	'SKS '	sms
> > Lule Sami	'LSM '	smj
> > ```
> 
> There are two others:
> 
> > ```
> > Southern Sámi    'SSM'   sma
> > Kildin Sámi     'KSM'    sjd
> > ```

Nevermind. @MariannaPaszkowska has already confirmed these two languages don't use the Eng.

**Comment by madig** [comment]
Added some tests to make sure that various Sami languages get the special treatment. There's no BCP47 tag for Kildin Sami though.

**Pull request merged**
