### PR TITLE
Cyrillic merge fix

### PR DESCRIPTION
**Pull request by alexeiva**
Fixes #82

### CODE REVIEW

**Comment by alexeiva** [comment]
@chrissimpkins you will see some artefacts in the diffs related to MergeGlyphs:
Screenshot 2020-09-07 at 16 23 13
(Glyphs imported custom UFO data from Robofont sources )

```
ERROR:cu2qu.ufo:Glyphs named 'ii-cy' have different number of segments
ERROR:cu2qu.ufo:Glyphs named 'dje-cy.sc' have different number of segments
fontmake: Error: In 'GoogleSans/GoogleSans-Italic.glyphs' -> '../build/GoogleSans/master_ufo/GoogleSans-Italic.designspace': 
Generating fonts from Designspace failed: calc_intersect() takes exactly 4 positional arguments (2 given)
```

I've checked these glyphs, but don't see anything wrong.

**Comment by chrissimpkins** [comment]
I will revert all merged glyphs.  Will you please let me know what glyph outlines have high priority changes for the next release? I will do those by hand and we will address the rest of the touch ups at a future date.

**Comment by alexeiva** [comment]
```
/U-cy/ia-cy/ghemiddlehook-cy/Ii-cy/shcha-cy.sc/dzhe-cy.sc/enghe-cy.sc/u-cy.sc/Kahook-cy/kahook-cy.sc/kahook-cy/Hastroke-cy/hastroke-cy/hastroke-cy.sc/be-cy/Dje-cy/dje-cy.sc/dje-cy/Tshe-cy/tshe-cy.sc/Ghemiddlehook-cy/ghemiddlehook-cy.sc/lje-cy.sc/tetse-cy.sc/eldescender-cy.sc/ii-cy/dzeabkhasian-cy

```


> ```
> ERROR:cu2qu.ufo:Glyphs named 'ii-cy' have different number of segments
> ERROR:cu2qu.ufo:Glyphs named 'dje-cy.sc' have different number of segments
> fontmake: Error: In 'GoogleSans/GoogleSans-Italic.glyphs' -> '../build/GoogleSans/master_ufo/GoogleSans-Italic.designspace': 
> Generating fonts from Designspace failed: calc_intersect() takes exactly 4 positional arguments (2 given)
> ```
> 
> 
> I've checked these glyphs, but don't see anything wrong.

These sources generate fine on my local machine with fontmake

**Comment by chrissimpkins** [comment]
Thanks for doing this Alexei. I will merge all of these updates and will not plan to revert the previous outline merge commits

**Pull request merged**
