### PR TITLE
Scrub groups

### LINKED ISSUE #294: Remove unused kerning groups
```python
from pathlib import Path
from ufoLib2 import Font

for p in Path("source/GoogleSans").glob("*.ufo"):
    print(p)
    u = Font.open(p)
    used = set()
    for f,s in u.kerning:
        used.add(f)
        used.add(s)
    for n in list(u.groups):
        if n not in used:
            del u.groups[n]
    u.save()
```

Maybe even make this part of the merge script 🤔

### PR DESCRIPTION
**Pull request by madig**
Closes https://github.com/googlefonts/googlesans/issues/294.

---

@chrissimpkins edits:

This PR adds new kerning group cleanup source to the normalize.py script used during source import, **and** cleans the groups in the list below

---

Pruned groups:

- public.kern1.DEV_aaMatra-deva_L
- public.kern1.DEV_avagraha-deva_L
- public.kern1.DEV_b-deva.alt2_L
- public.kern1.DEV_bb-deva.alt2_L
- public.kern1.DEV_bb-deva_L
- public.kern1.DEV_bh-deva_L
- public.kern1.DEV_c-deva.alt2_L
- public.kern1.DEV_cha-deva_L
- public.kern1.DEV_da-deva_L
- public.kern1.DEV_danda-deva_L
- public.kern1.DEV_dbldanda-deva_L
- public.kern1.DEV_ddda-deva_L
- public.kern1.DEV_ddha-deva_L
- public.kern1.DEV_dh-deva.alt2_L
- public.kern1.DEV_e-deva_L
- public.kern1.DEV_eight-deva_L
- public.kern1.DEV_five-deva_L
- public.kern1.DEV_four-deva_R
- public.kern1.DEV_g-deva_L
- public.kern1.DEV_gg-deva_L
- public.kern1.DEV_glottalstop-deva_L
- public.kern1.DEV_ha-deva_L
- public.kern1.DEV_i-deva_L
- public.kern1.DEV_iMatra-deva_L
- public.kern1.DEV_j-deva.alt2_L
- public.kern1.DEV_j-deva.alt3_L
- public.kern1.DEV_j-deva.alt4_L
- public.kern1.DEV_j-deva.alt6_L
- public.kern1.DEV_j-deva.alt8_L
- public.kern1.DEV_j-deva_L
- public.kern1.DEV_j_ny-deva.alt2_L
- public.kern1.DEV_j_ny-deva.alt3_L
- public.kern1.DEV_j_ny-deva.alt4_L
- public.kern1.DEV_j_ny-deva.alt5_L
- public.kern1.DEV_j_ny-deva.alt6_L
- public.kern1.DEV_j_ny-deva.alt7_L
- public.kern1.DEV_j_ny-deva.alt8_L
- public.kern1.DEV_j_ny-deva_L
- public.kern1.DEV_jh-deva.alt3_L
- public.kern1.DEV_jh-deva.loclNEP.alt2_L
- public.kern1.DEV_jh-deva.loclNEP_L
- public.kern1.DEV_jha-deva.loclNEP_L
- public.kern1.DEV_jj-deva.alt2_L
- public.kern1.DEV_jj-deva_L
- public.kern1.DEV_k-deva.alt10_L
- public.kern1.DEV_k-deva.alt11_L
- public.kern1.DEV_k-deva.alt2_L
- public.kern1.DEV_k-deva.alt3_L
- public.kern1.DEV_k-deva.alt4_L
- public.kern1.DEV_k-deva.alt5_L
- public.kern1.DEV_k-deva.alt6_L
- public.kern1.DEV_k-deva.alt7_L
- public.kern1.DEV_k-deva.alt8_L
- public.kern1.DEV_k-deva_L
- public.kern1.DEV_k_ss-deva.alt2_L
- public.kern1.DEV_k_ss-deva.alt3_L
- public.kern1.DEV_k_ss-deva.alt4_L
- public.kern1.DEV_k_ss-deva.alt5_L
- public.kern1.DEV_k_ss-deva.alt6_L
- public.kern1.DEV_k_ss-deva.alt7_L
- public.kern1.DEV_k_ss-deva_L
- public.kern1.DEV_kh-deva.alt2_L
- public.kern1.DEV_l-deva.alt3_L
- public.kern1.DEV_l-deva.alt4_L
- public.kern1.DEV_l-deva.alt5_L
- public.kern1.DEV_l-deva.alt6_L
- public.kern1.DEV_l-deva.alt7_L
- public.kern1.DEV_lVocalic-deva_L
- public.kern1.DEV_la-deva.loclMAR_L
- public.kern1.DEV_ll-deva_L
- public.kern1.DEV_llVocalic-deva_L
- public.kern1.DEV_lla-deva_L
- public.kern1.DEV_lll-deva_L
- public.kern1.DEV_m-deva.alt3_L
- public.kern1.DEV_m-deva_L
- public.kern1.DEV_marwaridda-deva_L
- public.kern1.DEV_n-deva.alt4_L
- public.kern1.DEV_nga-deva_L
- public.kern1.DEV_nine-deva_L
- public.kern1.DEV_nn-deva_L
- public.kern1.DEV_ny-deva.alt2_L
- public.kern1.DEV_ny-deva_L
- public.kern1.DEV_one-deva_L
- public.kern1.DEV_p-deva.alt2_L
- public.kern1.DEV_ph-deva.alt10_L
- public.kern1.DEV_ph-deva.alt11_L
- public.kern1.DEV_ph-deva.alt2_L
- public.kern1.DEV_ph-deva.alt3_L
- public.kern1.DEV_ph-deva.alt4_L
- public.kern1.DEV_ph-deva.alt7_L
- public.kern1.DEV_ph-deva.alt8_L
- public.kern1.DEV_ph-deva_L
- public.kern1.DEV_rVocalic-deva_L
- public.kern1.DEV_ra-deva_L
- public.kern1.DEV_rrVocalic-deva_L
- public.kern1.DEV_s-deva.alt2_L
- public.kern1.DEV_seven-deva_L
- public.kern1.DEV_sh-deva.loclMAR_L
- public.kern1.DEV_sh-deva_L
- public.kern1.DEV_sh_r-deva_L
- public.kern1.DEV_six-deva_L
- public.kern1.DEV_ss-deva_L
- public.kern1.DEV_t-deva.alt4_L
- public.kern1.DEV_th-deva.alt2_L
- public.kern1.DEV_th-deva.alt3_L
- public.kern1.DEV_three-deva_L
- public.kern1.DEV_tta-deva_L
- public.kern1.DEV_ttha-deva_L
- public.kern1.DEV_two-deva_L
- public.kern1.DEV_u-deva_L
- public.kern1.DEV_uu-deva_L
- public.kern1.DEV_v-deva.alt2_L
- public.kern1.DEV_y-deva.alt2_L
- public.kern1.DEV_y-deva.alt4_L
- public.kern1.DEV_yaheavy-deva.half_L
- public.kern1.DEV_zero-deva_L
- public.kern1.GRK_Omicrontonos
- public.kern1.alef-hb
- public.kern1.armn_period.case
- public.kern1.armn_punc_comma
- public.kern1.armn_punc_emphasis
- public.kern1.armn_punc_exclam
- public.kern1.armn_punc_question
- public.kern1.armn_punc_ringhalfleft
- public.kern1.cyr_H
- public.kern1.cyr_shha.sc
- public.kern1.finalpe-hb
- public.kern1.h.sc.lc.ss04
- public.kern1.he-hb
- public.kern1.l.sc.lc.ss04
- public.kern1.minute
- public.kern1.o.sc.lc.ss04
- public.kern1.ohorn
- public.kern1.pe-hb
- public.kern1.resh-hb
- public.kern1.samekh-hb
- public.kern1.seven.sc
- public.kern1.tse-cy.sc
- public.kern1.u.sc
- public.kern1.vav-hb
- public.kern1.zero.sc
- public.kern2.DEV_a-deva_R
- public.kern2.DEV_avagraha-deva_R
- public.kern2.DEV_bha-deva_R
- public.kern2.DEV_c-deva_R
- public.kern2.DEV_danda-deva_R
- public.kern2.DEV_dbldanda-deva_R
- public.kern2.DEV_e-deva_R
- public.kern2.DEV_eight-deva_R
- public.kern2.DEV_five-deva_R
- public.kern2.DEV_four-deva_R
- public.kern2.DEV_gh-deva.alt2-deva_R
- public.kern2.DEV_glottalstop-deva_R
- public.kern2.DEV_iiMatra-deva_R
- public.kern2.DEV_j-deva_R
- public.kern2.DEV_j_nya-deva_R
- public.kern2.DEV_k_ssa-deva_R
- public.kern2.DEV_nga-deva_R
- public.kern2.DEV_nine-deva_R
- public.kern2.DEV_one-deva_R
- public.kern2.DEV_prishthaMatraE-deva_R
- public.kern2.DEV_rVocalic-deva_R
- public.kern2.DEV_seven-deva_R
- public.kern2.DEV_sha-deva.loclMAR_R
- public.kern2.DEV_six-deva_R
- public.kern2.DEV_t_ra-deva_R
- public.kern2.DEV_t_ta-deva_R
- public.kern2.DEV_three-deva_R
- public.kern2.DEV_tta-deva_R
- public.kern2.DEV_two-deva_R
- public.kern2.DEV_u-deva_R
- public.kern2.DEV_uu-deva_R
- public.kern2.DEV_zero-deva_R
- public.kern2.GRK_Epsilon
- public.kern2.GRK_Epsilontonos
- public.kern2.GRK_Omicrontonos
- public.kern2.GRK_beta
- public.kern2.GRK_omicorn
- public.kern2.armn_punc_emphasis
- public.kern2.armn_punc_exclam
- public.kern2.armn_punc_question
- public.kern2.armn_punc_ringhalfleft
- public.kern2.cyr_h.sc
- public.kern2.enlefthook-cy.sc
- public.kern2.eth.sc
- public.kern2.minute
- public.kern2.o.sc.lc.ss04
- public.kern2.seven.sc
- public.kern2.vav-hb
- public.kern2.zero.sc

### CODE REVIEW

**Comment by madig** [comment]
Maybe merge this after Gurmukhi or Georgian to avoid annoying conflicts.

**Comment by chrissimpkins** [comment]
> Maybe merge this after Gurmukhi or Georgian to avoid annoying conflicts.

Copy that

**Comment by chrissimpkins** [comment]
Let's merge this following the merge of #310

**Comment by madig** [comment]
Confirming that this produces no binary diff.

**Comment by chrissimpkins** [comment]
Rebased on new Georgian source merge, build dependency updates, and GPOS optimization updates in main @ commit 3faa9ec250da7898ccbf07bf45bc2d5cb4c9c1df

**Pull request merged**
