### PR TITLE
Import Tamil

### PR DESCRIPTION
**Pull request by belluzj**
* [x] Merge and review QA on Dalton Maag side
* [x] @kalapi to check he's happy with the results
* [x] Add the regression test strings provided by Kalapi

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@kalapi it looks like the space glyph included in your Tamil sources changed our HB shaping output metrics.  Do you need a localized space in this set?  If so, do we need to move it to a loclTAML form and support it in `locl`?

**Comment by kalapi** [comment]
@chrissimpkins No, it's possibly the `space` glyph in the Bold that's interpolated from the Black. This can be removed because we tested the Tamil with the Latin Bold space.

**Comment by belluzj** [comment]
Our designer also spotted something that is due to how the pipeline deals with combining marks compared to Glyphs.app: the width of the glyph gets collapsed to 0 but the outline is not shifted in the same direction. That leads to a difference in how the mark appears on top of the dotter circle.

Our designer proposes to fix the problem by adding an anchor to have the same position in the merged font as in Kalapi.

@kalapi are you OK with Rob adding the necessary anchor? He says he can do it easily.

image
image

**Comment by kalapi** [comment]
@belluzj Do you mean adding the `topright` anchor on the `dottedCircle` glyph?

**Comment by belluzj** [comment]
yes exactly

**Comment by kalapi** [comment]
Yes, sounds good!

**Comment by belluzj** [comment]
@chrissimpkins @kalapi We're done with the merge and QA and this is ready for you to have a look at. Once it's all good we can add the test strings provided by Kalapi along with their results

**Comment by chrissimpkins** [comment]
Thanks Jany!  Will you please go ahead with the shaping text run additions?  I use the output in my review.  No rush.  I likely won't get to this before the end of next week

**Comment by madig** [comment]
Looking into this again. I found that there are no production names for some ligatures like `la_iMatra-tamil`. I'll run the list through Glyphs.app.

Edit: interesting. The glyph `k_ssa-tamil` has the production name `uni006B0BB7`, the first part of which is a `k` instead of `TAMIL LETTER KA` :)

**Comment by madig** [comment]
@googlebot I consent.

**Comment by chrissimpkins** [comment]
@kalapi These builds are ready for your review

https://github.com/googlefonts/googlesans/suites/3702689170/artifacts/90374395

**Comment by kalapi** [comment]
@belluzj @madig @chrissimpkins 

I've reviewed the artifacts and we're all good to go!

**Comment by chrissimpkins** [comment]
@belluzj @madig can we better document how to approach ligature glyph naming for design teams?  Anything to take away from the changes that we needed to make in the import work?

**Comment by madig** [comment]
The glyph naming should be done automatically by glyphsLib, but it does not match what Glyphs.app does completely, so you have to check manually. It's an eternal struggle.

**Comment by chrissimpkins** [comment]
>  It's an eternal struggle

The community needs a better approach...

**Comment by madig** [comment]
Maybe it's enough to have Glyphs.app embed the production names in the file. There could be a script.

**Comment by chrissimpkins** [comment]
Did we end up removing the new brace layers?

**Comment by chrissimpkins** [comment]
@kalapi Confirming that you pulled https://github.com/googlefonts/googlesans/commit/a11d045ddfff38dabfe72324d529a1d274abb08f into your upstream sources?

**Comment by chrissimpkins** [comment]
> @kalapi Confirming that you pulled [a11d045](https://github.com/googlefonts/googlesans/commit/a11d045ddfff38dabfe72324d529a1d274abb08f) into your upstream sources?

@kalapi and https://github.com/googlefonts/googlesans/commit/b434417bf6d03dc6b8334dd0c41d3fdc65365d29?

**Comment by chrissimpkins** [comment]
@kalapi Rationale for abandoning the default max opsz (18) quote and comma forms (defaults shown in image below)?  It looks like you are using the opsz 17 designs everywhere in the tml2 locale




*Edit: It looks like you are doing the same thing in Devanagari and Gurmukhi.  I didn't catch it on those imports. :)*

**Comment by chrissimpkins** [comment]
Comment 2 re: the new localized Tamil and current production localized Devanagari/Gurmukhi punctuation:

It looks like we have a number of decomposed punctuation forms that have the same (or very, very similiar) contours with different adv width/transforms.  I suggest that we have a look at these and consider a base set of outlines (we could export the existing non-exported *.alt forms) that are then used as components in the Devanagari, Gurmukhi, and Tamil localized punctuation designs.  Am I missing something in the localized designs that would prevent this?

E.g.,

- quoteright.alt (not currently exported)
- quoteright.loclDEVA
- quoteright.loclGURM
- quoteright.loclTAML

**Comment by chrissimpkins** [comment]
Note to self: these changes include a new set of height-adjusted international figure forms for Tamil script locales. The outlines are shorter than the default figures.

**Comment by chrissimpkins** [comment]
> Note to self: these changes include a new set of height-adjusted international figure forms for Tamil script locales. The outlines are shorter than the default figures.

@kalapi is this common practice?  I appreciate that this is likely what you want when the figs are combined with other Tamil forms in text, but what about other contexts (e.g., spreadsheets/times/dates/temperatures)?  If we modify the figure designs we may need to address those issues as well by, for instance, having localized MM DD YY and HH MM separator positions?  How are international figs used in Tamil script supported writing systems?

**Comment by belluzj** [comment]
> Did we end up removing the new brace layers?

Yes, I didn't import them, based on that comment: https://github.com/googlefonts/googlesans/issues/357#issuecomment-908458624

**Comment by chrissimpkins** [comment]
FIgure heights: #389 

Punctuation components: #390 

IMO we can merge this before the #389 review is complete but I'd like to have Kalapi complete this review before we push the v6 release next week.  If there are issues (e.g., we need additional localized punctuation for some use case areas, there are platform-specific staggered figure top alignment issues due to #31) then we can remove the feature code and pull in the localized Tamil international numerals in a future release.  Per Kalapi, the localized international fig forms will be used as the default for the use cases that I mentioned above (dates, times, spreadsheets, etc)  in Tamil script supported writing systems.  The encoded Tamil script figs are used in contexts that are unlikely to be relevant for this typeface (e.g., religious calendar dates) and are not used in the above situations.

**Comment by chrissimpkins** [comment]
### Tamil import file size change

#### Pre

```
build/GoogleSans/variable/GoogleSans-Italic[GRAD,opsz,wght].ttf

             Summary Statistics              
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃                    Statistic ┃   Size (B) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│                        Total │ 1098416.00 │
│ Avg per encoded glyph (1806) │     608.20 │
│   Avg per total glyph (3371) │     325.84 │
└──────────────────────────────┴────────────┘

build/GoogleSans/variable/GoogleSans[GRAD,opsz,wght].ttf

             Summary Statistics              
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃                    Statistic ┃   Size (B) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│                        Total │ 1043460.00 │
│ Avg per encoded glyph (1806) │     577.77 │
│   Avg per total glyph (3375) │     309.17 │
└──────────────────────────────┴────────────┘
```

#### Post

```
build/GoogleSans/variable/GoogleSans-Italic[GRAD,opsz,wght].ttf

             Summary Statistics              
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃                    Statistic ┃   Size (B) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│                        Total │ 1234252.00 │
│ Avg per encoded glyph (1878) │     657.22 │
│   Avg per total glyph (3553) │     347.38 │
└──────────────────────────────┴────────────┘

build/GoogleSans/variable/GoogleSans[GRAD,opsz,wght].ttf

             Summary Statistics              
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃                    Statistic ┃   Size (B) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│                        Total │ 1164604.00 │
│ Avg per encoded glyph (1878) │     620.13 │
│   Avg per total glyph (3557) │     327.41 │
└──────────────────────────────┴────────────┘
```

**Comment by chrissimpkins** [comment]
LGTM.

This looks great @kalapi.  Thank you very much for all of your help with the merge over the last few weeks.

Great job @belluzj @madig!

Thanks all!

**Pull request merged**
