### PR TITLE
Revise optical size axis to "eliminate" interpolation

### LINKED ISSUE #49: Add support for opsz step function instead of interpolation across opsz axis
Discussed at GS core weekly meeting on 6/4/20 with Dave Crossland, Damien Correll, and Jonathan Lee.  The team decided to eliminate the opsz axis linear interpolation over the 14 - 18  range and create an abrupt step function transition from min opsz to max opsz designs at the 17/18 transition point.  This will maintain the current definition "Google Sans Text" = 17 and below, "Google Sans" = 18 and above.  

This change will be applied to all merged scripts.

TODO:

- [x] review approach to handle the brace layers defined in the typeface (there was discussion that perhaps the interpolation could be reintroduced in the future which means that they likely need to stay)
- [x] investigate approach to elimination of the opsz axis interpolation in the VF format builds - move 14px masters to 17px + remove all brace layer definitions?
- [ ] implement (#62)

### PR DESCRIPTION
**Pull request by chrissimpkins**
This PR revises the opsz axis to eliminate support for interpolation between 14 - 18 px sizes where our masters were previously defined.  

The changes include:

- move 14 px masters to 17 px and keep 18 px as is
- move all bracket layers to value of 18
- remove all brace layers (see https://github.com/googlefonts/googlesans/pull/60#issuecomment-649815397 for assessment of impact a/w this change)

We experimented with brace layer definitions at the min opsz master value (not supported, this duplicates masters) and at intermediate float values (17.01, not supported, glyphsLib part of pipeline does not support non-integer brace layer definitions).  

Interpolation still occurs at float values between 17 and 18 so we have not formally eliminated interpolation, but this is restricted to px sizes that should not be set for typical use cases and will be outside of any guidance re: typeface use.  In typical use, Google Sans will be viewed at 18px and above.  Google Sans Text will be viewed at 17 px and below.  We anticipate that there could be issues with this approach for teams that animate across the 17 - 18 px range and teams that expose the ability to set px size for type (and have users who would select float values...).  In these cases, the abrupt transition in forms like upper case `G` and undesirable interpolation of outlines that were previously addressed with brace layers will be visible.

Supersedes #60 
Closes #49 
Fixes VF menu names with merge of #64 into this branch
Fixes static instance file path names with merge of https://github.com/googlefonts/googlesans/pull/65 into this branch

### CODE REVIEW

**Comment by chrissimpkins** [comment]
With these changes, the builds work again and we are now failing on fontbakery character set checks.  This is to be expected as the bracket layer changes alter the expected values.  Will bless the new expected character set and confirm that this addresses the fail.

**Comment by davelab6** [comment]
Sounds good, thank you Chris!

**Comment by chrissimpkins** [comment]
Moved nominal values in 2-axis VF STAT tables to 17 in https://github.com/googlefonts/googlesans/pull/62/commits/fe20766fa23a33f7c47b54e739d14618fcd4934c

**Comment by chrissimpkins** [comment]
Fontbakery checks updated and are all passing as of https://github.com/googlefonts/googlesans/pull/62/commits/86cb1f04d2ff9c2b4372039620fce994a556e317

**Comment by chrissimpkins** [comment]
#64 merged into this branch with fixes for defined VF instance names

**Comment by chrissimpkins** [comment]
All name fixes across static, single axis (partial) VF, and two-axis VF builds are now merged into this branch.  These changes are up to date with all work that is targeted to the v3.001 release of Google Sans as of https://github.com/googlefonts/googlesans/pull/62/commits/eeb7017ebd6dddeb0020396bb31422c94d73cf2f

cc @Colophon-Foundry

**Comment by chrissimpkins** [comment]
Latin set changes reviewed by Edd Harrington and approved for production use
Cyrillic set changes reviewed by Alexei Vanyashin and approved for production use
Greek set changes reviewed by Irene Vlachou and approved for production use

**Comment by chrissimpkins** [comment]
Marc Foley and I reviewed the VF designs/changes here for regressions against static builds and found no blockers for a production push to replace the static instance defaults.

**Comment by chrissimpkins** [comment]
Merged contextual colon positioning between numerals (new `calt` feature) into this branch.  Originated on PR #72

**Comment by chrissimpkins** [comment]
#73 merged with fixes for issue #40

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/pull/62/commits/4a56e8bf478bab299bd897b723b06c8af106a9f9 fixes an interpolation issue in the medium variable font format instance of Google Sans Text `rightArrow.ss05`, upright build only.

**Comment by chrissimpkins** [comment]
v3.001 changelog current with the updates here in #75

**Comment by chrissimpkins** [comment]
Lots of changes and effort on the part of many team members here to get the 2-axis VF's ready for a production release.  Many thanks to all involved.  Merging this work to the master branch.  All teams based on these upstream sources should rebase their variable design space on these changes.  See the changelog in #75 for a detailed list of the changes that are coming as of the v3.001 release.

**Comment by davelab6** [comment]
It may be worthwhile to confirm with each team that they rebased
successfully this week, to prevent problems in futuer

**Pull request merged**
