### PR TITLE
Fix variable font names, sync with static font names

### PR DESCRIPTION
**Pull request by chrissimpkins**
Our current variable font definitions include style names that do not distinguish the defined instances for the "Google Sans" and "Google Sans Text" families in installation applications (confirmed in macOS Font Book) and other desktop applications (confirmed by Edd Harrington in Adobe Illustrator and InDesign).  Before these changes, the three weight style names are duplicated, once for Google Sans family and once for Google Sans Text family:

#### Menus before

- Regular
- Medium
- Bold
- Regular
- Medium
- Bold
- Italic
- Medium Italic
- Bold Italic
- Italic
- Medium Italic
- Bold Italic

This was due to incorrect specification of the fvar table.  The stylename values were not properly set in the sources.

With these source changes, the menus will should display the following instances:

#### Menus after

- Regular
- Medium
- Bold
- Text Regular
- Text Medium
- Text Bold
- Italic
- Medium Italic
- Bold Italic
- Text Italic
- Text Medium Italic
- Text Bold Italic

I've verified that this fixes the naming in macOS Font Book and that STAT table and fvar table named instances now appear in sync on Samsa.  We still need to verify that the issue is addressed in Adobe applications.

cc @Colophon-Foundry this should fix the Adobe Illustrator and InDesign menu issues that you raised earlier this week. Do you mind reviewing the source changes in this branch (based on the edits that we are making with the opsz axis transition, this includes all of the opsz axis edits and extends with the glyphs source changes to address the name table / fvar table issues that led to this problem) and then have a look at [the **static** and **variable** font builds](https://github.com/googlefonts/googlesans/actions/runs/149211288) to confirm that this appears to be a fix for the issue and did not create any new issues in your design applications?  This required a number of Glyphs specific source edits to the master names and custom parameters.  It seems to be fixed.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
cc @davelab6 I think that we have the Adobe application menu name fix in place here.

**Review by Colophon-Foundry — APPROVED** [review]
These are looking good to me @chrissimpkins !
Can confirm that the naming is all good in Illustrator '20. Interpolation is looking good there also.

**Comment by chrissimpkins** [comment]
Good to hear.  Thank you Edd!

**Comment by chrissimpkins** [comment]
Merging to Latin-opsz branch and these changes will be merged as part of PR #62

**Pull request merged**
