### PR TITLE
Import Tamil localized international figure fixes

### LINKED ISSUE #389: Review / revise new localized Tamil figure forms
New Tamil locale-specific international figure heights are being added in #374.  @kalapi and team will review these forms in a Linux/FreeType environment to confirm that we are not going to run into the same issues that we have in #31 (related #344).  The review will take place before we release the outlines in v6

cc @kalapi

### PR DESCRIPTION
**Pull request by chrissimpkins**
Imports glif contour and adv width changes that were pushed in https://github.com/googlefonts/googlesans/issues/389#issuecomment-939061290

Closes #389

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Requires design update to compile fonts https://github.com/googlefonts/googlesans/issues/389#issuecomment-942593947

I also need to update the HB shaping definitions with the changes in adv width that occur here

**Comment by chrissimpkins** [comment]
> Requires design update to compile fonts [#389 (comment)](https://github.com/googlefonts/googlesans/issues/389#issuecomment-942593947)


f07dc53fdafe3d362b41407854e74ff955d8c805

**Comment by chrissimpkins** [comment]
Tamil CI shaping file updated in https://github.com/googlefonts/googlesans/pull/408/commits/041daf6148628de450632b08006bde2e3b77f093.  Includes new advance widths that were added in https://github.com/googlefonts/googlesans/pull/408/commits/3b4a753663abc1e2cf7f397f20781ec2b24fdbde

**Comment by chrissimpkins** [comment]
New design edits were pushed to an archive linked in https://github.com/googlefonts/googlesans/issues/389#issuecomment-952801472

**Comment by chrissimpkins** [comment]
> import localized Tamil default figure revisions

Imported @ https://github.com/googlefonts/googlesans/pull/408/commits/cde9f563065ec98ce2f80ffaef89ede0b3e19978

**Comment by madig** [comment]
Chris, did you look at the changes in detail? I bulk-updated the expectations above.

**Comment by chrissimpkins** [comment]
> Chris, did you look at the changes in detail? I bulk-updated the expectations above.

Yep! Thanks for the prompt Nikolaus.  Kalapi and I discussed this and feel that this is the best that we can do with these figs in the FreeType environment.  I'll merge it now.

**Pull request merged**
