### PR TITLE
v3.002: Hebrew script merge, tabular zero spacing fix, tab figure calt feature fix

### LINKED ISSUE #47: Merge Hebrew script sources
Merge the Hebrew script design work by @fontef and @danielgrumer into the upstream source files.

TODO:

- [x] update bracket layer definitions for opsz axis changes in #60 (see https://github.com/googlefonts/googlesans/pull/56#issuecomment-647749754 for the definitions that need to be updated)
- [x] merge outlines for min opsz upright masters
- [x] merge outlines for min opsz italics masters
- [x] merge outlines for max opsz upright masters
- [x] merge outlines for max opsz italics masters
- [x] merge fea code for upright source
  - [x] languagesystem (hebr dflt + hebr IWR)
  - [x] global class definitions (renamed with hb_* prefix)
  - [x] aalt
  - [x] ccmp (must be first fea implemented)
  - [x] dlig (Yiddish rules)
  - [x] jalt
  - [x] kern
- [x] merge fea code for italics source
  - [x] languagesystem (hebr dflt + hebr IWR)
  - [x] global class definitions (renamed with hb_* prefix)
  - [x] aalt
  - [x] ccmp (must be first fea implemented)
  - [x] dlig (Yiddish rules)
  - [x] jalt
  - [x] kern
- [x] add Hebrew Unicode range setting in Font > Info tab
- [ ] update expected fea tags with new features that are merged with Hebrew glyph set
- [ ] update fontbakery char set QA tests with new Hebrew glyphs
- [ ] designer review of sources (review in progress)
- [ ] designer review of build artifacts (review in progress)

The review identified the following issues:

- [ ] H spacing is slightly off for some glyphs, more detailed review in progress to understand this problem
- [x] we support tab and caps variants of currency symbols, these new outlines and feature code support will be added to the sources

### PR DESCRIPTION
**Pull request by chrissimpkins**
This PR supersedes the Hebrew script merge work that we performed in #56.  The merge was repeated on the HEAD commit in the master branch as the upstream source diverged with work that was performed to wrap up the v3.001 release.

This PR merges the Hebrew script design work that was performed by Daniel Grumer and Yanek Iontef into the upright and italics source files.

In addition to the merge of the Hebrew script designs, the following changes were made based on discussions in meetings and in the #56 thread:

- edited the Latin ccmp `lookup ccmp_latn_1` lookup to **remove** the `latn` script registration
- added tabular and caps forms of the sheqel currency glyph + feature code support

During the first round merge with the Hebrew designs, Daniel recognized an environment script/language dependent issue with the glyph composition/decomposition (ccmp) feature support in the Hebrew. This issue was addressed by removing the Hebrew script + lang registration in the ccmp feature code **and** the Latin registration of a ccmp lookup that was positioned at a higher priority level in the feature source.  Edd Harrington and Gor Jihanian confirmed that this was not necessary for Latin script support.  These were merged as commented out fields from Daniel's source work and I edited them out of the ccmp feature source altogether.

Closes #47

cc @danielgrumer 
cc @Colophon-Foundry 
cc @gorjious 

---

### TODO

- [x] Fontef design team review and signoff (Yanek)
- [x] Fontef design team review and signoff (Daniel)

### CODE REVIEW

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/pull/76/commits/6edf59151e99f8ab81b59a0907168bb9aec57616 updates our expected glyph and glyph order definition files with the Hebrew updates.

**Comment by chrissimpkins** [comment]
reactivated feature tag tests in https://github.com/googlefonts/googlesans/pull/76/commits/d12bb48d2e944108f20af2330a80ce89683d4e6c

These checks will fail because we added a new feature tag (`jalt`) during the Hebrew merge.

**Comment by chrissimpkins** [comment]
Expected feature tags updated for the Hebrew merge in https://github.com/googlefonts/googlesans/pull/76/commits/40f17e8f9e9ee342666c2e566baf3a62015cbbd2.  The CI should pass with this update.

**Comment by chrissimpkins** [comment]
QA testing updated for the Hebrew additions and we are green on all tests.

**Comment by chrissimpkins** [comment]
@danielgrumer The sheqel, sheqel.tf, and sheqel.cap definitions were not included in the feature classes until commit https://github.com/googlefonts/googlesans/pull/76/commits/6533731d967e7adf490e8fe9c6ef59aecdb7d586. 

The new download links with these changes are available in https://github.com/googlefonts/googlesans/actions/runs/209176125

**Comment by chrissimpkins** [comment]
I can verify that the tabular and case forms of the sheqel currency glyph are functioning properly after the changes in https://github.com/googlefonts/googlesans/pull/76/commits/6533731d967e7adf490e8fe9c6ef59aecdb7d586

**Comment by chrissimpkins** [comment]
Download links for the build archives as of commit https://github.com/googlefonts/googlesans/pull/76/commits/d0bd36bf3df0acd5bfb867f36615e4bc107f43bb

https://github.com/googlefonts/googlesans/actions/runs/236454680

**Comment by chrissimpkins** [comment]
@Colophon-Foundry Edd, your zero tab figure changes were merged into this branch as of https://github.com/googlefonts/googlesans/pull/76/commits/bb211835fec4656280a72cb348d8153922a5bf11 and will be released in v3.002.  I anticipate that this will be pushed to the Fonts eng team next week for release/rollout testing.

**Comment by chrissimpkins** [comment]
Merged a fix for the colon positioning between tabular figures into this branch @  https://github.com/googlefonts/googlesans/pull/76/commits/07c8d6442a30743bbbc02c1d2be651f741685e74

**Comment by chrissimpkins** [comment]
Approved by Yanek.

Await feedback from @danielgrumer

**Review by danielgrumer — APPROVED** [review]
Looks perfect! ✌️

**Comment by chrissimpkins** [comment]
Thanks Daniel! 

We have approval from both Yanek and Daniel.  I will prep the GS v3.002 release with these updates

**Comment by chrissimpkins** [comment]
The v3.002 release is built and available @ https://github.com/googlefonts/googlesans/releases/tag/v3.002 

I'll get this pushed over the engineering team this week.  Thank you very much @danielgrumer and Yanek for all of your work and input on this!

**Comment by chrissimpkins** [comment]
@moyogo https://github.com/googlefonts/googlesans/releases/tag/v3.002 @ commit https://github.com/googlefonts/googlesans/commit/c979d02892bb071e6039a12aeb709df5bdfd72bb will be the latest Hebrew definitions for our cantillation mark shaping work in October.  Talk soon.

cc: @danielgrumer

**Comment by danielgrumer** [comment]
Thanks @chrissimpkins for all your help, we were glad to take part! looking forward to see it in action soon 🤘

**Pull request merged**
