### PR TITLE
Update requirements (based on v6.000)

### PR DESCRIPTION
**Pull request by belluzj**

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Builds failed with fontmake update

**Comment by chrissimpkins** [comment]
It looks like we may have some bracket layer / rvrn glyph definitions still around?

> ERROR:fontmake.compatibility:Fonts had differing number of contours in glyph y.BRACKET.18

**Comment by madig** [comment]
Seems like a fontmake issue: https://github.com/googlefonts/fontmake/pull/832#issuecomment-1004936839

**Comment by chrissimpkins** [comment]
> Seems like a fontmake issue: [googlefonts/fontmake#832 (comment)](https://github.com/googlefonts/fontmake/pull/832#issuecomment-1004936839)

Looks like maybe fixed in https://github.com/googlefonts/fontmake/pull/840?

If so, I guess we'll need a new fontmake release to push Khmer with the sources as is. Or we can remove the non-exported glyphs that are causing problems?

**Comment by belluzj** [comment]
@chrissimpkins when is your target release date for v7.000? @anthrotype and @madig are both back next week for the new fontmake release.

Otherwise I could go and remove the BRACKET glyphs from the sources.

**Comment by chrissimpkins** [comment]
> @chrissimpkins when is your target release date for v7.000? @anthrotype and @madig are both back next week for the new fontmake release.
> 
> Otherwise I could go and remove the BRACKET glyphs from the sources.

Jany and I discussed this issue during a meeting today.  We will push the Khmer import that requires the fontmake update back to the GS v8 release so that we have sufficient time to work through the ability to compile Khmer and complete the review process on production builds that use the updated pipeline.

**Comment by madig** [comment]
Looking at the diffs pre/post update, I found:

1. Various lookups turned into extension lookups (probabaly the change in fontTools 4.28.4, https://github.com/fonttools/fonttools/pull/2465)
2. Various GSUB glyph coverage records dropped duplicate entries (change in fontTools 4.28.2, https://github.com/fonttools/fonttools/issues/2433)

So the update looks good to me.

**Comment by madig** [comment]
@chrissimpkins how should we proceed here? I think the update can go in, and then we can rebase #425, #416 and #417 on top?

**Comment by chrissimpkins** [comment]
IIUC we don't need this for #435 or #416.  I think that I will release those changes without the fontmake update, then we can base the Khmer work in #417 (and everything else planned for GS v8.000) on the updated compiler. Sg?

**Comment by madig** [comment]
Ok :)

**Comment by chrissimpkins** [comment]
> Ok :)

Sorry! I need a pause in changes so that I can prep GS v7 this week. :) 

Keep forging ahead on the Khmer.  We'll try to wrap up that import, build, and review over the next couple of weeks before we dive into the next script.

**Comment by madig** [comment]
This is ready to go.

**Pull request merged**
