### PR TITLE
Fix southeast arrow (U+2198) and southwest arrow (U+2199) directions

### LINKED ISSUE #40: Fix `↙` and `↘` orientation
Affects: U+2198 and U+2199

Operating system: macOS 10.15.4 (19E287) corp

Browser: Chrome (Version 81.0.4044.129 (Official Build) (64-bit))

Affected weight(s): All

Affected character(s): ↙ ↘

Steps to Reproduce:

- Paste ↙↘
- Set the font to "Google Sans"
- Result: Visually, you'll see ↘↙ upon changing the font to Google Sans

Expected: To see '↙↘'

Notes: The ↗↖ characters do not have the same problem.

### PR DESCRIPTION
**Pull request by chrissimpkins**
Fixes #40

The directions were swapped in the regular and italics sources.  This does not affect other arrows in the set.

cc @Colophon-Foundry: This will need to be reviewed in Mono and Wayfinding designs too

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Fix visually confirmed as of commit https://github.com/googlefonts/googlesans/pull/73/commits/dfeff0f5a54dc84196f1e62a5cb9e745c2bda1a0

Fonts are available in https://github.com/googlefonts/googlesans/actions/runs/187718057

It looks like these changes updated the glyph order leading to CI fails for both the static and VF builds.  I will review the char set diff to sort out what is going on.

**Comment by chrissimpkins** [comment]
@Colophon-Foundry Edd, you can see the affected glyphs in the source diff https://github.com/googlefonts/googlesans/pull/73/files

I'll have a more detailed look at what is going on later today.  On a quick glance last evening after I made these changes it appears that this may be a reordering issue.  I'm not sure yet whether any change manifests in the build artifacts aside from a glyph order change.  While this won't cause us problems, it is odd that it happened and I'm not sure why a simple outline swap in the Glyphs editor led to this issue.  I'll post more info when I have it today.

**Comment by chrissimpkins** [comment]
@Colophon-Foundry I verified that this CI fail was a glyph order change.  I will push the ordered glyph lists today. Must be a Glyphs editor version issue?

**Comment by chrissimpkins** [comment]
The font CI is passing with the new glyph lists that were pushed in https://github.com/googlefonts/googlesans/pull/73/commits/9c0a5274e2a5e18d7e4c1103985b1a3fcc8d4177

I can verify that all glyph numbers remain the same.  Glyph order changes with these Glyphs editor Version 2.6.5 (1342) edits.  The affected glyphs are:

- ustraitcy.sc
- ustraitstrokecy.sc
- acute
- breve
- caron
- cedilla
- circumflex
- ring
- tilde

**Comment by chrissimpkins** [comment]
## Diffenator v0.9.6

Displaying the 50 most significant items in each table. To increase use the '-ol' flag


### attribs modified: 1

table | attrib | value_a | value_b
--- | --- | --- | --- |
head | modified | 2020/07/29 15:52:02 | 2020/07/31 10:48:05

### glyphs modified: 2

glyph | diff | string
--- | --- | --- |
uni2198 | 0.0017 | ↘
uni2199 | 0.0017 | ↙

glyphs_modified

This looks clean vs. the parent commit. I think that the glyph order change is the only significant issue here.

**Review by Colophon-Foundry — APPROVED** [review]
Looks good to me!

**Comment by chrissimpkins** [comment]
Thanks Edd!

**Comment by chrissimpkins** [comment]
Merging

**Comment by chrissimpkins** [comment]
D/W Dave Crossland, the CLA check does not apply to source contributions on this repository.  OK to ignore the googlebot CLA consent authorization.

**Pull request merged**
