### PR TITLE
Import cap height default / international figures in opsz 18 masters

### PR DESCRIPTION
**Pull request by madig**
Taken from https://github.com/googlefonts/googlesans/tree/berlow-figures.

Imported 

- numbersign 
- dollar 
- percent 
- zero 
- one 
- two 
- three 
- four 
- five 
- six 
- seven 
- eight 
- nine 
- cent 
- sterling 
- yen 
- One-roman 
- Two-roman 
- Three-roman 
- Four-roman 
- Five-roman 
- Six-roman 
- Seven-roman 
- Eight-roman 
- Nine-roman 
- Ten-roman 
- Eleven-roman 
- Twelve-roman 
- Fifty-roman 
- Hundred-roman 
- Fivehundred-roman 
- Thousand-roman 
- Onethousandcd-roman 
- Fivethousand-roman 
- Tenthousand-roman 
- numbersign.tf 
- baht 
- dong 
- euro 
- florin 
- franc 
- hryvnia 
- lira 
- liraTurkish 
- peso 
- ruble 
- rupeeIndian 
- tenge 
- tugrik 
- won 
- baht.cap 
- cent.cap 
- cent.tf 
- currency.tf 
- dollar.tf 
- dong.tf 
- euro.tf 
- florin.tf 
- franc.tf 
- hryvnia.tf 
- lira.tf 
- liraTurkish.tf 
- peso.tf 
- ruble.tf 
- rupeeIndian.tf 
- sterling.tf 
- tenge.tf 
- tugrik.tf 
- won.tf 
- yen.tf 
- degree 
- pertenthousand 
- perthousand 
- centigrade 
- fahrenheit 
- sheqel 
- sheqel.tf 
- zeropercent

---

@chrissimpkins edits below:

Text runs for testing:

```
0123456789 
#%‱‱°℃℉
ⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩⅪⅫⅬⅭⅮⅯↀↁↂ
$¢£¥฿₫€ƒ₣₴₤₺₱₽₹₸₮₩₪
```
---

### CODE REVIEW

**Comment by chrissimpkins** [comment]
## Default figure overlay difference

hb-view image diffs

Only intended to understand the design changes at this stage. This does not indicate grid fit in a FreeType env.

<details>
<summary>opsz=18, wght=400, GRAD=0</summary>





</details>

<details>
<summary>opsz=18, wght=700, GRAD=0</summary>





</details>

**Comment by chrissimpkins** [comment]
## Fig height associated symbols overlay difference

hb-view image diffs

Only intended to understand the design changes at this stage. This does not indicate grid fit in a FreeType env.

<details>
<summary>opsz=18, wght=400, GRAD=0</summary>




</details>

<details>
<summary>opsz=18, wght=700, GRAD=0</summary>






</details>

**Comment by chrissimpkins** [comment]
## Roman numerals overlay difference

hb-view image diffs

Only intended to understand the design changes at this stage. This does not indicate grid fit in a FreeType env.

<details>
<summary>opsz=18, wght=400, GRAD=0</summary>






</details>

<details>
<summary>opsz=18, wght=700, GRAD=0</summary>





</details>

**Comment by chrissimpkins** [comment]
## Currency symbols overlay difference

hb-view image diffs

Only intended to understand the design changes at this stage. This does not indicate grid fit in a FreeType env.

<details>
<summary>opsz=18, wght=400, GRAD=0</summary>






</details>

<details>
<summary>opsz=18, wght=700, GRAD=0</summary>





</details>

**Comment by chrissimpkins** [comment]
The terminals on the **italic** 6, 7 (baseline), and 9 have angles that change across the GRAD axis.  Shown below at wght=700 where it is most apparent in a video, but it looks like this occurs across the entire wght axis.

figure_GRAD

Fonts: https://github.com/googlefonts/googlesans/suites/4234327267/artifacts/109660250

Thoughts @dberlow?

**Comment by dberlow** [comment]
Well, that's not good
Fixes to opsz17 GRAD +/- enclosed
[GS17GRAD-TerminalFix.zip](https://github.com/googlefonts/googlesans/files/7574390/GS17GRAD-TerminalFix.zip)

**Comment by chrissimpkins** [comment]
Thanks David! Were the changes only in the 6,7, and 9?

**Comment by dberlow** [comment]
Yes. I only changed italic 6,7 and 9, I changed them all, and in both grad-50 and 200 .

On Nov 21, 2021, at 10:12 AM, Chris Simpkins ***@***.***> wrote:

﻿
Thanks David! We're the changes only in the 6,7, and 9?

**Comment by chrissimpkins** [comment]
Thank you!

**Comment by madig** [comment]
Reimported. Sorry, what remains to be done here?

**Comment by chrissimpkins** [comment]
> Reimported. Sorry, what remains to be done here?

Thanks! I need to review the updated fig designs.

**Comment by madig** [comment]
Todo: round coordinates, avoid https://github.com/googlefonts/googlesans/pull/412/files#diff-2a832374cf1bbd28a74535f02c8cf2e067f7794d79912813158f460186186424

**Comment by chrissimpkins** [comment]
> Todo: round coordinates, avoid https://github.com/googlefonts/googlesans/pull/412/files#diff-2a832374cf1bbd28a74535f02c8cf2e067f7794d79912813158f460186186424

Do any UFO source normalizers do this at the source level?

**Comment by madig** [comment]
I don't think so because it's actual data and not formatting 🤔

**Comment by chrissimpkins** [comment]
> I don't think so because it's actual data and not formatting 🤔

Only difference is the text string representation of the same floating point value across those source files though no?

**Comment by chrissimpkins** [comment]
Interesting. It looks like we have a combination of floats and integer coordinate values  across the glif source files.  I suppose that this is a consequence of different serializers writing the files? How is the compiler rectifying this?  Does it use the Py default of casting ints to floats when int <==> float arithmetic is performed?  Or is every coordinate assumed to be a float at read? Or round/ceil/floor to int used at read?

**Comment by madig** [comment]
I mean we have a mix of `123.0` and `456.9999999999999998`. The former is a formatting issue, the latter a data issue. It might be that ufoLib2/fontTools.ufoLib does not drop the `.0` part automatically. Norad does, if it can. I think ufo2ft/fontTools will simply `otRound` where appropriate.

**Comment by chrissimpkins** [comment]
One of the [baht.glif masters in this branch](https://github.com/googlefonts/googlesans/blob/5e12f28419da0423ecfb160090e740df6dcd9542/source/GoogleSans/GoogleSans-opsz17-wght380-GRAD0.ufo/glyphs/baht.glif) includes the following:

```xml
<outline>
    <contour>
      <point x="84" y="0" type="line"/>
      <point x="376" y="0" type="line" smooth="yes"/>
      <point x="501" y="0"/>
      <point x="591" y="84"/>
      <point x="591" y="208" type="curve" smooth="yes"/>
      <point x="591" y="290"/>
      <point x="542" y="354"/>
      <point x="473" y="378" type="curve"/>
      <point x="473" y="382" type="line"/>
      <point x="529" y="408"/>
      <point x="568" y="459"/>
      <point x="568" y="536" type="curve" smooth="yes"/>
      <point x="568" y="648"/>
      <point x="479" y="716"/>
      <point x="362" y="716" type="curve" smooth="yes"/>
      <point x="84" y="716" type="line"/>
    </contour>
    <contour>
      <point x="169" y="80" type="line"/>
      <point x="169" y="636" type="line"/>
      <point x="366" y="636" type="line" smooth="yes"/>
      <point x="440" y="636"/>
      <point x="485" y="603"/>
      <point x="485" y="526" type="curve" smooth="yes"/>
      <point x="485" y="450"/>
      <point x="439" y="417"/>
      <point x="362" y="417" type="curve" smooth="yes"/>
      <point x="129" y="417" type="line"/>
      <point x="129" y="337" type="line"/>
      <point x="376" y="337" type="line" smooth="yes"/>
      <point x="455" y="337"/>
      <point x="506" y="292"/>
      <point x="506" y="209" type="curve" smooth="yes"/>
      <point x="506" y="126"/>
      <point x="456" y="80"/>
      <point x="380" y="80" type="curve" smooth="yes"/>
    </contour>
    <contour>
      <point x="279" y="-100" type="line"/>
      <point x="350" y="-100" type="line"/>
      <point x="350" y="816" type="line"/>
      <point x="279" y="816" type="line"/>
    </contour>
  </outline>
```

**Comment by chrissimpkins** [comment]
And a [different baht.glif master in this branch](https://github.com/googlefonts/googlesans/blob/5e12f28419da0423ecfb160090e740df6dcd9542/source/GoogleSans/GoogleSans-opsz17-wght380-GRAD200.ufo/glyphs/baht.glif) includes the following:

```xml
<outline>
    <contour>
      <point x="74.0" y="0.0" type="line"/>
      <point x="386.0" y="0.0" type="line" smooth="yes"/>
      <point x="511.0" y="0.0"/>
      <point x="601.0" y="84.0"/>
      <point x="601.0" y="201.0" type="curve" smooth="yes"/>
      <point x="601.0" y="290.0"/>
      <point x="551.0" y="353.0"/>
      <point x="473.0" y="378.0" type="curve"/>
      <point x="473.0" y="382.0" type="line"/>
      <point x="536.9999999999999" y="410.0"/>
      <point x="578.0" y="459.0"/>
      <point x="578.0" y="545.0" type="curve" smooth="yes"/>
      <point x="578.0" y="648.0000000000001"/>
      <point x="489.0" y="716.0"/>
      <point x="372.0" y="716.0" type="curve" smooth="yes"/>
      <point x="74.0" y="716.0" type="line"/>
    </contour>
    <contour>
      <point x="189.0" y="110.0" type="line"/>
      <point x="189.0" y="606.0" type="line"/>
      <point x="356.0" y="606.0" type="line" smooth="yes"/>
      <point x="421.0" y="606.0"/>
      <point x="465.0" y="601.9999999999999"/>
      <point x="465.0" y="521.0" type="curve" smooth="yes"/>
      <point x="465.0" y="441.0"/>
      <point x="420.0" y="432.0"/>
      <point x="352.0" y="432.0" type="curve" smooth="yes"/>
      <point x="139.0" y="432.0" type="line"/>
      <point x="139.0" y="322.0" type="line"/>
      <point x="366.0" y="322.0" type="line" smooth="yes"/>
      <point x="436.0" y="322.0"/>
      <point x="486.0" y="295.0"/>
      <point x="486.0" y="216.0" type="curve" smooth="yes"/>
      <point x="486.0" y="138.0"/>
      <point x="437.0" y="110.0"/>
      <point x="370.0" y="110.0" type="curve" smooth="yes"/>
    </contour>
    <contour>
      <point x="254.0" y="-100.0" type="line"/>
      <point x="350.0" y="-100.0" type="line"/>
      <point x="350.0" y="816.0" type="line"/>
      <point x="254.0" y="816.0" type="line"/>
    </contour>
  </outline>
```

**Comment by madig** [comment]
That triggered me, yes :grimacing:

**Comment by chrissimpkins** [comment]
> That triggered me, yes 😬

Apologies.  I did not see #430 until now... :)

**Comment by chrissimpkins** [comment]
I noticed this in new work that David Berlow pushed today. I assume that this is coming from the Robofont editor UFO serialization env:



There are cases of both float ==> int, and int ==> float coordinate value edits in the same write.

**Comment by madig** [comment]
Need to rebase on https://github.com/googlefonts/googlesans/pull/441 and apply normalization.

**Comment by madig** [comment]
Was this postponed again?

**Comment by madig** [comment]
Reimported from https://github.com/googlefonts/googlesans/tree/berlow-figures without the `.alt` glyphs.

**Comment by MariannaPaszkowska** [comment]
The positioning in ℃ ℉ (U+2103 and U+2109) changed in some sizes. Is it intentional? @dberlow 
CC @madig 
The top two rows are fonts built from the branch build-berlow-figs. Bottom are fonts from the latest release (main branch):
Screenshot 2023-10-16 at 12 14 38 PM

**Comment by dberlow** [comment]
I would assume there to be a little tighter spacing at opsz18, as in this designsapce that's largest design size. 

And I assume at GRAD181.4 it might look tighter,  in response to some need for additional luminance.

How there got to be a difference between one version and another is not something I'd know though, as this is a branch made by others and I have not committed here or to this font in two years, as far as I know. 

I'm happy to fix the spacing of the degree sign if I know what version to work on.

**Comment by MariannaPaszkowska** [comment]
@dberlow, thanks for this update! We will look into the origin of this change. Would it make sense to keep the original spacing (from the main branch)?
CC @madig @belluzj

**Comment by belluzj** [comment]
Hello @MariannaPaszkowska , as we're looking to kick off the Latin respacing merge again, I think we need to merge this first. Are you OK for us to proceed with editing this branch to have the spacing of the main branch, as per your last message? Or are you waiting for confirmation from @dberlow?

**Comment by MariannaPaszkowska** [comment]
@belluzj Let's update the spacing to match the old one, but make sure we're importing the ℃ ℉ (U+2103 and U+2109) with the correct, updated height.

**Comment by belluzj** [comment]
@MariannaPaszkowska looking at this, our designers propose to do the following changes to the branch, in addition to restoring the spacing from main:

Current glyphs in this branch:
* /centigrade
  * composed of /degree + /C
* /fahrenheit
  * composed of /degree + /F
* /centigrade.cap (same as /centigrade)
* /fahrenheit.cap (same as /fahrenheit)
* /C-figureht (same as /C with big LSB)
* /F-figureht (same as /F with big LSB)

Proposal: delete the last 4 glyphs, they're redundant now 

What do you think?

**Comment by belluzj** [comment]
@MariannaPaszkowska another question from the designer working on this @elenaperaltad: because David Berlow's uppercases are bigger, respecting the distance between the degree and the base glyph (C or F) means that they get displaced, sometimes further than the current advanced width. This means these characters ºC ºF will need to change its advance width. Is that okey or do we need to keep the current advance width?

The shapes in grey are David Berlow's, the outlines in the background are from main. So as you can see if we adjust it we get negative RSB.

image

**Comment by belluzj** [comment]
@MariannaPaszkowska this is ready to review and merge

**Comment by belluzj** [comment]
@MariannaPaszkowska actually, one more question about this from @elenaperaltad : now that the default figures are at cap height, should we delete the figures.cap? They're basically the same as the default. What do you think?

**Comment by belluzj** [comment]
@MariannaPaszkowska as discussed in the meeting, I will delete the .cap glyphs which are not needed anymore and push to this branch

**Comment by belluzj** [comment]
@MariannaPaszkowska on this, we noticed that /dram-arm hasn't been updated; it was not mentioned in the briefing doc from David Berlow back in the day: https://docs.google.com/document/d/1I8isKdbPGHUJZAcEr3Jr7VafADrRn8F4ET7WU30k5Y8/edit

Should we update it as well to cap-height?

Picture is /dram-arm.cap in light grey fill, and /dram-arm in blue outline in the background.

image

**Comment by MariannaPaszkowska** [comment]
@belluzj @elenaperaltad yes, we need to update /dram-arm too, thanks you for pointing that out!

**Comment by belluzj** [comment]
@MariannaPaszkowska this is ready again for review and merge

**Comment by belluzj** [comment]
I must point out that I'm including in this the commits about the glyph order from PR https://github.com/googlefonts/googlesans/pull/533

PR 533 was approved and merged but it went into update-deps instead of main (my fault, I changed the target branch some time ago to make reviewing easy but forgot to change it back before merging).

**Comment by MariannaPaszkowska** [comment]
Thank you, everyone for your hared work on this PR, I tested it and merged.

**Pull request merged**
