### PR TITLE
Use PyPy3

### PR DESCRIPTION
**Pull request by madig**
Supersedes https://github.com/googlefonts/googlesans/pull/299

### CODE REVIEW

**Comment by madig** [comment]
For clarity, I think we currently only need to update the unicodedata2 package to work with PyPy to make fontmake fully usable on it. This may require taking ownership of the package.

- https://github.com/mikekap/unicodedata2/pull/42/
- https://github.com/mikekap/unicodedata2/issues/43

**Comment by chrissimpkins** [comment]
> For clarity, I think we currently only need to update the unicodedata2 package to work with PyPy to make fontmake fully usable on it. This may require taking ownership of the package.
> 
> * [Support pypy mikekap/unicodedata2#42](https://github.com/mikekap/unicodedata2/pull/42)
> * [request to move repo under fonttools organization mikekap/unicodedata2#43](https://github.com/mikekap/unicodedata2/issues/43)

Good news. Let's see what Mike has to say.

**Comment by chrissimpkins** [comment]
We are blocked on the unicodedata2 issue that Niko mentioned in https://github.com/googlefonts/googlesans/pull/364#issuecomment-895423776.  This is paused until that is resolved.  Not a terribly high priority issue for us to address in this project, but it would be nice to have.  Let's give Mike some time. 

cc @justvanrossum this is where Nikolaus is with the pypy3 transition in the upstream repo

**Comment by behdad** [comment]
Can someone post a summary off changes and achievements please?

**Comment by madig** [comment]
Regarding PyPy? None, we're still trying make modules for it.

**Comment by anthrotype** [comment]
quick update: unicodedata2 was moved under fonttools github org and the latest release https://github.com/fonttools/unicodedata2/releases/tag/14.0.0 added support for PyPy3

Would be good to retry after this to see if there's any other blockers for pypy3 support (whether or not you're going to use it for GS)

**Comment by chrissimpkins** [comment]
> quick update: unicodedata2 was moved under fonttools github org and the latest release https://github.com/fonttools/unicodedata2/releases/tag/14.0.0 added support for PyPy3
> 
> Would be good to retry after this to see if there's any other blockers for pypy3 support (whether or not you're going to use it for GS)

Fantastic! Thanks Cosimo.  We're still interested in the transition and will give it a try.

**Comment by anthrotype** [comment]
thanks! I'd curious to know whether you do get any speed improvements using pypy and if so how much faster

**Comment by chrissimpkins** [comment]
We'll let you know.  @justvanrossum and @JeremieHornus are using pypy3 in the GS CJK build and IIUC they are seeing ~ 50% reduction in overall compile times.

**Comment by anthrotype** [comment]
> 50% reduction in overall compile times

not too bad

**Comment by madig** [comment]
So, I just tried this on the import-telugu branch by just making a venv with Pypy 7.3.9. I could install dependencies without any messing around. Build times dropped from ~535 s (CPython 3.8.10) to ~350 s (Pypy 7.3.9), so a ~35% improvement. Not bad.

**Comment by chrissimpkins** [comment]
That’s great news.  Think we are ready to make the transition?

**Comment by justvanrossum** [comment]
Not sure if this is considered “messing around” but I found that ensuring lxml is *not* installed, and ensuring the Python version of cu2qu is used brought significant further speedups under pypy.

**Comment by madig** [comment]
Hm. It seems fontmake is hardcoded to ask for lxml. Pure-Python cu2qu can be made to be installed with `--no-binary`, since ufo2ft won't use the fontTools-provided one.

Oh, also, the numbers above are gs-vf and gs-statics without table packing.

On main, with lxml and binary cu2qu, making vf/statics/compatible targets and compressing GPOS takes ~810 s, without lxml and binary cu2qu, ~700 s. That's something.

I'll see if I can fiddle with the deps, actually.

**Comment by madig** [comment]
Actually, I'd like the other PRs in flight to land first (#493, #496) so that I have a better base to pypy on.

**Comment by madig** [comment]
@justvanrossum cu2qu has no binary wheels for Pypy, so it should use pure Python code by default when you pip install it? Did you deliberately change it?

**Comment by justvanrossum** [comment]
Hmm, possibly I remember it wrong! When I look at it now I indeed don't see how it could have used the compiled version.

**Comment by justvanrossum** [comment]
Ah, it actually installs (or builds?) a .so for `cu2qu==1.6.7`, and not for the current `1.6.7.post1` wheels, so I guess I was testing then.

**Comment by madig** [comment]
So, I benchmarked lxml-not-present on the make-compat-masters branch plus the overlap script stuff:

```
> hyperfine -m 2 "time make -j"
Benchmark 1: time make -j
  Time (mean ± σ):     669.192 s ±  1.358 s    [User: 3172.408 s, System: 14.773 s]
  Range (min … max):   668.232 s … 670.152 s    2 runs
```

vs. lxml-present:

```
> pip install lxml
Collecting lxml
  Using cached lxml-4.8.0-pp38-pypy38_pp73-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (5.5 MB)
Installing collected packages: lxml
Successfully installed lxml-4.8.0
> hyperfine -m 2 "time make -j"
Benchmark 1: time make -j
  Time (mean ± σ):     815.312 s ± 11.583 s    [User: 3672.210 s, System: 18.015 s]
  Range (min … max):   807.121 s … 823.502 s    2 runs
```

This leads me to think that fontmake should make lxml optional when running under Pypy.

**Comment by madig** [comment]
https://github.com/googlefonts/fontmake/pull/886

**Comment by madig** [comment]
Right, so when I use pypy with the same requirements (sans lxml), I get identical TTX dumps. Upgrading fonttools to 3.4.0a2 and implicitly ufo2ft so I don't have to mess with dependencies however results in some diffs I don't quite understand (some contour reordering in some glyphs plus koa-ethiopic losing anchors or something?! Also GS Italic losing the "Italic" in name ID 6 and probably other stuff). Meh. Messing it is then.

**Comment by madig** [comment]
Closed in favor of https://github.com/googlefonts/googlesans/pull/500.

**Pull request closed without merging**
