### PR TITLE
Add midline horizontal ellipsis (U+22EF)

### LINKED ISSUE #101: Add midline horizontal ellipsis (U+22EF)
Similar to #99, a customer team requests an additional glyph:

> “...” default is bottom alignment.  
> We use “...” in tabular view , similar to “--”:  
> “-- = no data  
> “    “ = happening in between two time spots.
>
> Screen Shot 2020-10-15 at 3 49 01 PM

@chrissimpkins mentioned that 

> Google Sans / Google Sans Text does include an ellipsis (`U+2026`). This should be positioned on the baseline. It sounds like you may require a new midline horizontal ellipsis (`U+22EF`) to achieve this.

I agree, `U+22EF` should be added.

### PR DESCRIPTION
**Pull request by chrissimpkins**
Closes #101

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Distributed files to product team for review.

**Comment by chrissimpkins** [comment]
@belluzj ok to merge this before the Tamil is merged or is it easier to wait?

**Comment by belluzj** [comment]
It's fine with me, I'll rebase once it's merged. I'm working on top of the Thai to merge the Tamil, and will rebase to be on top of main once the Thai is merged too.

**Comment by chrissimpkins** [comment]
Thanks Jany.  Rebased on the Thai merge into main at commit https://github.com/googlefonts/googlesans/pull/371/commits/4cac0d0a745ca24766394caed0c385986239e7d0

I'll merge this once the CI tests pass

**Pull request merged**
