### PR TITLE
v3.003: Cyrillic update merge

### LINKED ISSUE #86: Delete RMX Scaler and Robofont user data elements from source files
MergeGlyphs creates a lot of clutter in the diffs because of the `userdata` field that was useful for development. I suggest removing it from production sources via 

`del font.userData[RMXScaler]` https://docu.glyphsapp.com/#GSFont.userData

Screenshot 2020-09-10 at 14 20 40

_Originally posted by @alexeiva in https://github.com/googlefonts/googlesans/pull/85#issuecomment-690216692_

We will need to investigate removal of the extra metadata that this tool publishes to the sources.

### PR DESCRIPTION
**Pull request by chrissimpkins**
Based on v3.002 work as of https://github.com/googlefonts/googlesans/commit/07c8d6442a30743bbbc02c1d2be651f741685e74

### Roman

```
apostrophemod
tetse-cy.sc
```

### Italic

```
apostrophemod
tetse-cy.sc
ge-cy.loclSRB
gje-cy.loclMKD
```

Adds final refinements:

Ustrait-cy renamed to Ustraight-cy (misspelled name in Glyphs App lists), updated features
Updated kerning for Cyrillic small caps. (Previously they relied on UC classes)
in Italics added new glyph gje-cy.loclMKD and updated language MKD definition:

```
script cyrl;
language SRB;
sub be-cy by be-cy.loclSRB;
sub de-cy by de-cy.loclSRB;
sub pe-cy by pe-cy.loclSRB;
sub te-cy by te-cy.loclSRB;
sub sha-cy by sha-cy.loclSRB;
language MKD;
sub ge-cy by ge-cy.loclMKD;
sub gje-cy by gje-cy.loclMKD;
sub be-cy by be-cy.loclSRB;
sub de-cy by de-cy.loclSRB;
sub pe-cy by pe-cy.loclSRB;
sub te-cy by te-cy.loclSRB;
sub sha-cy by sha-cy.loclSRB;
```

---

TODO:

- [x] merge apostrophemod Roman and Italics
- [x] merge tetse-cy.sc Roman and Italics
- [x] merge ge-cy.loclSRB, Italics only
- [x] merge gje-cy.loclMKD, Italics only
- [x] rename Ustrait-cy to Ustraight-cy + update features with new spelling (blocked on feedback from Alexei)
- [x] update kerning for [Uu]straight-cy* glyph name changes (requires above item to be addressed)
- [x] update kerning for Cyrillic, Roman
- [x] update kerning for Cyrillic, Italic
- [x] update SS08 feature code to remove Bulgarian locale definition
- [x] merge edited *-cy glyph outlines
- [x] diagnose / fix broken build as of commit https://github.com/googlefonts/googlesans/pull/82/commits/1bc66ea622bf791d984a6966f2422bc825c9dd05 (follows merge of updated Cyrillic outlines)
- [x] update fontbakery character set expected values with new glyph additions / order
- [x] Alexei Vanyashin review and approval for merge as new production release of Cyrillic set
- [x] bump version number to v3.003
- [x] merge v3.002 (including Hebrew script) updates in #76 
- [ ] merge this branch to master 
- [ ] prep v3.003 release
- [ ] merge changelog updates (#91)

--- 

Closes #86

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@alexeiva Will you please confirm the Ustrait-cy -> Ustraight-cy naming changes that are to take place in your updates?

I am seeing the following in the upstream sources:

- Ustrait-cy
- Ustraitstroke-cy
- ustrait-cy
- ustraitstroke-cy
- ustrait-cy.sc
- ustraitstroke-cy.sc

and the following in your updated sources:

- Ustraightstroke-cy
- ustraight-cy
- ustraightstroke-cy
- ustraight-cy.sc
- ustraightstroke-cy.sc

There does not appear to be a Ustraight-cy (note modified name from Ustrait-cy) in your updates?

**Comment by chrissimpkins** [comment]
Build breaks after the merge of updated Cyrillic outlines in Alexei's sources with the following error message:

```
INFO:fontmake.font_project:Interpolating master UFOs from designspace
fontmake: Error: In 'GoogleSans/GoogleSans.glyphs' -> '../build/GoogleSans/master_ufo/GoogleSans.designspace': Generating fonts from Designspace failed: Too many offcurves defined for curve.
```

Build CI run: https://github.com/googlefonts/googlesans/pull/82/checks?check_run_id=1073645175

**Comment by alexeiva** [comment]
> @alexeiva Will you please confirm the Ustrait-cy -> Ustraight-cy naming changes that are to take place in your updates?

It looks like `Ustraight-cy` was missing in my sources in Roman.

**Comment by alexeiva** [comment]
> Build breaks after the merge of updated Cyrillic outlines in Alexei's sources with the following error message:
> 
> ```
> INFO:fontmake.font_project:Interpolating master UFOs from designspace
> fontmake: Error: In 'GoogleSans/GoogleSans.glyphs' -> '../build/GoogleSans/master_ufo/GoogleSans.designspace': Generating fonts from Designspace failed: Too many offcurves defined for curve.
> ```
> 
> Build CI run: https://github.com/googlefonts/googlesans/pull/82/checks?check_run_id=1073645175

I am seeing a lot of incompatible and broken outlines in these glyphs from https://github.com/googlefonts/googlesans/pull/82/commits/09463a1f9c938e2453bc830c6a055c11a869b48d

`/Tshe-cy/Dje-cy/Ghemiddlehook-cy/Kahook-cy/Hastroke-cy/be-cy/kahook-cy/de-cy.sc/u-cy.sc/dzhe-cy.sc/lje-cy.sc/tshe-cy.sc/dje-cy.sc/enghe-cy.sc/kahook-cy.sc/hastroke-cy.sc/`

Screenshot 2020-09-07 at 14 12 41

**Comment by chrissimpkins** [comment]
Are all of these glyph outlines updated vs where we were in v3.000?  I am seeing a large number of Cyrillic design changes and this is how those are being merged in with the MergeGlyphs tool.

**Comment by alexeiva** [comment]
> Are all of these glyph outlines updated vs where we were in v3.000? I am seeing a large number of Cyrillic design changes and this is how those are being merged in with the MergeGlyphs tool.

Yes, all of them were updated. Might have been a MergeGlyphs bug?
I reimported these glyphs again via MergeGlyphs in https://github.com/googlefonts/googlesans/pull/84 

Here is a list of glyphs that I reimported. 
Screenshot 2020-09-07 at 16 20 13

**Comment by chrissimpkins** [comment]
OK, got it.  I will revert all of the merged glyphs and only import the ones in the list above.  Thanks Alexei!

**Comment by alexeiva** [comment]
> OK, got it. I will revert all of the merged glyphs and only import the ones in the list above. Thanks Alexei!

yes, that would be optimal.

Here is the list for Roman glyphs:

```
/U-cy/ia-cy/ghemiddlehook-cy/Ii-cy/shcha-cy.sc/dzhe-cy.sc/enghe-cy.sc/u-cy.sc/Kahook-cy/kahook-cy.sc/kahook-cy/Hastroke-cy/hastroke-cy/hastroke-cy.sc/be-cy/Dje-cy/dje-cy.sc/dje-cy/Tshe-cy/tshe-cy.sc/Ghemiddlehook-cy/ghemiddlehook-cy.sc/lje-cy.sc/tetse-cy.sc/eldescender-cy.sc/ii-cy/dzeabkhasian-cy
```

**Comment by chrissimpkins** [comment]
@alexeiva I did not merge the kerning updates for the [Uu]straight*-cy glyphs as part of the kerning merge b/c the new glyph names were not in place at the time.  Were those updated in your PR #84 commits?

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/pull/82/commits/add8fbb43e8cd8a0ffe5c8e7d9ee639d95fc142d updates the fontbakery glyph set definition files for our char set / glyph order checks.  This includes the updates that were included in Alexei's changes for Roman and Italic sources

**Comment by chrissimpkins** [comment]
All CI tests passing as of https://github.com/googlefonts/googlesans/pull/82/commits/add8fbb43e8cd8a0ffe5c8e7d9ee639d95fc142d

**Comment by alexeiva** [comment]
@googlebot I consent.

**Comment by alexeiva** [comment]
> @alexeiva I did not merge the kerning updates for the [Uu]straight*-cy glyphs as part of the kerning merge b/c the new glyph names were not in place at the time. Were those updated in your PR #84 commits?

Yes, `Ustraight-cy` was added to Roman sources, all glyph names are correct now.

**Comment by chrissimpkins** [comment]
> > @alexeiva I did not merge the kerning updates for the [Uu]straight*-cy glyphs as part of the kerning merge b/c the new glyph names were not in place at the time. Were those updated in your PR #84 commits?
> 
> 
> 
> Yes, `Ustraight-cy` was added to Roman sources, all glyph names are correct now. 
> 
> 

Apologies.  The question was if you merged the kerning associated with the ustraight name changes? There were several kerning pairs associated with those names that i did not merge because I hadn't changed the names yet.

**Comment by alexeiva** [comment]
No I didn't merge any kerning

**Comment by alexeiva** [comment]
> > > @alexeiva I did not merge the kerning updates for the [Uu]straight*-cy glyphs as part of the kerning merge b/c the new glyph names were not in place at the time. Were those updated in your PR #84 commits?
> > 
> > 
> > Yes, `Ustraight-cy` was added to Roman sources, all glyph names are correct now.
> 
> Apologies. The question was if you merged the kerning associated with the ustraight name changes? There were several kerning pairs associated with those names that i did not merge because I hadn't changed the names yet.

I have merged in the ustaight-cy kerning now in https://github.com/googlefonts/googlesans/pull/85

**Comment by chrissimpkins** [comment]
> > > > @alexeiva I did not merge the kerning updates for the [Uu]straight*-cy glyphs as part of the kerning merge b/c the new glyph names were not in place at the time. Were those updated in your PR #84 commits?
> > > 
> > > 
> > > Yes, `Ustraight-cy` was added to Roman sources, all glyph names are correct now.
> > 
> > 
> > Apologies. The question was if you merged the kerning associated with the ustraight name changes? There were several kerning pairs associated with those names that i did not merge because I hadn't changed the names yet.
> 
> I have merged in the ustaight-cy kerning now in #85

Thanks Alexei!

Please see https://github.com/googlefonts/googlesans/pull/85#issuecomment-690304384

**Comment by chrissimpkins** [comment]
I went back through this commit by commit and performed the italics "ustrait" -> "ustraight" renaming in Glyphs app.  It looks like this is what you used because I get the same massive source diff with the glyph renaming.  🤷 

Let's assume that this is ok and I will verify with fontdiffenator.

I cherry picked all of your other commits in #85.  We are even with that branch now.  I'll push the updated fontbakery glyph name / order files to fix the CI fails.   This should be coming from the new glyph name updates in the italics builds.

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/pull/82/commits/7aaaad23b4a61035b6f0726113b80b1c3a61b68e updates the fontbakery glyph name/order checks.  It looks like that massive diff that happened on the renaming of the "ustrait" glyphs was due to a large reordering of the glyphs based on review of these files.

**Comment by chrissimpkins** [comment]
CI passes with the updated glyph name / order definition files

**Comment by chrissimpkins** [comment]
@alexeiva Will you please review the sources @ https://github.com/googlefonts/googlesans/pull/82/commits/7aaaad23b4a61035b6f0726113b80b1c3a61b68e and the static and variable font files in the downloadable archives available at this URL:  https://github.com/googlefonts/googlesans/actions/runs/248465150 ?

I believe that we have all of your updates merged at this stage.

**Review by alexeiva — COMMENTED** [review]
fontgoogles showing interpolation issue in `Ҵ tetse-cy.sc`  in Medium Italic and Bold

Screenshot 2020-09-10 at 21 47 10

**Comment by alexeiva** [comment]
`ss08` now functions correctly, but for some reason I don't see it in FontGoggles
Screenshot 2020-09-10 at 21 53 51

**Comment by alexeiva** [comment]
locl feature in Italic:

```
	language SRB ;
	sub uni0431 by uni0431.loclSRB;
	sub uni0434 by uni0434.loclSRB;
	sub uni043F by uni043F.loclSRB;
	sub uni0442 by uni0442.loclSRB;
	sub uni0448 by uni0448.loclSRB;
```

should be (one like added)
```
	language SRB ;
 	sub uni0433 by uni0433.loclMKD; // added
	sub uni0431 by uni0431.loclSRB;
	sub uni0434 by uni0434.loclSRB;
	sub uni043F by uni043F.loclSRB;
	sub uni0442 by uni0442.loclSRB;
	sub uni0448 by uni0448.loclSRB;
```

**Comment by chrissimpkins** [comment]
> fontgoogles showing interpolation issue in `Ҵ tetse-cy.sc` in Medium Italic and Bold
> 
> Screenshot 2020-09-10 at 21 47 10

Should be fixed by 1e29c5dadd5db348670f3d5c33d2c2c49f3a4ee7

It looks like there was a path issue on the regular max opsz master that impacted interpolation.  Glyphs `Paths > Tidy Up Paths` fixes it.

**Comment by chrissimpkins** [comment]
> `ss08` now functions correctly, but for some reason I don't see it in FontGoggles
> Screenshot 2020-09-10 at 21 53 51

By functions correctly, you mean that you are able to access the ss08 feature with a different application but you are not seeing it to test in Font Goggles?

**Comment by chrissimpkins** [comment]
> locl feature in Italic:
> 
> ```
> 	language SRB ;
> 	sub uni0431 by uni0431.loclSRB;
> 	sub uni0434 by uni0434.loclSRB;
> 	sub uni043F by uni043F.loclSRB;
> 	sub uni0442 by uni0442.loclSRB;
> 	sub uni0448 by uni0448.loclSRB;
> ```
> 
> should be (one like added)
> 
> ```
> 	language SRB ;
>  	sub uni0433 by uni0433.loclMKD; // added
> 	sub uni0431 by uni0431.loclSRB;
> 	sub uni0434 by uni0434.loclSRB;
> 	sub uni043F by uni043F.loclSRB;
> 	sub uni0442 by uni0442.loclSRB;
> 	sub uni0448 by uni0448.loclSRB;
> ```

Added in f11907a759e6d4af198809bd7bf2231a7dde2de4

**Comment by chrissimpkins** [comment]
New builds with https://github.com/googlefonts/googlesans/commit/1e29c5dadd5db348670f3d5c33d2c2c49f3a4ee7 and https://github.com/googlefonts/googlesans/commit/f11907a759e6d4af198809bd7bf2231a7dde2de4 changes will be available @ 
 ~~https://github.com/googlefonts/googlesans/actions/runs/248623398~~

https://github.com/googlefonts/googlesans/actions/runs/248628329

**Comment by chrissimpkins** [comment]
Hmmm... I broke something in the build.  Checking

**Comment by chrissimpkins** [comment]
Missing semicolon in the fea code update.  Fixed in https://github.com/googlefonts/googlesans/pull/82/commits/e53e2d773599ca581e703c6b48d5f176d0827499.

New files will be available in https://github.com/googlefonts/googlesans/actions/runs/248628329 instead of the link above

**Comment by chrissimpkins** [comment]
> also MKD should be:
> 
> ```
> language MKD;
> sub ge-cy by ge-cy.loclMKD;
> sub gje-cy by gje-cy.loclMKD;
> sub be-cy by be-cy.loclSRB;
> sub de-cy by de-cy.loclSRB;
> sub pe-cy by pe-cy.loclSRB;
> sub te-cy by te-cy.loclSRB;
> sub sha-cy by sha-cy.loclSRB;
> ```

Regular and Italic or Italic only?

**Comment by alexeiva** [comment]
> By functions correctly, you mean that you are able to access the ss08 feature with a different application but you are not seeing it to test in Font Goggles?

Yes, it works fine in the browser and in Sketch.

**Comment by chrissimpkins** [comment]
> > By functions correctly, you mean that you are able to access the ss08 feature with a different application but you are not seeing it to test in Font Goggles?
> 
> Yes, it works fine in the browser and in Sketch.

Must be a Font Goggles bug? Lang settings appropriate in the application?  Maybe lang needs to be selected to see it for some reason?

**Comment by alexeiva** [comment]
> > also MKD should be:
> > ```
> > language MKD;
> > sub ge-cy by ge-cy.loclMKD;
> > sub gje-cy by gje-cy.loclMKD;
> > sub be-cy by be-cy.loclSRB;
> > sub de-cy by de-cy.loclSRB;
> > sub pe-cy by pe-cy.loclSRB;
> > sub te-cy by te-cy.loclSRB;
> > sub sha-cy by sha-cy.loclSRB;
> > ```
> 
> Regular and Italic or Italic only?

Italic only.

**Comment by chrissimpkins** [comment]
> > > also MKD should be:
> > > ```
> > > language MKD;
> > > sub ge-cy by ge-cy.loclMKD;
> > > sub gje-cy by gje-cy.loclMKD;
> > > sub be-cy by be-cy.loclSRB;
> > > sub de-cy by de-cy.loclSRB;
> > > sub pe-cy by pe-cy.loclSRB;
> > > sub te-cy by te-cy.loclSRB;
> > > sub sha-cy by sha-cy.loclSRB;
> > > ```
> > 
> > 
> > Regular and Italic or Italic only?
> 
> Italic only.

fixed in c4366425c7c825fb4d03ee8ffdaaccaca95463db

**Comment by chrissimpkins** [comment]
Builds as of https://github.com/googlefonts/googlesans/commit/c4366425c7c825fb4d03ee8ffdaaccaca95463db in https://github.com/googlefonts/googlesans/actions/runs/248640351

**Comment by alexeiva** [comment]
> > > By functions correctly, you mean that you are able to access the ss08 feature with a different application but you are not seeing it to test in Font Goggles?
> > 
> > 
> > Yes, it works fine in the browser and in Sketch.
> 
> Must be a Font Goggles bug? Lang settings appropriate in the application? Maybe lang needs to be selected to see it for some reason?

I guess Font Goggles does not see it because of `script cyrl;` in the top. Tried changing lang setting to no avail.

**Comment by alexeiva** [comment]
> Builds as of [c436642](https://github.com/googlefonts/googlesans/commit/c4366425c7c825fb4d03ee8ffdaaccaca95463db) in https://github.com/googlefonts/googlesans/actions/runs/248640351

These builds look good now

**Comment by chrissimpkins** [comment]
> > Builds as of [c436642](https://github.com/googlefonts/googlesans/commit/c4366425c7c825fb4d03ee8ffdaaccaca95463db) in https://github.com/googlefonts/googlesans/actions/runs/248640351
> 
> These builds look good now

Excellent!  I'll have a look later today and will plan to base the Georgian updates on this commit if I don't come up with any issues.  Thanks Alexei!

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/pull/82/commits/e9342ac8748de0d16de0d2b1ada49ba8db8bc0ca updates italic glyph set lists for fontbakery checks with U+0453.loclMKD and CI is passing again

**Comment by chrissimpkins** [comment]
https://wakamaifondue.com/ is a good testing site if you are not aware of it.  `ss08` appears to be working there

Cyrillic-locl

**Comment by chrissimpkins** [comment]
rebased on master at https://github.com/googlefonts/googlesans/commit/ede2d5b96a4e447c65359d53fedd76dbbf8882b1.  This addresses the Makefile merge conflict that arose following the v3.002 release updates in the master branch

**Comment by chrissimpkins** [comment]
Changelog for v3.003 prepped in #91

**Comment by chrissimpkins** [comment]
Updated all Python build dependencies as part of this release work

**Comment by chrissimpkins** [comment]
v3.003 release changes are gtg

Merging to master

**Comment by chrissimpkins** [comment]
@alexeiva I prepared the release with your updates today https://github.com/googlefonts/googlesans/releases/tag/v3.003

Thank you very much for all of your work!

**Pull request merged**
