### PR TITLE
Fix graded width of various Greek polytonic glyphs

### PR DESCRIPTION
**Pull request by madig**
I ran a script over the sources that simply set the GRAD0 width on the -50 and 200 master Polytonic Greek glyphs.

---

### TODO

- [x] Irene review of the auto-updated designs
- [x] remove copied cPython source and squash before we merge this
- [x] document that the new Python script requires Py3.9+

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@irenevl Nikolaus's edits are in this branch

**Comment by belluzj** [comment]
I pushed again, using the LSB to do the adjustments this time. I also pushed the script that used.

<details>
<summary>Script output:</summary>
```
$ python scripts/one-off/fix-greek-poly-widths.py

GoogleSans-opsz17-wght380-GRAD0.ufo - fixed glyphs:
    Alphadasia
    Alphadasiaperispomeni
    Alphadasiaperispomeniprosgegrammeni
    Alphadasiaperispomeniprosgegrammeni.ad
    Alphadasiaprosgegrammeni
    Alphadasiaprosgegrammeni.ad
    Alphaoxia
    Alphapsili
    Alphapsiliperispomeni
    Alphapsiliperispomeniprosgegrammeni
    Alphapsiliperispomeniprosgegrammeni.ad
    Alphapsiliprosgegrammeni
    Alphapsiliprosgegrammeni.ad
    Alphatonos
    Alphavaria
    Epsilonoxia
    Epsilontonos
    Epsilonvaria
    Etadasiaperispomeni
    Etadasiaperispomeniprosgegrammeni
    Etadasiaperispomeniprosgegrammeni.ad
    Etaoxia
    Etaprosgegrammeni
    Etapsiliperispomeni
    Etapsiliperispomeniprosgegrammeni
    Etapsiliperispomeniprosgegrammeni.ad
    Etatonos
    Etavaria
    Iotadasiaperispomeni
    Iotaoxia
    Iotapsiliperispomeni
    Iotatonos
    Iotavaria
    Omegadasiaperispomeni
    Omegadasiaperispomeniprosgegrammeni
    Omegadasiaperispomeniprosgegrammeni.ad
    Omegaoxia
    Omegapsiliperispomeni
    Omegapsiliperispomeniprosgegrammeni
    Omegapsiliperispomeniprosgegrammeni.ad
    Omegatonos
    Omegavaria
    Omicronoxia
    Omicrontonos
    Omicronvaria
    Upsilondasiaperispomeni
    Upsilonoxia
    Upsilontonos
    Upsilonvaria
GoogleSans-opsz17-wght380-GRAD0.ufo - NOT fixed glyphs:
    semicolon.loclARM

GoogleSans-opsz18-wght380-GRAD0.ufo - fixed glyphs:
    Alphadasia
    Alphadasiaperispomeni
    Alphadasiaperispomeniprosgegrammeni
    Alphadasiaperispomeniprosgegrammeni.ad
    Alphadasiaprosgegrammeni
    Alphadasiaprosgegrammeni.ad
    Alphaoxia
    Alphapsili
    Alphapsiliperispomeni
    Alphapsiliperispomeniprosgegrammeni
    Alphapsiliperispomeniprosgegrammeni.ad
    Alphapsiliprosgegrammeni
    Alphapsiliprosgegrammeni.ad
    Alphatonos
    Alphavaria
    Epsilonoxia
    Epsilontonos
    Epsilonvaria
    Etadasiaperispomeni
    Etadasiaperispomeniprosgegrammeni
    Etadasiaperispomeniprosgegrammeni.ad
    Etaoxia
    Etaprosgegrammeni
    Etapsiliperispomeni
    Etapsiliperispomeniprosgegrammeni
    Etapsiliperispomeniprosgegrammeni.ad
    Etatonos
    Etavaria
    Iotadasiaperispomeni
    Iotaoxia
    Iotapsiliperispomeni
    Iotatonos
    Iotavaria
    Omegadasiaperispomeni
    Omegadasiaperispomeniprosgegrammeni
    Omegadasiaperispomeniprosgegrammeni.ad
    Omegaoxia
    Omegapsiliperispomeni
    Omegapsiliperispomeniprosgegrammeni
    Omegapsiliperispomeniprosgegrammeni.ad
    Omegatonos
    Omegavaria
    Omicronoxia
    Omicrontonos
    Omicronvaria
    Upsilondasiaperispomeni
    Upsilonoxia
    Upsilontonos
    Upsilonvaria
GoogleSans-opsz18-wght380-GRAD0.ufo - NOT fixed glyphs:
    semicolon.loclARM

GoogleSansItalic-opsz17-wght380-GRAD0.ufo - fixed glyphs:
    Alphadasia
    Alphadasiaoxia
    Alphadasiaoxiaprosgegrammeni
    Alphadasiaoxiaprosgegrammeni.ad
    Alphadasiaperispomeni
    Alphadasiaperispomeniprosgegrammeni
    Alphadasiaperispomeniprosgegrammeni.ad
    Alphadasiaprosgegrammeni
    Alphadasiaprosgegrammeni.ad
    Alphadasiavaria
    Alphadasiavariaprosgegrammeni
    Alphadasiavariaprosgegrammeni.ad
    Alphaoxia
    Alphapsili
    Alphapsilioxia
    Alphapsilioxiaprosgegrammeni
    Alphapsilioxiaprosgegrammeni.ad
    Alphapsiliperispomeni
    Alphapsiliperispomeniprosgegrammeni
    Alphapsiliperispomeniprosgegrammeni.ad
    Alphapsiliprosgegrammeni
    Alphapsiliprosgegrammeni.ad
    Alphapsilivaria
    Alphapsilivariaprosgegrammeni
    Alphapsilivariaprosgegrammeni.ad
    Alphatonos
    Alphavaria
    Epsilondasia
    Epsilondasiaoxia
    Epsilondasiavaria
    Epsilonoxia
    Epsilonpsili
    Epsilonpsilioxia
    Epsilonpsilivaria
    Epsilontonos
    Epsilonvaria
    Etadasia
    Etadasiaoxia
    Etadasiaoxiaprosgegrammeni
    Etadasiaoxiaprosgegrammeni.ad
    Etadasiaperispomeni
    Etadasiaperispomeniprosgegrammeni
    Etadasiaperispomeniprosgegrammeni.ad
    Etadasiaprosgegrammeni
    Etadasiaprosgegrammeni.ad
    Etadasiavaria
    Etadasiavariaprosgegrammeni
    Etadasiavariaprosgegrammeni.ad
    Etaoxia
    Etaprosgegrammeni
    Etapsili
    Etapsilioxia
    Etapsilioxiaprosgegrammeni
    Etapsilioxiaprosgegrammeni.ad
    Etapsiliperispomeni
    Etapsiliperispomeniprosgegrammeni
    Etapsiliperispomeniprosgegrammeni.ad
    Etapsiliprosgegrammeni
    Etapsiliprosgegrammeni.ad
    Etapsilivaria
    Etapsilivariaprosgegrammeni
    Etapsilivariaprosgegrammeni.ad
    Etatonos
    Etavaria
    Iotadasia
    Iotadasiaoxia
    Iotadasiaperispomeni
    Iotadasiavaria
    Iotaoxia
    Iotapsili
    Iotapsilioxia
    Iotapsiliperispomeni
    Iotapsilivaria
    Iotatonos
    Iotavaria
    Omegadasia
    Omegadasiaoxia
    Omegadasiaoxiaprosgegrammeni
    Omegadasiaoxiaprosgegrammeni.ad
    Omegadasiaperispomeni
    Omegadasiaperispomeniprosgegrammeni
    Omegadasiaperispomeniprosgegrammeni.ad
    Omegadasiaprosgegrammeni
    Omegadasiaprosgegrammeni.ad
    Omegadasiavaria
    Omegadasiavariaprosgegrammeni
    Omegadasiavariaprosgegrammeni.ad
    Omegaoxia
    Omegapsili
    Omegapsilioxia
    Omegapsilioxiaprosgegrammeni
    Omegapsilioxiaprosgegrammeni.ad
    Omegapsiliperispomeni
    Omegapsiliperispomeniprosgegrammeni
    Omegapsiliperispomeniprosgegrammeni.ad
    Omegapsiliprosgegrammeni
    Omegapsiliprosgegrammeni.ad
    Omegapsilivaria
    Omegapsilivariaprosgegrammeni
    Omegapsilivariaprosgegrammeni.ad
    Omegatonos
    Omegavaria
    Omicrondasia
    Omicrondasiaoxia
    Omicrondasiavaria
    Omicronoxia
    Omicronpsili
    Omicronpsilioxia
    Omicronpsilivaria
    Omicrontonos
    Omicronvaria
    Rhodasia
    Upsilondasia
    Upsilondasiaoxia
    Upsilondasiaperispomeni
    Upsilondasiavaria
    Upsilonoxia
    Upsilontonos
    Upsilonvaria
GoogleSansItalic-opsz17-wght380-GRAD0.ufo - NOT fixed glyphs:
    baht.tf
    semicolon.loclARM

GoogleSansItalic-opsz18-wght380-GRAD0.ufo - fixed glyphs:
    Alphadasia
    Alphadasiaoxia
    Alphadasiaoxiaprosgegrammeni
    Alphadasiaoxiaprosgegrammeni.ad
    Alphadasiaperispomeni
    Alphadasiaperispomeniprosgegrammeni
    Alphadasiaperispomeniprosgegrammeni.ad
    Alphadasiaprosgegrammeni
    Alphadasiaprosgegrammeni.ad
    Alphadasiavaria
    Alphadasiavariaprosgegrammeni
    Alphadasiavariaprosgegrammeni.ad
    Alphaoxia
    Alphapsili
    Alphapsilioxia
    Alphapsilioxiaprosgegrammeni
    Alphapsilioxiaprosgegrammeni.ad
    Alphapsiliperispomeni
    Alphapsiliperispomeniprosgegrammeni
    Alphapsiliperispomeniprosgegrammeni.ad
    Alphapsiliprosgegrammeni
    Alphapsiliprosgegrammeni.ad
    Alphapsilivaria
    Alphapsilivariaprosgegrammeni
    Alphapsilivariaprosgegrammeni.ad
    Alphatonos
    Alphavaria
    Epsilondasia
    Epsilondasiaoxia
    Epsilondasiavaria
    Epsilonoxia
    Epsilonpsili
    Epsilonpsilioxia
    Epsilonpsilivaria
    Epsilontonos
    Epsilonvaria
    Etadasia
    Etadasiaoxia
    Etadasiaoxiaprosgegrammeni
    Etadasiaoxiaprosgegrammeni.ad
    Etadasiaperispomeni
    Etadasiaperispomeniprosgegrammeni
    Etadasiaperispomeniprosgegrammeni.ad
    Etadasiaprosgegrammeni
    Etadasiaprosgegrammeni.ad
    Etadasiavaria
    Etadasiavariaprosgegrammeni
    Etadasiavariaprosgegrammeni.ad
    Etaoxia
    Etaprosgegrammeni
    Etapsili
    Etapsilioxia
    Etapsilioxiaprosgegrammeni
    Etapsilioxiaprosgegrammeni.ad
    Etapsiliperispomeni
    Etapsiliperispomeniprosgegrammeni
    Etapsiliperispomeniprosgegrammeni.ad
    Etapsiliprosgegrammeni
    Etapsiliprosgegrammeni.ad
    Etapsilivaria
    Etapsilivariaprosgegrammeni
    Etapsilivariaprosgegrammeni.ad
    Etatonos
    Etavaria
    Iotadasia
    Iotadasiaoxia
    Iotadasiaperispomeni
    Iotadasiavaria
    Iotaoxia
    Iotapsili
    Iotapsilioxia
    Iotapsiliperispomeni
    Iotapsilivaria
    Iotatonos
    Iotavaria
    Omegadasia
    Omegadasiaoxia
    Omegadasiaoxiaprosgegrammeni
    Omegadasiaoxiaprosgegrammeni.ad
    Omegadasiaperispomeni
    Omegadasiaperispomeniprosgegrammeni
    Omegadasiaperispomeniprosgegrammeni.ad
    Omegadasiaprosgegrammeni
    Omegadasiaprosgegrammeni.ad
    Omegadasiavaria
    Omegadasiavariaprosgegrammeni
    Omegadasiavariaprosgegrammeni.ad
    Omegaoxia
    Omegapsili
    Omegapsilioxia
    Omegapsilioxiaprosgegrammeni
    Omegapsilioxiaprosgegrammeni.ad
    Omegapsiliperispomeni
    Omegapsiliperispomeniprosgegrammeni
    Omegapsiliperispomeniprosgegrammeni.ad
    Omegapsiliprosgegrammeni
    Omegapsiliprosgegrammeni.ad
    Omegapsilivaria
    Omegapsilivariaprosgegrammeni
    Omegapsilivariaprosgegrammeni.ad
    Omegatonos
    Omegavaria
    Omicrondasia
    Omicrondasiaoxia
    Omicrondasiavaria
    Omicronoxia
    Omicronpsili
    Omicronpsilioxia
    Omicronpsilivaria
    Omicrontonos
    Omicronvaria
    Rhodasia
    Upsilondasia
    Upsilondasiaoxia
    Upsilondasiaperispomeni
    Upsilondasiavaria
    Upsilonoxia
    Upsilontonos
    Upsilonvaria
GoogleSansItalic-opsz18-wght380-GRAD0.ufo - NOT fixed glyphs:
    Men_Ech-arm.liga
    baht.tf
    men_xeh-arm.liga.sc
    semicolon.loclARM
```
</details>

**Comment by chrissimpkins** [comment]
@belluzj Jany, is this ready for Irene to have a look?

**Comment by belluzj** [comment]
Yes it is!

**Comment by chrissimpkins** [comment]
added new todo's that Jany and I discussed today to the OP

**Comment by chrissimpkins** [comment]
@irenevl Do you mind reviewing the automated updates that we made in the following variable font archive when you have a chance?

https://github.com/googlefonts/googlesans/suites/4853239384/artifacts/137890614

This should address the issue in https://github.com/googlefonts/googlesans/issues/421

Ty!

**Comment by irenevlachou** [comment]
sure! I'll have a look first thing tomorrow morning. Thanks for the update!

**Comment by irenevlachou** [comment]
Hi @chrissimpkins yep all is good now! thank you for the update!

**Comment by chrissimpkins** [comment]
> Hi @chrissimpkins yep all is good now! thank you for the update!

Excellent work @madig and @belluzj!

Thanks Irene!

**Comment by chrissimpkins** [comment]
Will squash this prior to merge to remove all history remnants of the cPy PFL licensed sources.  Should otherwise be gtg.

**Comment by chrissimpkins** [comment]
OK if I squash (to eliminate all traces of the cPython std lib source in the git history) and merge?

**Comment by madig** [comment]
I think so.

**Comment by chrissimpkins** [comment]
>> OK if I squash (to eliminate all traces of the cPython std lib source in the git history) and merge?

> I think so.

Ty!

Squashed into https://github.com/googlefonts/googlesans/pull/425/commits/07f9d4fda89f5f5f9cacb8e08f1ff1c739e6927c

**Comment by chrissimpkins** [comment]
Moving this up to the v7.000 release (from v8.000).

Thanks @madig, @belluzj, & @irenevl!

**Pull request merged**
