### PR TITLE
Latin & Cyrillic small fixes

### LINKED ISSUE #526: Anchor usage in /t_f
## Issue

During the Lao Loopless QA, Hanna observed the following arrangement in our Latin sources:

> 1) Spotted a discrepancy in anchor placement in the 
		regular Display Upright vs Italic
> 2) Does it require all these anchors? Can it get simplified?

> | Upright | Italic |
> | - | - |
> | image | image |

## Questions

- [ ] Do we want to change the Latin sources here?
- [ ] Do we want to filter the anchors that we propagate to the Loopless fonts?

@chrissimpkins @MariannaPaszkowska @belluzj I would be interested to hear your thoughts here : )

### PR DESCRIPTION
**Pull request by RickyDaMa**
- (CYR - UPR and ITAL)  Iu and iu glyphs compatibility and refreshed metrics
- (UPR & ITAL) fixed: Fivethousand-roman, Tenthousand-roman, zeropercent, percentbar, percent, pertenthousand, perthousand,
- (CYR - UPR and ITAL) Updated point placement of Iu and iu glyphs
- (ITAL): fixed compatibility of non-Latin glyphs
- (UPR): fixed compatibility of non-Latin glyphs
- (ITAL) updated latin ligature anchors
- (UPR) updated latin ligature anchors
- t_f anchor update
- Ignore (ital): glyphs roundtrip diffs
- Ligatures fix (Ital): component order
- Ligatures fix: component order

Fixes: https://github.com/googlefonts/googlesans/issues/526 https://github.com/googlefonts/googlesans/issues/591 https://github.com/googlefonts/googlesans/issues/607 https://github.com/googlefonts/googlesans/issues/606

### CODE REVIEW

**Comment by RickyDaMa** [comment]
ERRORs raised by fontbakery will be fixed by https://github.com/fonttools/fontbakery/pull/4357

With the above fontbakery patch applied, the interpolation check passes on this PR

**Comment by RickyDaMa** [comment]
Fix has now been merged, just need it to be released for us to have the pipeline passed

**Comment by MariannaPaszkowska** [comment]
@belluzj @RickyDaMa many thanks for the updates. I noticed some unexpected differences in Italic font: some glyphs have spacing differences (Gurmukhi) and ethiopic Hi has a regression. Please review: Screenshot 2023-12-12 at 4 42 58 PM
Screenshot 2023-12-12 at 4 42 50 PM
Screenshot 2023-12-12 at 4 42 11 PM
Screenshot 2023-12-12 at 4 41 46 PM

**Comment by belluzj** [comment]
@MariannaPaszkowska I reverted changes to the Ethiopic Hi that got merged accidentally, as you spotted.

However I couldn't see the other issues in the Gurmukhi when using diffenator2 against the main branch, so I'm wondering if you could double check on your end that you've compared against the latest Italic from main, that would be great. Here is what I see now:

image
image
image
image

**Comment by MariannaPaszkowska** [comment]
Ok, thanks! Did you run diff2 with the flag: "-s masters"?

**Comment by belluzj** [comment]
No I didn't use that flag, I'll run again

**Comment by belluzj** [comment]
I ran it again and still don't have the Gurmukhi diffs

**Comment by MariannaPaszkowska** [comment]
I have reviewed it again and I cannot find any more regressions. Many thanks!

**Pull request merged**
