### PR TITLE
Import Cyrillic fixes

### LINKED ISSUE #456: CYRILLIC merge: GRAD masters cleanup
Cyrillic GRAD masters update. 
I cleaned up contour/interpolation issues in Cyrillic GRAD masters, 
and also adjusted `C`, `c`, `c.sc` glyphs, since they are required for Cyrillic components. 

My .glyphs files don't convert to UFOs: 
(Removing background didn't help.)

```
Traceback (most recent call last):
  File "/Users/alexeiva/github.com/googlefonts/googlesans/scripts/gs-glyphs2ufo.py", line 76, in <module>
    normalize.scrub_designspace(designspace, ROOT_DIR)
  File "/Users/alexeiva/github.com/googlefonts/googlesans/scripts/internal/normalize.py", line 40, in scrub_designspace
    ot_categories = infer_opentype_categories(designspace.default.font)
  File "/Users/alexeiva/github.com/googlefonts/googlesans/scripts/internal/normalize.py", line 301, in infer_opentype_categories
    pf(font=ufo_copy)
  File "/Users/alexeiva/virtualenvs/gftools/lib/python3.9/site-packages/ufo2ft/filters/flattenComponents.py", line 12, in __call__
    if super().__call__(font, glyphSet):
  File "/Users/alexeiva/virtualenvs/gftools/lib/python3.9/site-packages/ufo2ft/filters/base.py", line 195, in __call__
    if include(glyph) and filter_(glyph):
  File "/Users/alexeiva/virtualenvs/gftools/lib/python3.9/site-packages/ufo2ft/filters/flattenComponents.py", line 24, in filter
    flattened_tuples = _flattenComponent(self.context.glyphSet, comp)
  File "/Users/alexeiva/virtualenvs/gftools/lib/python3.9/site-packages/ufo2ft/filters/flattenComponents.py", line 46, in _flattenComponent
    flattened_components = _flattenComponent(glyphSet, nested)
  File "/Users/alexeiva/virtualenvs/gftools/lib/python3.9/site-packages/ufo2ft/filters/flattenComponents.py", line 46, in _flattenComponent
    flattened_components = _flattenComponent(glyphSet, nested)
  File "/Users/alexeiva/virtualenvs/gftools/lib/python3.9/site-packages/ufo2ft/filters/flattenComponents.py", line 46, in _flattenComponent
    flattened_components = _flattenComponent(glyphSet, nested)
[Google-Sans-Cyrillic.zip](https://github.com/googlefonts/googlesans/files/8098955/Google-Sans-Cyrillic.zip)

  [Previous line repeated 987 more times]
  File "/Users/alexeiva/virtualenvs/gftools/lib/python3.9/site-packages/ufo2ft/filters/flattenComponents.py", line 40, in _flattenComponent
    if not glyph.components or len(glyph) > 0:
  File "/Users/alexeiva/virtualenvs/gftools/lib/python3.9/site-packages/ufoLib2/objects/glyph.py", line 86, in __len__
    return len(self.contours)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Notes on the Cyrillic edits here: https://github.com/googlefonts/googlesans/issues/449

### PR DESCRIPTION
**Pull request by madig**
This imports https://github.com/googlefonts/googlesans/issues/456#issuecomment-1067099090 without the `*strait*` glyphs that are duplicates of the `*straight*` glyphs and which we deleted some time ago.

Closes https://github.com/googlefonts/googlesans/issues/456, https://github.com/googlefonts/googlesans/issues/399

### CODE REVIEW

**Comment by belluzj** [comment]
@MariannaPaszkowska we would also like to merge this before we start looking at the spacing fixes for the Cyrillic. Thanks in advance for your review!

**Comment by MariannaPaszkowska** [comment]
Hi, I see a lot of diffs in the build from this branch that are beyond Cyrillic, are those intentional? Are they a consequence of the #516 ? 

Screenshot 2023-10-23 at 5 48 12 PM

Screenshot 2023-10-23 at 5 48 47 PM

Screenshot 2023-10-23 at 5 48 36 PM

**Comment by Hoolean** [comment]
Hi Marianna! We will investigate :+1:

**Comment by belluzj** [comment]
Hello @MariannaPaszkowska , I think I've fixed the fontbakery issue now. Next for us to investigate here are the Hibizcus diffs from your screenshot. Do you have more information about what Hibizcus is finding as differences in the red glyphs? We'll also have a go running Hibizcus tomorrow to see if we have the same diffs

**Comment by MariannaPaszkowska** [comment]
@belluzj I'm seeing less diffs in Hibizcus, but still some unexpected ones:
Screenshot 2023-10-25 at 6 37 42 PM
I'm looking onto it.

**Comment by belluzj** [comment]
OK thanks, I'll have a look at Hibizcus tomorrow to try and explain these.

**Comment by belluzj** [comment]
@MariannaPaszkowska ~~I ran Hibizcus on my side and I don't even see the expected diffs... I'm thinking that Hibizcus is picking up differences that don't exist~~ I was dismissive of the results a bit too fast... Hibizcus had stopped mid-way and not gone through all the glyphs, doing a second run I saw more diffs. However, upon inspecting the glyphs in fullscreen, I still couldn't see what was different by eye

**Comment by MariannaPaszkowska** [comment]
Hi all, thank you for your hard work on this PR. 
I reviewed the diffs. Special thanks, @m4rc1e, for your support in making this happen - without improvements to the diffenator2 tool, it would be very challenging to review! 

Here is my report:

- I confirm that this PR fixes issues with the `ђ`, 

- I noticed that the `upturncy` in `Ґ` and `ґ` is still misaligning (it seems ok in .sc character). - are we importing/merging this glyph correctly in this PR?  @belluzj 

Screenshot 2023-10-31 at 7 50 36 PM
  
Screenshot 2023-10-31 at 7 53 51 PM

- I noticed that there are no differences to `C`, `c` and `c.sc`

Reviewed charset: all GS charset and `CcəБГҐДЖЗИКЛПУФЧЦШЏЬЪЉЄЭЯЂѪѴҜҠҤҨҸҼӃӇӘӠӼӾԐԒԨбвгґджзиклмнптфчцшџьъыљњєэюђѫѵҕҝҡҥҩұҵҹҽӄӈәӡӽӿԑԓҍԩ` + `.sc `

cc @chrissimpkins @davelab6

**Comment by chrissimpkins** [comment]
> Special thanks, @m4rc1e, for your support in making this happen - without improvements to the diffenator2 tool, it would be very challenging to review!

Thanks Marc!

**Comment by belluzj** [comment]
Thanks for the review Marianna and for the tool Marc. We'll double-check the import (i.e. is the glyphs mis-aligned in the branch we're importing from or not) and fix the import if that's the issue.

**Comment by MariannaPaszkowska** [comment]
@belluzj I ran more tests (completed this review too now) and finally found the differences in the `C c` and `c.sc` (all good there, small outline refinements ). I also found a new issue with the `ԓ`  glyph in the GRAD -50 (only in the build from this branch, main is ok):  
Screenshot 2023-11-01 at 1 27 02 PM

**Comment by belluzj** [comment]
@MariannaPaszkowska coming back to this PR, I can confirm that the two issues you've spotted are present in the Glyphs files that we imported from (see gifs below, looking at the files [from this zip](https://github.com/googlefonts/googlesans/issues/456#issuecomment-1067099090) in Fontra). Would you like to go back to Alexei for fixes, or would you want a designer from our side to commit to this PR the fixes?

Cyrillic issue 1

Cyrillic issue 2

**Comment by MariannaPaszkowska** [comment]
@belluzj, please arrange for a designer from your team to fix this issue and commit to this PR. Many thanks! We also might need to rebase.

**Comment by belluzj** [comment]
Will do! Thanks

**Comment by RickyDaMa** [comment]
@MariannaPaszkowska Rebased and fix from one of our designers all pushed!

~~(We're aware of the CLA issue and working to fix it)~~ Edit: fixed!

**Comment by MariannaPaszkowska** [comment]
@belluzj  I confirm that the previous issues have been fixed, many thanks! I found one interpolation issue in this build related to Cyrillic:
Screenshot 2023-11-21 at 7 20 13 PM
Can we fix this too?

Here is a full report; the rest of the issues we can address in a separate PR.
[Cyrillic-fixes-int_issues.pdf](https://github.com/googlefonts/googlesans/files/13429309/Cyrillic-fixes-int_issues.pdf)

**Comment by belluzj** [comment]
@MariannaPaszkowska yes sure, I will forward this request to the designers. Thanks!

**Comment by RickyDaMa** [comment]
@MariannaPaszkowska pushed our designer's fixes to the issue you highlighted

**Comment by MariannaPaszkowska** [comment]
Hi @belluzj I noticed that ` ю`  glyph has a new issue: 
Screenshot 2023-12-04 at 6 15 55 PM

Top fonts shown here are from this branch, bottom is the release. It seems like a wrong component order. 

I merged the PR so as not to hold on to the work on kerning, but can we fix this one? Perhaps in a new PR?

**Pull request merged**
