### PR TITLE
Remove r-ligatures

### LINKED ISSUE #528: Remove `r` ligature forms
Creative directors on the project decided to remove all `r` ligature forms.  Let's add this to the v10 release

cc @MariannaPaszkowska

### PR DESCRIPTION
**Pull request by MariannaPaszkowska**
Removed all references to `r` ligatures from `liga` and `dlig` features.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Decided to see what this PR looks like in latest diffenator2. I'm diffing against the v9.0 release

[gs.zip](https://github.com/googlefonts/googlesans/files/9569809/gs.zip)

Screenshot 2022-09-14 at 21 38 01

@MariannaPaszkowska  You've taken out the r ligs as requested in #528 but by doing this we now get different ligatures activated for certain words e.g "Heartfelt" used to give us `H e a r_t f e l t`, we now get `h e a r t_f e l t`. Please ignore this comment if this was intended. I thought I'd just point this out since it may be a side effect we didn't consider

@belluzj @Hoolean @madig Apologies for the lack of communication regarding the diffing tooling. I'm still pushing hard. Wip repo with terrible sketchy code here, https://github.com/m4rc1e/diffenator2. Will transfer the repo to googlefonts once it's better. Please just open up issues for now and I will implement. My usual style is to first sketch terribly, get something to work that everyone is happy with, add tests and then refactor.


@chrissimpkins I still need time to make this faster. It currently takes 15 mins to get through all the available word lists for Google Sans. Also, if there are two versions you'd like me to diff, lmk. I'd also be interested in seein gthe scuba screenshots.

**Comment by MariannaPaszkowska** [comment]
>You've taken out the r ligs as requested in https://github.com/googlefonts/googlesans/issues/528 but by doing this we now get different ligatures activated for certain words e.g "Heartfelt" used to give us `H e a r_t f e l t`, we now get `h e a r t_f e l t`. Please ignore this comment if this was intended. I thought I'd just point this out since it may be a side effect we didn't consider

I love diffenator2! Great catch, thanks, @m4rc1e! This side effect seems logical and makes sense to me, but I'll ensure it's raised and clarified before we move forward.

**Comment by chrissimpkins** [comment]
Diffs that include new default ligs as the r-ligs go away is no problem at all.  There will be diffs but they are desirable ones.  Thanks all!

**Comment by chrissimpkins** [comment]
> Decided to see what this PR looks like in latest diffenator2. I'm diffing against the v9.0 release
> 
> 
> 
> [gs.zip](https://github.com/googlefonts/googlesans/files/9569809/gs.zip)
> 
> 
> 
> Screenshot 2022-09-14 at 21 38 01
> 
> 
> 
> @MariannaPaszkowska  You've taken out the r ligs as requested in #528 but by doing this we now get different ligatures activated for certain words e.g "Heartfelt" used to give us `H e a r_t f e l t`, we now get `h e a r t_f e l t`. Please ignore this comment if this was intended. I thought I'd just point this out since it may be a side effect we didn't consider
> 
> 
> 
> @belluzj @Hoolean @madig Apologies for the lack of communication regarding the diffing tooling. I'm still pushing hard. Wip repo with terrible sketchy code here, https://github.com/m4rc1e/diffenator2. Will transfer the repo to googlefonts once it's better. Please just open up issues for now and I will implement. My usual style is to first sketch terribly, get something to work that everyone is happy with, add tests and then refactor.
> 
> 
> 
> 
> 
> @chrissimpkins I still need time to make this faster. It currently takes 15 mins to get through all the available word lists for Google Sans. Also, if there are two versions you'd like me to diff, lmk. I'd also be interested in seein gthe scuba screenshots.

The tool looks great Marc.  Thank you very much for developing it!

**Comment by chrissimpkins** [comment]
Can we land this around script merges to target v10 later this month @Hoolean?

**Comment by belluzj** [comment]
Hello Chris, yes this is easy to merge because the diff is very small. We're going to do the following:
* check that the ligature glyphs (which are not needed anymore) are dropped from the final fonts thanks to the subsetter
* re-generate shaping tests and glyphset expectations
* check that the pipeline is green the new shaping looks correct
* then it's ready for you to review and merge

**Comment by MariannaPaszkowska** [comment]
@Hoolean Just a reminder to target this too for v10. :)

**Comment by Hoolean** [comment]
Hi @MariannaPaszkowska, I will make sure we have this arranged :)

**Comment by MariannaPaszkowska** [comment]
@Hoolean @belluzj  Any updates on this? Any chance we can make this update happen still this week?

**Comment by belluzj** [comment]
Hello @MariannaPaszkowska , no update yet but it's on our TODO list and we'll make sure to make it happen this week.

**Comment by belluzj** [comment]
@chrissimpkins @MariannaPaszkowska I'll look at the r ligatures tomorrow, and if that sounds good to you, I would rebase the r ligatures on top of the Latin Extension branch, so that I will update the glyphsetdefs and shaping only once, assuming the Latin Extension branch could be merged first before this PR?

Otherwise, I can also base this PR on main, rebase the Latin Extension and update the glyphsetdefs and shaping one last time in the Latin Extension before it's merged.

**Comment by MariannaPaszkowska** [comment]
Ok @belluzj I will rebase this branch on the Latin Extension, thank you. :)

**Comment by belluzj** [comment]
Thanks, and no worries, I'll do it and also do the updates to the glyphsetdef and shaping files while I'm at it. I'll push-force soon to this branch

**Comment by belluzj** [comment]
@MariannaPaszkowska I see that the Google CLA bot is unhappy about the commit from https://github.com/TypeAndCode, is that you? Maybe you need to add that account to the CLA? @chrissimpkins maybe can help with that?

Details here: https://github.com/googlefonts/googlesans/pull/529/checks?check_run_id=8590247326

**Comment by MariannaPaszkowska** [comment]
I closed this PR because I couldn't add CLA to that account. I'll open a new PR. @belluzj

**Comment by belluzj** [comment]
If you want I can help by modifying your commit to use another email for the author? It's possible with git to edit the data of past commits without redoing everything. Let me know if I should do that

**Comment by belluzj** [comment]
https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-a-single-commit

**Comment by MariannaPaszkowska** [comment]
Oh, I didn't know that. Yes, then let's do it like that. Thank you @belluzj

**Comment by belluzj** [comment]
CLA is happy now 👍

**Comment by Hoolean** [comment]
Hello @MariannaPaszkowska, @chrissimpkins! Another PR for you today :tada:

We have *re*-rebased on `latin-extension-dama`, which has sorted out the conflicts, and built to confirm that [the CI is passing with no further warnings](https://github.com/googlefonts/googlesans/actions/runs/3182683294). This branch is now ready for review, and then merging : )

**Comment by MariannaPaszkowska** [comment]
Approved and merged!  🎉 Thanks a lot @Hoolean @m4rc1e @belluzj @chrissimpkins!

**Comment by madig** [comment]
@MariannaPaszkowska just to check, you are aware that this is now lying around in https://github.com/googlefonts/googlesans/pull/517 rather than main?

**Comment by MariannaPaszkowska** [comment]
Thanks for bringing this up! AFAIK This should be based on the main and land in v10. 
CC @chrissimpkins

**Comment by chrissimpkins** [comment]
Thanks @madig!  I didn't catch that we were based on the Latin expansion work.

We should be able to cherry pick the following commits into a new branch based on main and merge to main:

- https://github.com/googlefonts/googlesans/pull/529/commits/2618e4cc58d66845857627377ee567b7d9db5009
- https://github.com/googlefonts/googlesans/pull/529/commits/8554f1973110fdf9be9b57fc5b085146524d75c6

I can take a look into it later today.

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/pull/546

**Pull request merged**
