### PR TITLE
Apply new sidebearings

### LINKED ISSUE #589: Improve the spacing of the `1)` sequence
User report:

> I noticed while typing up a google doc that (1) renders a little weirdly
>
>Details:
>
>OS: OSX
Browser: Chrome
App: docs.google.com
Font Size: 11
Font: "Google Sans Text"
compared with some other common body-text fonts in Google Docs: http://screen/8YGyrcde269H58J
>
>Normally I am used to being able to type out (1) detail one (2) detail two (3) detail three in a list and this is the first time I think I've encountered a font where I've found a number looking this imbalanced.
>
>My specific criticism is about the closing paren ) being too close to the 1. The remaining digits all look great.
>
>I think Roboto will probably always look better by virtue of using a fixed width for numbers but if it's possible to add a little more space between the 1 and the ) in Google Sans Text I think this will look considerably better.

8YGyrcde269H58J

### PR DESCRIPTION
**Pull request by madig**
@chrissimpkins This branch/PR contains the spacing changes done by our designers, used in the presentation you received. Not to be merged now, but so you can see the results.

Fixes https://github.com/googlefonts/googlesans/issues/589

### CODE REVIEW

**Comment by chrissimpkins** [comment]
> @chrissimpkins This branch/PR contains the spacing changes done by our designers, used in the presentation you received. Not to be merged now, but so you can see the results.

Ty!

**Comment by madig** [comment]
@chrissimpkins would you like us to upload the kerning work of our designers now or do you want to go over the slides with Dave first? I don't think there is any hurry right now?

**Comment by chrissimpkins** [comment]
> @chrissimpkins would you like us to upload the kerning work of our designers now or do you want to go over the slides with Dave first? I don't think there is any hurry right now?

I will review the slides with Dave and then we can discuss where things are/if more needs to be done.  No need to spend time on it on your end right now IMO.

**Comment by chrissimpkins** [comment]
@belluzj you can eliminate the google-cla messages by entering `@googlebot I consent.` in a post in these threads.  The CLA doesn't apply to this project but we can't deactivate it...

**Comment by belluzj** [comment]
@chrissimpkins in order to produce a comparison of sentence lengths from the main branch vs from the re-kerned fonts, I have rebased this pull request on top of main and updated it with the kerning changes as well. I didn't manage to get to producing the sentence length comparison this week but Nikolaus will have a look next week.

BTW this process of importing the sidebearing and kerning changes into main is done with a script, so we should be able to rebase this easily when it's the right time to merge.

**Comment by belluzj** [comment]
@googlebot I consent

**Comment by chrissimpkins** [comment]
> @chrissimpkins in order to produce a comparison of sentence lengths from the main branch vs from the re-kerned fonts, I have rebased this pull request on top of main and updated it with the kerning changes as well. I didn't manage to get to producing the sentence length comparison this week but Nikolaus will have a look next week.
> 
> BTW this process of importing the sidebearing and kerning changes into main is done with a script, so we should be able to rebase this easily when it's the right time to merge.

Sgtm and no problem on the schedule.  Thanks Jany!

**Comment by madig** [comment]
Here's some new statistics for 899da6e:

```
 Regular (opsz=18, wght=400, GRAD=0):
  Word length diffs, min and max: -283 (-15.6%), 121 (7.6%)
  Word length diffs, 1., 10., 50., 90., 99. percentile: -2.4, -1.2, -0.3, 0.1, 0.6%
  Sentence length diffs, min and max: -4856 (-2.4%), 510 (1.5%)
  Sentence length diffs, 1., 10., 50., 90., 99. percentile: -1.1, -0.7, -0.3, 0.0, 0.2%

 Bold (opsz=18, wght=700, GRAD=0):
  Word length diffs, min and max: -290 (-12.4%), 112 (6.7%)
  Word length diffs, 1., 10., 50., 90., 99. percentile: -2.4, -1.3, -0.4, 0.0, 0.4%
  Sentence length diffs, min and max: -5344 (-2.5%), 429 (1.4%)
  Sentence length diffs, 1., 10., 50., 90., 99. percentile: -1.2, -0.8, -0.4, 0.0, 0.1%


 Text Regular (opsz=17, wght=400, GRAD=0):
  Word length diffs, min and max: -230 (-12.9%), 251 (9.9%)
  Word length diffs, 1., 10., 50., 90., 99. percentile: -1.8, -0.8, -0.2, 0.1, 0.5%
  Sentence length diffs, min and max: -2303 (-2.1%), 2029 (1.6%)
  Sentence length diffs, 1., 10., 50., 90., 99. percentile: -0.8, -0.5, -0.2, 0.0, 0.2%

 Text Bold (opsz=17, wght=700, GRAD=0):
  Word length diffs, min and max: -262 (-12.2%), 237 (8.4%)
  Word length diffs, 1., 10., 50., 90., 99. percentile: -1.8, -0.9, -0.2, 0.1, 0.6%
  Sentence length diffs, min and max: -3437 (-2.0%), 1775 (1.4%)
  Sentence length diffs, 1., 10., 50., 90., 99. percentile: -0.9, -0.5, -0.2, 0.0, 0.2%
```

Overall, everything is a bit tighter, with most of the action happening between -2.4% to +0.6% for words and -1.2% to +0.2% for sentences of the AOSP and UDHR corpus.

I had a look at the top 50 biggest changes in words in either direction and cross-checked with our designer.

Width increases:

|word        |Text Regular|
|------------|------------|
|kʼé         |9.853420195 |
|tʼéí        |9.346504559 |
|jeʼe        |8.322324967 |
|leʼé        |8.179419525 |
|kʼoʼolol,   |7.619914997 |
|weʼetʼel    |7.157894737 |
|Vĩ          |7.083825266 |
|tʼóó        |7.004120071 |
|átʼé        |6.985294118 |
|haʼe        |6.742179072 |
|kʼeh        |6.648199446 |
|firʼe       |6.647058824 |
|ñeʼẽ        |6.408185245 |
|teʼej       |6.246634356 |
|biʼoh       |6.049325268 |
|ájítʼe      |6.022944551 |
|ájítʼé      |6.022944551 |
|Tsíʼdí      |6.010928962 |
|átʼé.       |5.925925926 |
|Tsiʼdí      |5.917159763 |
|rokʼe       |5.792400371 |
|nííkʼeh     |5.734513274 |
|’i          |5.714285714 |
|Tï          |5.597014925 |
|vaiʼéi      |5.525606469 |
|níítʼéé     |5.278921752 |
|Tsíʼdó      |5.215686275 |
|iîïíīįì     |5.209580838 |
|jeʼex       |5.187032419 |
|Yìy         |5.007824726 |
|firrʼe      |5.002405002 |
|iñeʼẽ,      |4.993597951 |
|nookʼoʼob,  |4.986933798 |
|jeʼelel     |4.938759384 |
|haʼevaʼerã: |4.912207358 |
|Tî          |4.850746269 |
|įj.,        |4.840370752 |
|jì          |4.835164835 |
|jî          |4.835164835 |
|îi          |4.835164835 |
|fiîlî       |4.780564263 |
|Kótʼe       |4.747116238 |
|Vì          |4.722550177 |
|omeʼẽ       |4.693274205 |
|bikʼeh      |4.678585013 |
|koʼoleloʼob,|4.678478997 |
|kweʼé       |4.642857143 |
|kwéʼé       |4.642857143 |
|haʼóra      |4.64028777  |
|jóokʼol     |4.53435647  |

You can see a pattern here, with words containing `ʼ` (U+02BC MODIFIER LETTER APOSTROPHE) having the biggest increase. The smaller the "word", the bigger the impact of a single glyph. The character is used in e.g. Navajo. The other characters have intentionally changed to better fit the font's texture: punctuation, i-like characters, ...

We were actually wondering about U+02BC. In current main, the Text has a large negative kern for the glyph following the apostrophe in e.g. the word `kʼé`, while the Display doesn't. Our designer wondered whether this was intended and what the rationale was?

image

Width decreases:

|word  |Text Regular|
|------|------------|
|',    |-12.92929293|
|"."   |-11.47540984|
|Ił    |-10.98546042|
|łe    |-10.44776119|
|fa’,  |-10.02747253|
|lł    |-9.897610922|
|į“,   |-9.518935517|
|".    |-9.439528024|
|„”,   |-9.415584416|
|„”.   |-9.415584416|
|ła    |-9.371671991|
|łà    |-9.371671991|
|la’,  |-9.262048193|
|la’.  |-9.262048193|
|lá’,  |-9.262048193|
|łu    |-9.243697479|
|łaał  |-9.129738388|
|atď.  |-9.026644916|
|'',   |-9.016393443|
|''.   |-9.016393443|
|i'.   |-8.852005533|
|I',   |-8.823529412|
|I'.   |-8.823529412|
|tà’,  |-8.809359945|
|sa’,  |-8.333333333|
|tło   |-8.00304878 |
|„“,   |-7.792207792|
|„“.   |-7.792207792|
|“”,   |-7.729468599|
|“”.   |-7.729468599|
|łu.   |-7.438016529|
|wo’,  |-7.395498392|
|tła   |-7.370054306|
|ľa    |-7.24801812 |
|łaʼ   |-7.148659626|
|ułóż  |-7.117969139|
|teď   |-7.102803738|
|6°    |-7.04845815 |
|fù’, |-6.828938472|
|Inc.“,|-6.818181818|
|ri',  |-6.624319419|
|łegałe|-6.589403974|
|yił   |-6.588447653|
|…'    |-6.564102564|
|9,    |-6.553398058|
|9     |-6.553398058|
|ti',  |-6.525735294|
|la'.  |-6.520031422|
|kilo’,|-6.465517241|
|płi   |-6.419753086|

Here, you see a lot of punctuation and `ł` (U+0142 LATIN SMALL LETTER L WITH STROKE) being intentionally tightened.

**Comment by belluzj** [comment]
I rebased this work on top of current main.

Compared to last time we pushed to this branch, I have not deleted all metric keys. But I'll open an issue to explain why it may be useful to look into QA'ing/validating metrics keys, and maybe getting rid of some.

**Comment by belluzj** [comment]
Sorry for the noise, I converted to draft again because I spotted something, this PR creates kerning between groups that don't exist. I'll fix that and mark as ready again once it's done.

**Comment by chrissimpkins** [comment]
@belluzj I spoke with Evan and Nyshadh today.  We will need to push the kerning/spacing improvements and the cap height figure transition back to Q4 / v11.000 release.  They are still working through screenshot diff issues with previous releases and will not be prepared to tackle a new batch of updates until later in the year.

**Comment by belluzj** [comment]
Noted, thanks for the update.

**Comment by chrissimpkins** [comment]
> Noted, thanks for the update.

Sorry Jany.  This is a change from their previous decision.  They aren't ready for the changes on the original timeframe that we previously discussed.

**Comment by MariannaPaszkowska** [comment]
@belluzj Here is first part of my review of the sources. Still in progress. Please review and fix those pairs/classes if necessary. Please review all masters:
1. Regular 18pt
Upright: `εν ҒА Ѓо дз Ẁu Ӱд го аҵ дҹ`
Italic: `ΒΔ ϊν ξί ВА дҹ Ѓо го ҳо до рд Кӫ ТЈ Δή Ӧз Ba дз`
2. Bold 18pt 
Upright: I haven't found any new issues. 
Italic: `ΒΔ ϊν ξί ВА дҹ Ѓо BƐ vo ΡΑ рӡ`

4. Regular 17pt
Upright: I haven't found any new issues. 
Italic: I haven't found any new issues. 

5. Bold 17pt:  
Upright:`ҟә` seems a little loose.  
Italic: `ϊν`

HalfKern didn't find anything new.

**Comment by belluzj** [comment]
@MariannaPaszkowska Thanks for these. On our side, Eduardo will wait for your signal that you've reviewed all the weights before starting to act on your feedback. Does that work for you?

Also, he asks whether the Regular and Medium that you've reviewed are Display or Text cuts?

Thanks in advance!

**Comment by MariannaPaszkowska** [comment]
Hi @belluzj yes, please wait till I'm finished :) I'll let you know. Those were display styles. I'll update the comment

**Comment by MariannaPaszkowska** [comment]
@belluzj I finished the review. Overall, this is wonderful work! Great improvements. I found only a few issues. Let me know if this comment is sufficient or if you need any other data. Many thanks!

**Comment by belluzj** [comment]
Thanks for the speedy review Marianna! I forwarded [your comment here](https://github.com/googlefonts/googlesans/pull/333#issuecomment-1988877610) to Eduardo and we'll push to this branch once he has done the fixes.

**Comment by belluzj** [comment]
@MariannaPaszkowska I pushed fixes from Eduardo that he did today. Some notes from him:


> - Some of fixes were considerably small (5-15 units)
> - Ӱд pair was considerably made tighter to go better with Ӱн
> - Δή was not fixed as it would look inconsistent with Alpha and it would demand that all straights to be kerned against Delta
> - I fixed some other pairs that related to the fixes to ensure consistency

**Comment by MariannaPaszkowska** [comment]
Hi @belluzj I noticed that the spacing in `1` has changed, is this intentional?

**Comment by MariannaPaszkowska** [comment]
Otherwise, new kerning looks good! Great job!

**Comment by belluzj** [comment]
@MariannaPaszkowska yes the spacing change to /one is intentional. Please find below the message from Eduardo about this:

> I reviewed the figures, and I noticed that the figure one was actually tight on the right side.
> I've made adjustments to the spacing of figure one, in pink in the following PDF. Could Marianna confirm whether adjusting the advance width is acceptable to address this issue or if she prefers maintaining the current spacing and resolving it through only kerning (though it's not the recommended approach)?

Please have a look at the attached PDF and let us know what you think. Thanks in advance!

[2024-01-12b_GoogleText_ComparisonDoc (1).pdf](https://github.com/googlefonts/googlesans/files/14697241/2024-01-12b_GoogleText_ComparisonDoc.1.pdf)

**Comment by MariannaPaszkowska** [comment]
I see, many thanks! This is to address https://github.com/googlefonts/googlesans/issues/589

**Pull request merged**
