### PR TITLE
[WIP] Merge Georgian script

### LINKED ISSUE #87: Georgian script merge (old)
**Note**: superseded by https://github.com/googlefonts/googlesans/issues/309

---

Target release v3.004

Tracker for the Georgian merge work

### Downstream Sources for Merge

https://github.com/razmadzekoko/google-sans/tree/master/source/Marged_with_current_Latin_26.06.2020

Downstream files added to Georgian branch in https://github.com/googlefonts/googlesans/commit/955fd4272dfecd70fcf6f29262ce1a0e09fd24f5

Downstream files modified to normalize *.glyphs text in preparation for the merge in https://github.com/googlefonts/googlesans/commit/0315e54a3e15dbe2174f48f34b76bbaf0643b9ab

### TODO

- [x] normalize downstream source files with new glyphsLib script (script added in #89, this change made in https://github.com/googlefonts/googlesans/commit/0315e54a3e15dbe2174f48f34b76bbaf0643b9ab)
- [x] merge all *-georgian outlines
- [x] merge all *-loclGEO outlines (includes localized punctuation)
- [x] confirm semicolon-loclGEO bracket layers @ [18] (see https://github.com/googlefonts/googlesans/issues/58#issuecomment-691965326)
- [x] merge paragraph-georgian.case
- [x] merge lari currency symbol outline
- [x] merge lari tabular and case form outlines (#88)
- [x] merge kerning
- [x] merge geor_uppercase and geor_lowercase glyph classes
- [x] add spaces.all glyph class (converted name to spaces_all)
- [x] add punctuation.all glyph class (converted name to punctuation_all)
- [x] add punctuation.centered glyph class (converted name to punctuation_centered)
- [x] merge fea code updates
    - [x] case
    - [x] locl
    - [x] calt
    - [x] lari currency symbol case and tnum updates (#88)
- [x] rename spaces.all, punctuation.all, punctuation.centered to spaces_all, punctuation_all, punctuation_centered in fea code (names changed to maintain consistency with other feature classes)
- [x] update Unicode range with Georgian script
- [x] update language systems registrations with Georgian script
- [ ] fix `calt` feature code for Georgian alpha-Latin punctuation-Georgian position of colon + semicolon (see https://github.com/googlefonts/googlesans/pull/93#issuecomment-702830282)

### Questions for Akaki

- [x] tabular form of lari currency symbol? (decision: to be designed and will be merged into v3.004 updates)
- [x] case form of lari currency symbol? (decision: to be designed and will be merged into v3.004 updates)
 
--- 

cc @razmadzekoko

### LINKED ISSUE #88: Add Georgian lari currency symbol tabular and case forms
Akaki is working on the designs for the tabular and case forms of the new lari currency symbol that will be included in the v3.004 release of GS.  Discussed with him today.

### PR DESCRIPTION
**Pull request by chrissimpkins**
Changes tracked in https://github.com/googlefonts/googlesans/issues/87

Closes #87
Closes #88

This PR merges the new Georgian script designs by Akaki Razmadze

---

### TODO

- [x] Akaki review of source and builds following merge
- [x] Chris fix calt feature issue identified with Georgian punctuation positioning (https://github.com/googlefonts/googlesans/pull/93#issuecomment-702830282)
- [ ] review case feature in MS Word
- [x] Akaki review of VF format
- [ ] VF only - semicolon.loclGEO defined with bracket layers `[18]`, in VF do not get the appropriate localized form with the feature code in https://github.com/googlefonts/googlesans/pull/93#issuecomment-702830282 @ max opsz only (works for min opsz).  How do we get at the semicolon.BRACKET.18 outline for max opsz only via feature code?
- [ ] Chris QA

### CODE REVIEW

**Comment by chrissimpkins** [comment]
CI tests will fail for now.  The fontbakery character set checks will need to be updated with the new Georgian glyph set to pass FB tests.

**Comment by chrissimpkins** [comment]
@razmadzekoko Akaki, the merge is complete and I am building files in https://github.com/googlefonts/googlesans/actions/runs/265499142. You can use the download links to grab the variable and static font files for review.  The latest commits of the source files are available in this directory / branch https://github.com/googlefonts/googlesans/tree/chrissimpkins-georgian-merge/source/GoogleSans

Please confirm that you received this message and that you will be able to review the files over the next couple of weeks.  Please use the issue report thread https://github.com/googlefonts/googlesans/issues/87 for comments / problems as you work through the files (or feel free to open a new issue if it warrants it).  Thanks!

cc @gorjious (see above for the latest state of the source, we'll likely be ~ at this base as we begin your merge)

**Comment by chrissimpkins** [comment]
Please note: use the builds in the `expert` subdirectories for your review

**Comment by chrissimpkins** [comment]
Discussion with Akaki re: Georgian merge:

- Need to fix `Georgian - Latin punctuation - Georgian position of semicolon/colon` (this was a combination that was missed in first iteration of the feature code)

Add the following to calt feature:

```
sub @geor_lowercase @punctuation_all colon' by colon.loclGEO;
sub @geor_lowercase @punctuation_all semicolon' by semicolon.loclGEO;
```

**Comment by chrissimpkins** [comment]
@razmadzekoko Akaki, can there be a space between the Latin punctuation and semicolon / colon that requires vertical position adjustment?

Like this: `[Georgian alphabetic][Latin period][space][Latin semicolon that needs Georgian positioning]`

**Comment by chrissimpkins** [comment]
> Discussion with Akaki re: Georgian merge:
> 
> * Need to fix `Georgian - Latin punctuation - Georgian position of semicolon/colon` (this was a combination that was missed in first iteration of the feature code)
> 
> Add the following to calt feature:
> 
> ```
> sub @geor_lowercase @punctuation_all colon' by colon.loclGEO;
> sub @geor_lowercase @punctuation_all semicolon' by semicolon.loclGEO;
> ```

Fixed in https://github.com/googlefonts/googlesans/pull/93/commits/10a5de25d13003b0a59166f3ea19e40b917c7261

**Comment by razmadzekoko** [comment]
there are some issues we discussed during the call:
1. calt feature for punctuation_centered have problems in Adobe Illustrator and Photoshop but works in Indesign, it works perfect at FontGoggles as well. I used this text to test it: მეო-  dgo-
2. locl feature can be problematic for Georgian texts so we add some lines in calt feature like:
```
sub @geor_lowercase @punctuation_all colon' by colon.loclGEO;
sub @geor_lowercase @punctuation_all semicolon' by semicolon.loclGEO;
```
I used this text to test it:  მეო.:  dgo.:

The other things looks nice so far, I will continue looking at it and if something shows up I will inform you.

**Comment by madig** [comment]
Is this out of date and can be closed?

**Comment by chrissimpkins** [comment]
> Is this out of date and can be closed?

Yes, this is correct.  Maintained for posterity in case we needed any of the information during this second merge round

**Pull request closed without merging**
