### PR TITLE
Adds support for localised punctuation in Devanagari; fixes #336

### LINKED ISSUE #336: Devanagari locl feature support for punctutation
From https://github.com/googlefonts/googlesans/issues/304#issuecomment-851984728

Also, the following glyphs are unreachable (no Unicode value, no sub in features, not used as components):

    asterisk.loclDEVA
    braceleft.loclDEVA
    braceright.loclDEVA
    bracketleft.loclDEVA
    bracketright.loclDEVA
    colon.loclDEVA
    comma.loclDEVA
    ellipsis.loclDEVA
    exclam.loclDEVA
    parenleft.loclDEVA
    parenright.loclDEVA
    period.loclDEVA
    question.loclDEVA
    quotedblleft.loclDEVA
    quotedblright.loclDEVA
    quoteleft.loclDEVA
    quoteright.loclDEVA
    rh-deva
    semicolon.loclDEVA
    v-deva.alt5
    yy-deva.alt4

### PR DESCRIPTION
**Pull request by kalapi**
Adds the support for localised Devanagari-specific Latin punctuation as described in #336 

Closes https://github.com/googlefonts/googlesans/issues/336

### CODE REVIEW

**Comment by madig** [comment]
Can you please give us a test string?

**Comment by kalapi** [comment]
> Can you please give us a test string?

Hello @madig, hope you're well! I'll test the fonts once they're compiled and post both screenshots and test strings.

**Comment by chrissimpkins** [comment]
Looks like the glyph set / order files need to be updated.  I will address this later today.

**Comment by chrissimpkins** [comment]
> Can you please give us a test string?

It looks like this is the list for dev2 locl support:

asterisk braceleft braceright bracketleft bracketright colon comma ellipsis exclam parenleft parenright period question quotedblleft quotedblright quoteleft quoteright semicolon

I'll prep shaping files today and will push all of this to this branch.

**Comment by chrissimpkins** [comment]
I can address this @madig.  Pub time for you. :)

Thanks Kalapi! I'll send a link to files later today.  Mind having a look on Monday?  If things look ok with the subs on my end, I'll likely merge this today and we can continue to work on it as necessary if you recognize any issues.

**Comment by kalapi** [comment]
Hi Chris, i'm adding the missing Devanagari glyphs to the `.glyphsetdef` files now.

**Comment by chrissimpkins** [comment]
> Hi Chris, i'm adding the missing Devanagari glyphs to the `.glyphsetdef` files now.

We have a script for it.  No need Kalapi.  I can take care of this.  Thank you!

**Comment by chrissimpkins** [comment]
See https://github.com/googlefonts/googlesans/issues/336#issuecomment-877334246 though

**Comment by chrissimpkins** [comment]
@googlebot I consent.

**Comment by chrissimpkins** [comment]
New glyphsetdef files pushed in 865151bfaba91b3f34336246fc6e3c071a446247

**Comment by chrissimpkins** [comment]
harfbuzz shaping regression output JSON file pushed in 7f2ba50167e336e56d2c3747d4ccfcbe1a579ee3

LGTM. @kalapi let me know what you think.  I added `quotedbl` and this does not appear to have a localized form.  Should it?  Everything else seems to appropriately sub to the loclDEVA form in the `dev2` (in harfbuzz `deva`) locale.

**Comment by chrissimpkins** [comment]
Building files for you in https://github.com/googlefonts/googlesans/actions/runs/1016015403

The static and variable font archives will show up in that link in several minutes.

**Comment by chrissimpkins** [comment]
Minor localized ellipsis issue Roman vs. Italic on the opsz axis range.  See https://github.com/googlefonts/googlesans/issues/336#issuecomment-877403104

Not a deal breaker.  Let's merge this.

**Comment by chrissimpkins** [comment]
@kalapi I am going to leave this branch for now in case you want to continue work in it.

**Comment by kalapi** [comment]
> harfbuzz shaping regression output JSON file pushed in [7f2ba50](https://github.com/googlefonts/googlesans/commit/7f2ba50167e336e56d2c3747d4ccfcbe1a579ee3)
> 
> LGTM. @kalapi let me know what you think. I added `quotedbl` and this does not appear to have a localized form. Should it? Everything else seems to appropriately sub to the loclDEVA form in the `dev2` (in harfbuzz `deva`) locale.

I think it should, but I didn't because the default version was using bracket layers. We can add it to the next release.

**Comment by chrissimpkins** [comment]
Kalapi reviewed and approved the imported changes.

https://github.com/googlefonts/googlesans/issues/304#issuecomment-879934005

**Comment by chrissimpkins** [comment]
@kalapi I am going to delete this branch as work is now done here.

**Pull request merged**
