### PR TITLE
Import Devanagari for v4

### LINKED ISSUE #148: Merge Devanagari script
Tracking thread for the Devanagari script merge

### LINKED ISSUE #303: Harfbuzz shaping input files use ISO 15924 script tags
Documented @ https://en.wikipedia.org/wiki/ISO_15924

It looks like this is the problem with the Devanagari shaping files.  We are using Microsoft OpenType spec script tags in the shaping files and they are not always the same. The docs state:

> Script tags generally correspond to a Unicode script. However, the associations between them may not always be one-to-one, and the OpenType script tags are not guaranteed to be the same as Unicode Script property-value aliases or ISO 15924 script IDs.

The hb-shape help states:

>  --script=ISO-15924 tag                 Set text script (default: auto)

When I convert the `dev2` lang tag to `deva` hb-shape shows the expected localized output with `locl` text run testing.

cc @madig @kalapi

### PR DESCRIPTION
**Pull request by madig**
TODO
- [x] WARN: The following mark characters could be in the GDEF mark glyph class:       U+0903, U+093B, U+093E, U+093F, U+0940, U+0949, U+094A, U+094B, U+094C, U+094E and U+094F [code: mark-chars]
- [x] add git sha hashes to the new JSON shaping regression test files
- [x] remove or uncomment commented out Dev fea code (https://github.com/googlefonts/googlesans/pull/277#issuecomment-842554502) - Kalapi wants to keep it in commented out form.  He will be using it in a future update to the script.
- [x] Discuss JSON shaping output, are we seeing the correct output? (fixed, we needed to change the script tag spec)

### Issues that will be addressed following the merge

Opened #304 to track these issuees

- [x] fix virama position on jha, italic only, opsz 18 only (https://github.com/googlefonts/googlesans/pull/277#issuecomment-841416147) - requires fix
- [x] ja-tha half form junction (https://github.com/googlefonts/googlesans/pull/277#issuecomment-842579017) - requires fix
- [x] bha-ca half form junction (https://github.com/googlefonts/googlesans/pull/277#issuecomment-842589171) - requires fix
- [x] la-nya half form junction (https://github.com/googlefonts/googlesans/pull/277#issuecomment-842593802) - requires fix
- [ ] va-va half form overlap alignment (https://github.com/googlefonts/googlesans/pull/277#issuecomment-842596932) - requires fix
- [ ] base rakaar form text run nukta positions (https://github.com/googlefonts/googlesans/pull/277#issuecomment-842635371) - requires fix
- [ ] base - rakaar join separation (https://github.com/googlefonts/googlesans/pull/277#issuecomment-842640788) - requires fix

---

Closes #303 
Closes #148

### CODE REVIEW

**Comment by madig** [comment]
@kalapi fontbakery says these should be GDEF marks:

image

Should they?

**Comment by moyogo** [comment]
No, we need to fix the fontbakery check so it only warn for Mark non-spacing, these are Mark spacing.

**Comment by moyogo** [comment]
I've opened a PR: https://github.com/googlefonts/fontbakery/pull/3198

**Comment by chrissimpkins** [comment]
Kalapi will push shaping regression testing strings as toml definition files to this branch

**Comment by chrissimpkins** [comment]
@madig I spoke with Kalapi today.  Once the shaping text run definitions are pushed to this branch, he feels that we are in a good position to build and distribute files to him so that he can have a look.  The next step will be to uncomment a space character shaping feature (to be pushed in this branch too) that he wants to review pre/post, build again, and review.  He has expected shaping changes and text runs for this issue so we will be able to use the hb shaping tests to review it along with his visual eval.

**Comment by chrissimpkins** [comment]
@kalapi Kalapi will you please let us know how things look for timing of the feature updates and shaping text runs for this merge?

**Comment by madig** [comment]
I reimported the Deva sources from https://github.com/googlefonts/googlesans/issues/148#issuecomment-778155929, on top of the latest Armenian changes.

**Comment by kalapi** [comment]
@madig @chrissimpkins 

Hey! Here are the new sources with extended features and the TOML files (in `docs>qa>shaping_input`).

We've decided to not modify the space glyph using OTL because the differences are too small. 

Please let me know if you have any questions.

[GoogleSans_Devanagari_R03.zip](https://github.com/googlefonts/googlesans/files/6280204/GoogleSans_Devanagari_R03.zip)

**Comment by chrissimpkins** [comment]
Thanks Kalapi! We will ping you when this is merged and we are able to build fonts for your review.  I really appreciate it!

**Comment by madig** [comment]
@kalapi this also changes TextBold's `k-deva.alt7` and `la-deva.loclMAR` and Bold's `la-deva.loclMAR` to have a 1 font unit change for some point. Intentional?

I merged your new changes. Please also have a look at the shaping output in the JSON files.

**Comment by kalapi** [comment]
Hello! Yes this is intentional (the _shirorekha_ had a minor issue). 

Having a look at the JSON output now, thank!

**Comment by chrissimpkins** [comment]
@madig status here Nikolaus?  This is marked as a draft.

**Comment by madig** [comment]
Waiting for green light from Kalapi 🚀

**Comment by kalapi** [comment]
Ready for **lift-off**!  ✳️

**Comment by chrissimpkins** [comment]
Seems to be no diff in the rakaar forms across Marathi <--> Nepali:

```shell
$ diff qa/shaping/devanagari_marathi_ortho_rakaar_forms.json qa/shaping/devanagari_ne
pali_ortho_rakaar_forms.json
```

```diff
<     "language": "mr",
---
>     "language": "ne",
```

I *think* that this is as expected because our Marathi fea code seems to specify that the Marathi localized `sha`, `halant`, `ra` sequence should result in the same substituted form as in the Nepali locale.  Is this correct @kalapi? 

```fea
feature rkrf {
    script dev2;
    lookup dev2_dflt_mar_nep_rkrf_rakar_forms {
        sub da-deva halant-deva ra-deva by d_ra-deva;
        sub ta-deva halant-deva ra-deva by t_ra-deva;
        sub ha-deva halant-deva ra-deva by h_ra-deva;
        sub sha-deva halant-deva ra-deva by sh_ra-deva;
    } dev2_dflt_mar_nep_rkrf_rakar_forms;

    language MAR;
    lookup dev2_dflt_mar_nep_rkrf_rakar_forms;
    lookup dev2_mar_rkrf_rakar_forms {
        sub sha-deva.loclMAR halant-deva ra-deva by sh_ra-deva;
    } dev2_mar_rkrf_rakar_forms;

    language NEP;
    lookup dev2_dflt_mar_nep_rkrf_rakar_forms;
} rkrf;
```

**Comment by chrissimpkins** [comment]
Seems to be no shaping regression test coverage of the `locl` GSUB fea support for localized Marathi / Nepali consonant and numeral forms?

```fea
feature locl {
    script dev2;
    language MAR;
    lookup dev2_mar_locl_localised_consonants {
        sub la-deva by la-deva.loclMAR;
        # Marathi La
        sub sha-deva by sha-deva.loclMAR;
        # Marathi Sha
    } dev2_mar_locl_localised_consonants;

    lookup dev2_mar_nep_locl_common_localised_numerals {
        sub eight-deva by eight-deva.loclMARNEP;
    } dev2_mar_nep_locl_common_localised_numerals;

    language NEP;
    lookup dev2_nep_locl_localised_consonants_numerals {
        sub jha-deva by jha-deva.loclNEP;
        # Nepali Jha
        sub one-deva by one-deva.loclNEP;
        sub five-deva by five-deva.loclNEP;
        sub nine-deva by nine-deva.loclNEP;
    } dev2_nep_locl_localised_consonants_numerals;

    lookup dev2_mar_nep_locl_common_localised_numerals;
} locl;
```

**Comment by kalapi** [comment]
Thanks @chrissimpkins

1. Your observation re. the Rakaar coverage in `ne` and `mr` is correct.

2. I'll look into this and add the relevant tests for the `locl` feature tests.

**Comment by chrissimpkins** [comment]
Thanks Kalapi!

Re: 2, I'd be happy to add them if you paste the strings into this thread.  Not a problem at all.  I can interpret the appropriate GSUB from the glyph names and will re-gen the JSON files.

**Comment by kalapi** [comment]
@chrissimpkins Here you go!

[marathi_nepali_localised.zip](https://github.com/googlefonts/googlesans/files/6477407/marathi_nepali_localised.zip)

**Comment by chrissimpkins** [comment]
Thanks Kalapi!

**Comment by chrissimpkins** [comment]
@madig  is this issue in the OP addressed?

> WARN: The following mark characters could be in the GDEF mark glyph class: U+0903, U+093B, U+093E, U+093F, U+0940, U+0949, U+094A, U+094B, U+094C, U+094E and U+094F [code: mark-chars]

**Comment by chrissimpkins** [comment]
> @madig is this issue in the OP addressed?
> 
> > WARN: The following mark characters could be in the GDEF mark glyph class: U+0903, U+093B, U+093E, U+093F, U+0940, U+0949, U+094A, U+094B, U+094C, U+094E and U+094F [code: mark-chars]

By this maybe? https://github.com/googlefonts/googlesans/pull/277#issuecomment-797421057

**Comment by madig** [comment]
I think @moyogo said this was a too-eager fontbakery?

Edit: ha, yeah. Maybe we need to update fontbakery here.

**Comment by moyogo** [comment]
Yes, while these are mark characters, their glyphs a spacing marks so they typically aren't in the GDEF Mark Glyph Class.
This was fixed in googlefonts/fontbakery#3198 which landed in fontbakery 0.7.35.

**Comment by chrissimpkins** [comment]
@kalapi 

It looks like there is an issue with the position of the ~~virama~~ halant form of Ra (?) relative to the jha across the weight masters in opsz 18, italic only - default locale

jha_virama

**Comment by chrissimpkins** [comment]
@googlebot I consent.

**Comment by chrissimpkins** [comment]
For some reason, I'm not getting the proper locl glyphs in the JSON output files @ https://github.com/googlefonts/googlesans/pull/277/commits/b1a813ae70c904c21728c85ca78afe452124adf7.  Not sure what is going on. The BCP tags seem to be ok, locl is set to true, and spot checks in Font Goggles suggest that the proper locl forms are sub'd. Thoughts?

**Comment by chrissimpkins** [comment]
> For some reason, I'm not getting the proper locl glyphs in the JSON output files @ [b1a813a](https://github.com/googlefonts/googlesans/commit/b1a813ae70c904c21728c85ca78afe452124adf7). Not sure what is going on. The BCP tags seem to be ok, locl is set to true, and spot checks in Font Goggles suggest that the proper locl forms are sub'd. Thoughts?

This seems to be an issue across a number of the shaping files.  I am finding the same issue in the devanagari_default_ortho_conjuncts.json file.

The input string:

```
ङ्य
```

should form a conjunct that is defined by the unencoded `ng_yadeva` glyph.  

What we see in the shaping output JSON file is:

```
"uni0919=0+662,0|uni094D=0@-476,3|uni092F=2+588,0"
```

These are the decomposed nga, halant, and ya components of the conjunct rather than the ligature glyph form.

The shaping is defined by the `cjct` fea code:

```fea
sub ng-deva ya-deva by ng_ya-deva;
```

**Comment by chrissimpkins** [comment]
OK for this feature code to go away or is this meant to be uncommented?

https://github.com/googlefonts/googlesans/blob/b1a813ae70c904c21728c85ca78afe452124adf7/source/GoogleSans/devanagari.fea#L45-L47

**Comment by chrissimpkins** [comment]
Slight notch at junction in the Ja-Tha half form opsz 18, wght 700, italic only

**Comment by chrissimpkins** [comment]
Slight gap at junction of Bha-Ca half form: opsz 18, wght 700, italic only

**Comment by chrissimpkins** [comment]
La-Nya half form is not joined in italic source, opsz 18 only, all weights

**Comment by chrissimpkins** [comment]
Va-Va half form peek-a-boo :) italic only, opsz 17 and 18, wght 400 only

**Comment by chrissimpkins** [comment]
Beautiful stuff Kalapi.  👍

**Comment by chrissimpkins** [comment]
This is from your base rakaar form text run.  Are the nukta positions correct here?

**Comment by chrissimpkins** [comment]
Bit of separation of between rakaar and base consonant opsz 18, italic only, 700 wght master seems to be the issue. OK at wght=400

**Comment by chrissimpkins** [comment]
Shaping regression files fixed with new ISO 15924 script tags in 

https://github.com/googlefonts/googlesans/pull/277/commits/38421dbbf1c481cef7b9e642c22284752ca5bb02
https://github.com/googlefonts/googlesans/pull/277/commits/dfdd5e7c376c926dbf0721faeac57591a0ead67e

#303

**Comment by chrissimpkins** [comment]
> OK for this feature code to go away or is this meant to be uncommented?
> 
> https://github.com/googlefonts/googlesans/blob/b1a813ae70c904c21728c85ca78afe452124adf7/source/GoogleSans/devanagari.fea#L45-L47

Spoke with Kalapi. This will be used in a future update. We will leave as commented out fea source for now.

**Comment by chrissimpkins** [comment]
Kalapi and I ran through all of the issues identified in this thread.  These are valid issues and will be addressed.   Kalapi will open new threads on the tracker, then we'll merge this PR.  The Devanagari fixes will land in a new PR.

**Comment by chrissimpkins** [comment]
Open issues in this thread will be tracked in https://github.com/googlefonts/googlesans/issues/304.  These will require design edits and updated shaping regression test files

**Comment by chrissimpkins** [comment]
Thanks Nikolaus and Kalapi!  This looks great

**Pull request merged**
