### PR TITLE
Fix `Eng` and `eng` tail outlines

### LINKED ISSUE #284: Issues with glyphs composed with Eng-tail and eng-tail
Eng = U+014a
eng = U+014b

Test string: `Ŋŋ`

1. Eng has been recomposed as `Eng= N + Eng-tail` but Eng-tail is misplaced in some masters or adds a corner between the diagonal and the vertical stem of the tail in some masters.

The fix would probably be to adjust Eng-tail as it is only used in Eng at the moment. It can be reused in a few glyphs in the Latin extension PR.

GoogleSans-opsz18-wght734-GRAD0
image

it is slightly misplaced in GoogleSansItalic-opsz17-wght380-GRAD200 and GoogleSansItalic-opsz18-wght380-GRAD200
image
image

2. eng-tail is now used to compose eng, eng.sc, dje-cy, elhook-cy. It is either too narrow or misplaced in some glyphs in some masters. One issue is that it matches the stem width of el-cy used in elhook-cy which is slightly narrower than the stem width of n used in eng or h used in dje-cy. The stem width difference is more noticeable in some Roman masters but there is a one unite difference in some Italic masters. The vertical weight of the eng-tail is also too heavy in some masters.

The fix could be to fix the vertical weight of the tail and to adjust the stem width of el-cy and eng-tail, and make a separate eng-tail.sc for eng.sc to remove the corner. The eng-tail and the potential eng-tail.sc can be reused in the Latin extension PR.

For example in GoogleSans-opsz18-wght380-GRAD200: 
image
or GoogleSans-opsz17-wght380-GRAD200:
image

The vertical weight of the stroke is too heavy in GoogleSans-opsz18-wght380-GRAD50 and GoogleSans-opsz17-wght380-GRAD50:
image
image

### LINKED ISSUE #380: Remove Engtail component glyph
This was previously used as a component to form the Eng glyph form.  In #379 these outlines were decomposed and the glyph is no longer required in the glyph set.  Let's remove it.

### PR DESCRIPTION
**Pull request by chrissimpkins**
Fixes #284

Sources imported from David Berlow edits in https://github.com/googlefonts/googlesans/issues/284#issuecomment-877116548 with my minor edits to `Eng` and `eng` point definitions in the `GoogleSans-opsz18-wght380-GRAD0.ufo` master  to address an outline incompatibility issue that prevented compiles

### TODO

- [x] Rebase after #374 is merged (glyphsetdef conflict)
- [x] Remove Engtail (https://github.com/googlefonts/googlesans/pull/379/commits/18f7dc3196e1b20d346d27c773088f80fef289bf)
- [x] run `gs-normalize-designspace.py` on the sources, determine what still needs to be scrubbed from source files
- [ ] document glyph removal approach (#369)

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Fix confirmed visually across the full design space.

**Comment by chrissimpkins** [comment]
The Engtail (uppercase) glyph is no longer used after these changes and can be removed from the glyph set. #380 

The engtail (lowercase) glyph is used as a component in `dje-cy`, `elhook-cy`, and `eng.sc`.  These designs will need to be reviewed to see if the fix here is required there.  #381

**Comment by chrissimpkins** [comment]
Engtail removed from expected glyph set QA defs in https://github.com/googlefonts/googlesans/pull/379/commits/d15d2a5a92e6157d92fdccfbaf4f0f387d09cc02. CI should pass following this update

**Comment by chrissimpkins** [comment]
> CI should pass following this update

And it does.  LGTM.  Ready for merge.

**Comment by chrissimpkins** [comment]
The glyph set definition files will conflict with the Tamil merge PR.  I'll hold on this merge and rebase after we merge the Tamil work in #374

**Comment by madig** [comment]
@googlebot I consent.

**Comment by madig** [comment]
I this instance, I ran the following script over the UFOs:

```python
from pathlib import Path

from ufoLib2 import Font

for p in Path("source/GoogleSans/").glob("*.ufo"):
    ufo = Font.open(p)
    for layer in ufo.layers:
        if "Eng-tail" in layer:
            del layer["Eng-tail"]
    if "Eng-tail" in ufo.lib["public.glyphOrder"]:
        ufo.lib["public.glyphOrder"].remove("Eng-tail")
    ufo.save()
```

I guess we can expand on it next time we delete something and then write it down in the docs?

**Comment by chrissimpkins** [comment]
> I this instance, I ran the following script over the UFOs:
> 
> ```python
> from pathlib import Path
> 
> from ufoLib2 import Font
> 
> for p in Path("source/GoogleSans/").glob("*.ufo"):
>     ufo = Font.open(p)
>     for layer in ufo.layers:
>         if "Eng-tail" in layer:
>             del layer["Eng-tail"]
>     if "Eng-tail" in ufo.lib["public.glyphOrder"]:
>         ufo.lib["public.glyphOrder"].remove("Eng-tail")
>     ufo.save()
> ```
> 
> I guess we can expand on it next time we delete something and then write it down in the docs?

:+1: https://github.com/googlefonts/googlesans/issues/369#issuecomment-915344122

**Comment by chrissimpkins** [comment]
Engtail glyph removed from sources in https://github.com/googlefonts/googlesans/commit/18f7dc3196e1b20d346d27c773088f80fef289bf. TODO list updated

**Comment by chrissimpkins** [comment]
Rebased on main branch changes @ https://github.com/googlefonts/googlesans/pull/379/commits/37bf1e78a6aca4e6536000e7d157ce03f1785bb0

**Comment by chrissimpkins** [comment]
Manual trigger of static font CI https://github.com/googlefonts/googlesans/actions/runs/1270495483

**Comment by chrissimpkins** [comment]
CI passed. Visual review across design space LGTM.  Eng / eng tails are all fixed.  Thanks for the fixes @dberlow!  And thanks @moyogo for identifying the issue!

Fix will be released in GS v6.000

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/issues/369 opened for glyph removal docs.  All issues have been addressed here.  OK to merge

**Pull request merged**
