### PR TITLE
Add Direct Current Symbol Form Two (U+2393)

### LINKED ISSUE #535: Add Direct Current Symbol Form Two (U+2393)
The symbol will be used in laser etching on product surfaces, including plastics and metals, at very small text sizes (demo at 3.2pt today). The team attempted to use the symbol available in Noto and found that the top and bottom strokes have a tendency to overlap/blend at these laser etched text sizes. We'll need to take this into consideration as we develop the outlines.  The team is willing to test the designs as we develop. 

@MariannaPaszkowska

### PR DESCRIPTION
**Pull request by Hoolean**
Design work is taking place on a smaller internal repository, but we will import into this branch when we need to produce TTFs with the original build workflow, and to do the final import when the process is complete.

---

After design work is complete:

- [x] Add glyph to `public.glyphOrder`
- [x] Add glyph to `public.postscriptNames`
- [x] Add glyph to italics
- [x] Update glyphsetdef

Closes #535.

### CODE REVIEW

**Comment by madig** [comment]
@chrissimpkins @MariannaPaszkowska I have here imported the newest iteration of the glyph after feedback.

Font build: https://github.com/googlefonts/googlesans/suites/9861906662/artifacts/475677943

**Comment by chrissimpkins** [comment]
The team needed static instance files for testing.  I am pushing a new v11.000 beta 1 release at commit https://github.com/googlefonts/googlesans/pull/545/commits/23936d12ae4c6cf2bab064d2f1bc6b84d2ad44fd so that we have static fonts to distribute to them.  

cc @elenaperaltad @belluzj

**Review by chrissimpkins — APPROVED** [review]

**Comment by chrissimpkins** [comment]
Approved by requesting team and ready for merge from my standpoint.

**Comment by madig** [comment]
No, because there's no italics yet.

**Comment by madig** [comment]
@chrissimpkins @MariannaPaszkowska Here is the addition to the italics.

**Review by MariannaPaszkowska — APPROVED** [review]

**Pull request merged**
