### PR TITLE
Only build variable fonts by default

### PR DESCRIPTION
**Pull request by madig**
See https://github.com/googlefonts/googlesans/issues/464#issuecomment-1069647180.

I removed the upload-artifacts.yml job because I was unsure whether it would work if static and variable jobs are uncoupled and the jobs themselves do not put up their artifacts. So, now you need to get artifacts from the jobs directly.

### CODE REVIEW

**Comment by madig** [comment]
Oh wait! I misread your comment, you want to stop _using_ `build-*` branches but otherwise leave them in. Hm. Then we still need to remove the upload job because the VF job does not put up artifacts?

**Comment by chrissimpkins** [comment]
Yes! We will need to be able to build and QA the static files.  They are still used in production distributions.  We haven't moved to fully VF distributions (yet!)

**Comment by chrissimpkins** [comment]
And we need the upload artifacts workflow.  I use the GHA repository builds for my own QA work.  And these are what we share with design teams as the final post-import WIP builds that use our build workflow.  I'd prefer to keep it this way rather than introduce an individual's local venv and build workflow definition in the process. (i.e., with a push of font files to a PR or IR thread)

**Comment by chrissimpkins** [comment]
My suggestion did not involve any source modifications.  Only branch definition approach mods.  For future imports, we use a PR branch that is not prefixed with `build-*`.  It will only build and QA the VF's in the GHA runner environment.  It will not upload any artifacts for download (_FWIW, the build-* branches were originally intended for intermittent pushes to gain access to the files for human review_). We can push commits to a build-* branch when we are ready to include static instance tests and compile fonts for testers.  This branch doesn't need to be linked to the PR.  From a workflow standpoint, I will always do this once I dive into the review process after the merge happened and before the PR is merged to main.  You *can* do it if you want to see test results as you merge, iterate through issues that arise with design teams during the merge.  You'll need to do it to share the GHA compiled VF files with design teams for review.  And just prior to a tester push seems like a good point to include the instance tests.  We will want to avoid multiple rounds of review if we understand that there is a static font issue and we need to change the sources.

Sgty?

**Comment by madig** [comment]
Ok! :)

**Comment by chrissimpkins** [comment]
See https://github.com/googlefonts/googlesans/issues/464#issuecomment-1074357539

**Comment by madig** [comment]
Noted.

**Pull request closed without merging**
