### PR TITLE
Import Lao

### PR DESCRIPTION
**Pull request by madig**
Closes https://github.com/googlefonts/googlesans/pull/413.

---

@chrissimpkins edits below:

- Test string for tall/deep glyph testing: `ກໍ່ກໍ່ກໍ໊ກໍ໋ກັ່ກັ້ກັ໊ກັ໋ ງູຫຼູ`

### CODE REVIEW

**Comment by madig** [comment]
This needs another pass from a designer on our side and is then ready to be passed over to Cadson Demak for final inspection and then merging.

**Comment by chrissimpkins** [comment]
Did you come across any V metrics related clipping in the Lao?  Or does that issue apply to Khmer only?

**Comment by madig** [comment]
I'll let our designer check this.

**Comment by madig** [comment]
Yes, some tall glyphs clip in Word. The fonts here are otherwise good.

**Comment by chrissimpkins** [comment]
> Yes, some tall glyphs clip in Word. The fonts here are otherwise good.

Thanks! I will have a look later this week.  Global yMin and yMax as set by compiler should reflect the new dimensions?

**Comment by madig** [comment]
Hrm. I think it may be better to use an established "strategy" as described in https://glyphsapp.com/learn/vertical-metrics, as different apps and OSes interpret the values differently.

**Comment by chrissimpkins** [comment]
We set the use typo metrics bit and have hhea=typo a/d metrics.  Win metrics are set to max / min across the set to avoid clipping.  What is your concern with the current strategy and how would you change it?

**Comment by chrissimpkins** [comment]
A few GDEF issues were raised by fontbakery during CI testing of the commits here.  @madig can you comment on these issues?

```
 >> com.google.fonts/check/gdef_spacing_marks
    Check glyphs in mark glyph class are non-spacing.
    with build/GoogleSans/variable/GoogleSans[GRAD,opsz,wght].ttf

      Rationale:                                                                
      Glyphs in the GDEF mark glyph class should be non-spacing.                
      Spacing glyphs in the GDEF mark glyph class may have incorrect anchor     
      positioning that was only intended for building composite glyphs during   
      design.                                                                   

     WARN The following spacing glyphs may be in the GDEF mark glyph class      
          by mistake: uni0A03 (U+0A03), uni0BBF (U+0BBF), uni0BBF.alt           
          (unencoded), uni0BC1 (U+0BC1) and uni0BC2 (U+0BC2) [code:             
          spacing-mark-glyphs]                                                  


    Result: WARN
```

```
>> com.google.fonts/check/gdef_non_mark_chars
    Check GDEF mark glyph class doesn't have characters that are not marks.
    with build/GoogleSans/variable/GoogleSans[GRAD,opsz,wght].ttf

      Rationale:                                                                
      Glyphs in the GDEF mark glyph class become non-spacing and may be         
      repositioned if they have mark anchors.                                   
      Only combining mark glyphs should be in that class. Any non-mark glyph    
      must not be in that class, in particular spacing glyphs.                  

     WARN The following non-mark characters should not be in the GDEF mark      
          glyph class: U+0A03, U+0BBF, U+0BC1 and U+0BC2 [code: non-mark-chars] 


    Result: WARN
```

```
 >> com.google.fonts/check/gdef_spacing_marks
    Check glyphs in mark glyph class are non-spacing.
    with build/GoogleSans/variable/GoogleSans-Italic[GRAD,opsz,wght].ttf

      Rationale:                                                                
      Glyphs in the GDEF mark glyph class should be non-spacing.                
      Spacing glyphs in the GDEF mark glyph class may have incorrect anchor     
      positioning that was only intended for building composite glyphs during   
      design.                                                                   

     WARN The following spacing glyphs may be in the GDEF mark glyph class      
          by mistake: uni0A03 (U+0A03) [code: spacing-mark-glyphs]              


    Result: WARN
```

```
 >> com.google.fonts/check/gdef_non_mark_chars
    Check GDEF mark glyph class doesn't have characters that are not marks.
    with build/GoogleSans/variable/GoogleSans-Italic[GRAD,opsz,wght].ttf

      Rationale:                                                                
      Glyphs in the GDEF mark glyph class become non-spacing and may be         
      repositioned if they have mark anchors.                                   
      Only combining mark glyphs should be in that class. Any non-mark glyph    
      must not be in that class, in particular spacing glyphs.                  

     WARN The following non-mark characters should not be in the GDEF mark      
          glyph class: U+0A03 [code: non-mark-chars]                            


    Result: WARN
```

**Comment by madig** [comment]
These were present before, imported during Devanagari/Gurmukhi/Tamil I think. I remember Kalapi saying they were ok :thinking:

**Comment by chrissimpkins** [comment]
> These were present before, imported during Devanagari/Gurmukhi/Tamil I think. I remember Kalapi saying they were ok 🤔

@kalapi Possible to confirm? If so, it sounds like we should update the data fontbakery side. ping @felipesanches

**Comment by chrissimpkins** [comment]
Once I get the CI passing in https://github.com/googlefonts/googlesans/pull/428, we'll need to rebase here so that we can confirm that the metrics with the Lao design edits meet the new Win metrics criteria and visually confirm that the clipping issue is no longer present in the Win environment.

**Comment by chrissimpkins** [comment]
Rebased onto #428 changes in main @ commit 956c8b0836dd84b7416ee8b33e6c132df8bf1cb4

**Comment by chrissimpkins** [comment]
Test string for tall/deep glyph testing: `ກໍ່ກໍ່ກໍ໊ກໍ໋ກັ່ກັ້ກັ໊ກັ໋ ງູຫຼູ`

**Comment by chrissimpkins** [comment]
Builds @ https://github.com/googlefonts/googlesans/pull/416/commits/956c8b0836dd84b7416ee8b33e6c132df8bf1cb4

MS Word (Office 18.2110.13110.0) on Win 10 tested with Google Sans regular weight via the VF builds.

The clipping is influenced by the vertical line "Spacing" settings options under the Layout menu.

With 0pt before and 0pt after we see clipping:

2021-12-22 12_09_15-Document docx - Word

With 18pt before and 12pt after we see no clipping:


2021-12-22 12_19_43-Document docx - Word

I thought that they would collide across overlapping text runs, but apparently Word handles this with clipping (or we aren't properly calculating the yMax / yMin metrics for the Win Asc / Win Desc settings).  Irrespective of the env specific approach to overlapping contours, I think that a *user* will want to make this line spacing adjustment to properly view multi-line text runs in Lao and other tall/deep char sets.  

I'm not sure that there is any other modification that we can make to address this.  Increasing global line spacing metrics across all scripts to accommodate large/deep glyphs in new merged scripts is not an option.  This may be a user detail for guidance documentation.  In contrast to many typefaces, this one is highly unlikely to find broad use in MS products.  If we do hear about this issue, I think that the next step is to consider Noto style script-specific typeface families with custom typo / hhea metrics definitions for the tall/deep areas of Google Sans.

cc @madig @belluzj @cadsondemakoffice 

cc @davelab6

**Comment by chrissimpkins** [comment]
Here is the text that I used in the above examples if anyone wants to reproduce locally:

```
ກໍ່ກໍ່ງູຫຼູກໍ໊ກໍ໋ງູຫຼູກັ່ກັ້ກັ໊ກັ໋ 
ກໍ່ກໍ່ກໍ໊ກໍ໋ງູຫຼູກັ່ກັ້ງູຫຼູກັ໊ກັ໋ 
ກໍ່ກໍ່ງູຫຼູກໍ໊ກໍ໋ງູຫຼູກັ່ກັ້ກັ໊ກັ໋

ABCabc0123
ABCabc0123 
```

**Comment by davelab6** [comment]
@chrissimpkins I suggest to email Si about this, you can put it in a PDF for him and I'll send you his contact info

**Comment by chrissimpkins** [comment]
D/W Cadson-Demak team this week.  They approved the latest builds for prod push.

**Comment by chrissimpkins** [comment]
> I suggest to email Si about this, you can put it in a PDF for him and I'll send you his contact info

Discussion with Si in progress.

**Comment by madig** [comment]
What is the desired outcome of the discussion? Does it block the merge?

**Comment by chrissimpkins** [comment]
> What is the desired outcome of the discussion? Does it block the merge?

I don't believe so.  My plan is to move ahead with metrics as is and we can update if necessary based on the feedback from Si.  Do you have any concerns about current v metrics? I believe that you raised a tall/deep concern on one of the threads over the last month.

**Comment by madig** [comment]
The concerns came from designers, who found Khmer cut off in Office apps. I am not aware of other apps cutting glyphs off.

Btw, the concept of script tallness is known to the Android team: https://material.io/archive/guidelines/style/typography.html# -- Maybe this is something to keep in mind for Google Sans (Flex) and to bake into usage guidance? And maybe even to cut the family into sub-families?

**Comment by chrissimpkins** [comment]
> Btw, the concept of script tallness is known to the Android team: https://material.io/archive/guidelines/style/typography.html#

An Android Text eng fix for the tall/deep glyph issue (in non-Latin scripts relative to Latin) is in the works after years of persuasion by Dave. 👍  I think that the persuasion included *intentionally not* constraining non-Latin scripts to Roboto / Noto UI Latin v metrics in Google Sans. :) 

Let's see what they come up with.  

Completely agree that we need to keep this in mind and that it should be included in guidance.

> And maybe even to cut the family into sub-families?

The multi-script merged approach came from the top of the Fonts eng chain.  We're trying to merge everything that we can with an understanding that there are some scripts (e.g., CJK due to glyph repertoire size, Arabic/Urdu/Persian due to outline dimensions) that will not land in the "Google Sans" family.  They will be "Google Sans X" script families. All design teams are aware of the Pixel Android environment v metrics text rendering issue.  We discuss this with them at the outset of design work. The goal with this project is that it is first, and foremost, a branding typeface and UI-specific design compromises that lead to inappropriate v compression of forms (or alternatives like H distribution of features that would typically be stacked in the v dim) are avoided.  

Please do continue to raise issues if you or the DaMa design reviewers come across any general or env-specific issues with this approach.  We need to understand those problems to consider separate families.  The design vendors are informing the decision about the ability to merge their designs into the "Google Sans" family under the v metrics constraints.

**Comment by chrissimpkins** [comment]
Minor edit to the ccmp_lao shaping def file in https://github.com/googlefonts/googlesans/pull/416/commits/0f5bf9f9d3794dfe056d8427b765a6462b0c5b5c

Otw, LGTM.

**Comment by chrissimpkins** [comment]
## File size changes with Lao import

VF format only

### Main branch

```
build/GoogleSans/variable/GoogleSans[GRAD,opsz,wght].ttf

             Summary Statistics              
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃                    Statistic ┃   Size (B) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│                        Total │ 1166816.00 │
│ Avg per encoded glyph (1885) │     619.00 │
│   Avg per total glyph (3547) │     328.96 │
└──────────────────────────────┴────────────┘
```

```
build/GoogleSans/variable/GoogleSans-Italic[GRAD,opsz,wght].ttf

             Summary Statistics              
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃                    Statistic ┃   Size (B) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│                        Total │ 1236132.00 │
│ Avg per encoded glyph (1885) │     655.77 │
│   Avg per total glyph (3543) │     348.89 │
└──────────────────────────────┴────────────┘
```

### This branch

```
build/GoogleSans/variable/GoogleSans[GRAD,opsz,wght].ttf

             Summary Statistics              
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃                    Statistic ┃   Size (B) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│                        Total │ 1232024.00 │
│ Avg per encoded glyph (1968) │     626.03 │
│   Avg per total glyph (3672) │     335.52 │
└──────────────────────────────┴────────────┘
```

```
build/GoogleSans/variable/GoogleSans-Italic[GRAD,opsz,wght].ttf

             Summary Statistics              
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃                    Statistic ┃   Size (B) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│                        Total │ 1310872.00 │
│ Avg per encoded glyph (1968) │     666.09 │
│   Avg per total glyph (3668) │     357.38 │
└──────────────────────────────┴────────────┘
```

**Comment by chrissimpkins** [comment]
I moved the open issue about Windows env/MS product v metrics and the conversation with Si Daniels to https://github.com/googlefonts/googlesans/issues/435 so that we can track his response and act on any recommendations.  I think that we are set to merge this branch.

**Comment by madig** [comment]
> Please do continue to raise issues if you or the DaMa design reviewers come across any general or env-specific issues with this approach. We need to understand those problems to consider separate families. The design vendors are informing the decision about the ability to merge their designs into the "Google Sans" family under the v metrics constraints.

Will do. I suppose the same applies to Google Sans Flex?

**Comment by chrissimpkins** [comment]
> I suppose the same applies to Google Sans Flex?

Yep!

**Pull request merged**
