### PR TITLE
Add fontmake transformed components decompose filter

### LINKED ISSUE #459: Transformed components
We now fail on the new fontbakery check:

```
 >> Check:   com.google.fonts/check/transformed_components
    Desc:    Ensure component transforms do not perform scaling or rotation.
    Files:   GoogleSansText-MediumItalic.ttf

     FAIL The following glyphs had components with scaling or rotation:

           • uni0547 (component uni0549)
           • uni0577.sc (component uni0579.sc)
           • eternityarmrf (component eternityarmlf)
           • uni0A51 (component uni0A4D)
           • uni1CB9 (component uni1C92)
           • uni1CBE (component uni1CB2)
           • uni10F9 (component uni10D2)
           • uni10FE (component uni10F2)
           • uni1207 (component _geezpart11)
           • uni12AF (component _geezpart11)

          [code: transformed-components]
    Result: FAIL
```

---

Includes components from Armenian, Ethiopic, Georgian, Gurmukhi

### PR DESCRIPTION
**Pull request by chrissimpkins**
Closes #459

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Static font CI run was manually triggered in https://github.com/googlefonts/googlesans/runs/5338428639?check_suite_focus=true

**Comment by chrissimpkins** [comment]
It looks like this addresses the fontbakery fail in VF and static artifacts.  The CI still fails because of #458

**Comment by chrissimpkins** [comment]
Rebased on #461.  CI should pass after the rebase.

Manual trigger of the static font tests at commit https://github.com/googlefonts/googlesans/pull/460/commits/2ee1acc7b4349d4600c3217ffbe274c472f00365 in https://github.com/googlefonts/googlesans/runs/5339452576?check_suite_focus=true

**Comment by chrissimpkins** [comment]
Ok, we're closer. The "Font Bakery GS profile" tests now pass. The "Font Bakery character set profile" tests fail with the changes.  I need to update the expected char set lists from the fonts built with the decomposed component edits.

**Comment by madig** [comment]
I'm not sure what you did, but this PR decreases file size:

```
Main:
-rw-r--r-- 1 nikolaus nikolaus 1520540 Feb 28 11:31 'GoogleSans-Italic[GRAD,opsz,wght].ttf'
-rw-r--r-- 1 nikolaus nikolaus 1417164 Feb 28 11:30 'GoogleSans[GRAD,opsz,wght].ttf'

This PR:
-rw-r--r-- 1 nikolaus nikolaus 1479000 Feb 28 11:36 'GoogleSans-Italic[GRAD,opsz,wght].ttf'
-rw-r--r-- 1 nikolaus nikolaus 1381156 Feb 28 11:35 'GoogleSans[GRAD,opsz,wght].ttf'
```

Edit: it seems a chunk of GPOS about base anchors evaporated.

**Comment by chrissimpkins** [comment]
Here is what happens to the glyph set when we decompose transformed components ==> https://github.com/googlefonts/googlesans/pull/460/commits/5efe7ebdb02a262ab2c4437fb119f0b800887390

**Comment by chrissimpkins** [comment]
Glyph set tests pass with the updates in https://github.com/googlefonts/googlesans/commit/5efe7ebdb02a262ab2c4437fb119f0b800887390

Armenian, Gurmukhi, and Devangari shaping tests fail with these updates.  I will have a look to see what changes.

Edit: and Hebrew...

**Comment by madig** [comment]
(Have a look at the regression test strings that fail and see if they look different, maybe that's easiest to spot check)

**Comment by chrissimpkins** [comment]
Hmm. It looks like there are some metrics changes in the HB shaping output diffs.  On the initial pass through the Armenian I see a handful of horizontal displacement changes relative to the previous shaping QA output.  I'll have a look at the text runs with changes in Font Goggles.  Let me see what is going on in Gurmukhi and Devanagari and I'll push the updated shaping json files.

Edit: and Hebrew...

**Comment by chrissimpkins** [comment]
There are shaping regressions with these changes. In images below, the top font in Font Goggles is our v7 production build and the bottom font is the build at commit https://github.com/googlefonts/googlesans/pull/460/commits/2ee1acc7b4349d4600c3217ffbe274c472f00365 in this branch.

Armenian test string with `U+055B` that has horizontal offset changes:

`և՛ ﬔ՛ ﬕ՛`



Gurmukhi test string with `uni0A4D0A39` that has horizontal offset changes:

`ਜ਼੍ਹ ੜ੍ਹ ਫ਼੍`



Devanagari test string with `uni094D0930.diagonal` that has horizontal offset changes:

`फ़्र य़्र`



Hebrew test string with `uni05B6` and `uni0591` that have horizontal offset changes:

`רָקִ֑יעַ מִקֶּ֑`


@madig @belluzj Any thoughts about why the decompose transformed components filter might be leading to these issues?

**Comment by chrissimpkins** [comment]
> I'm not sure what you did, but this PR decreases file size:
> 
> ```
> Main:
> -rw-r--r-- 1 nikolaus nikolaus 1520540 Feb 28 11:31 'GoogleSans-Italic[GRAD,opsz,wght].ttf'
> -rw-r--r-- 1 nikolaus nikolaus 1417164 Feb 28 11:30 'GoogleSans[GRAD,opsz,wght].ttf'
> 
> This PR:
> -rw-r--r-- 1 nikolaus nikolaus 1479000 Feb 28 11:36 'GoogleSans-Italic[GRAD,opsz,wght].ttf'
> -rw-r--r-- 1 nikolaus nikolaus 1381156 Feb 28 11:35 'GoogleSans[GRAD,opsz,wght].ttf'
> ```
> 
> Edit: it seems a chunk of GPOS about base anchors evaporated.

We must be losing some valid and required GPOS data...

**Comment by madig** [comment]
Ah. See the `fontmake --help` entry for --filter, it overwrites the filters in the UFO. We lose anchor propagation, that's why stuff breaks.

You have to put it into the UFO's filter lib key, probably as the first entry. Then, regression tests pass :) VF file size increases by 2-4 KB. Permission to overwrite this PR with the commit?

**Comment by chrissimpkins** [comment]
> Permission to overwrite this PR with the commit?

Ty! Yes, please do.

**Comment by chrissimpkins** [comment]
Or just paste what line(s) I need to add here.  We'll need to modify the shaping regression test definition files again.  I can take care of that.

**Comment by madig** [comment]
I force pushed over the other commits :)

**Comment by chrissimpkins** [comment]
> I force pushed over the other commits :)

ok, np

**Comment by chrissimpkins** [comment]
Manually triggered the static font checks in https://github.com/googlefonts/googlesans/actions/runs/1917551986

@madig assuming that passes, ok to merge this and we will rebase the Ethiopic and Bangla PR's on the changes?

**Comment by madig** [comment]
Yes :)

**Pull request merged**
