### PR TITLE
Hebrew scaled dagesh

### PR DESCRIPTION
**Pull request by moyogo**
The dagesh dot used in some glyphs has different scaling transformation than the default master in some masters.
This is problematic in variable fonts, since they can only use the scaling transformation from the default master.

- [x] Fix the variable fonts dagesh dot size in pedagesh-hb, pedagesh-hb.BRACKET.18, finalpedagesh-hb, finalpedagesh-hb.BRACKET.18, shindagedh-hb, shindagedhsintdot-hb, shindagedhshindot-hb
  - [x] Add a scaled dagesh-hb.alt with the transformation used in composite glyphs
  - [x] Update composite glyphs
  - [x] Add dagesh-hb.alt to glyhpsetdef

Split from #118 as this doesn't require to update the toolchain requirements.

### CODE REVIEW

**Comment by moyogo** [comment]
See https://github.com/googlefonts/googlesans/pull/118#issuecomment-763610348

Here is a comparison of the modified glyphs שּׁשּׂשּףּפּ in in the variable font with the fix and with the static fonts from 3.003:
image
image
image
image

**Comment by chrissimpkins** [comment]
cc @danielgrumer @fontef

**Comment by chrissimpkins** [comment]
Thank you very much Denis!  This LGTM.

scaled-dagesh

I'll review this with Daniel tomorrow and confirm that he has no concerns.  If not, we will get this merged.  We need to wrap up several other things that are in progress.  We should be able to get this merged soon.

**Comment by danielgrumer** [comment]
> This LGTM.

LGTM2

**Review by chrissimpkins — APPROVED** [review]
LGTM

**Review by madig — APPROVED** [review]
I see no problem with adding this but can't say anything about the visual changes 😬.

**Comment by chrissimpkins** [comment]
> I see no problem with adding this but can't say anything about the visual changes 😬.

Sg!  I reviewed the designs with Daniel earlier this week.  All looks well across the full weight and opsz axis range.

**Comment by chrissimpkins** [comment]
Will merge today.  Thank you very much @moyogo!  And thanks for having a look to make sure that we are in good shape here @danielgrumer!

**Comment by madig** [comment]
Maybe rebase to master first to see if it trips any regression tests.

**Comment by chrissimpkins** [comment]
changelog 0ef508f550059986acfc3fc6df1556b45e91a733

**Comment by chrissimpkins** [comment]
@moyogo Will you please delete your branch if you no longer need it?

Thanks again for these changes!

**Pull request merged**
